### ISSUE TITLE
Multiple-origin web publications 

### ISSUE THREAD

**Issue by dauwhe** [w3c/wpub#10]
Issue #5 included lots of discussion of whether multiple-origin web publications should be allowed, and what some of the problems might be. Let's have that particular discussion here. 

I believe there is wide agreement that we shouldn't restrict things like web fonts or scripts to be same-orgin as the WP, given such things are so common on the web. So the issue is more about what old epub folk might call "spine items".

**Comment by lrosenthol** [comment]
Someone (I forget who, sorry) made a good point in the original thread that
the answer we choose for WP may *not* be the same answer as PWP or as
EPUB4.  (which is, of course, the reason that we structured the different
specs the way we did).

**Comment by HadrienGardeur** [comment]
> I believe there is wide agreement that we shouldn't restrict things like web fonts or scripts to be same-orgin as the WP, given such things are so common on the web. So the issue is more about what old epub folk might call "spine items".

Why should we restrict "spine items" if we don't (and can't) restrict the rest?

Let's be consistent and simply acknowledge the fact that on the Web, a publication can be spread across multiple domains or sub-domains.

**Comment by lrosenthol** [comment]
On Mon, Jul 17, 2017 at 12:07 PM, Hadrien Gardeur <notifications@github.com>
wrote:

> I believe there is wide agreement that we shouldn't restrict things like
> web fonts or scripts to be same-orgin as the WP, given such things are so
> common on the web. So the issue is more about what old epub folk might call
> "spine items".
>
> Why should we restrict "spine items" if we don't (and can't) restrict the
> rest?
>
> For a Web Publication - I fully agree.

However, as we move to PWP and EPUB4 profiles, we will need to be more
strict (about all types of non-same-origin) content from a security
perspective.

**Comment by murata0204** [comment]
I propose that the FPWD allows multi-domain publications and also provides possible reasons (security, packaging/unpackaging, and compatibilities with EPUB3) for imposing restrictions in the future.

**Comment by wareid** [comment]
As discussed on Feb 4 2019, closing this issue in favour of issues #321 and #374.
