### ISSUE TITLE
Requirement for an HTML document

### ISSUE THREAD

**Issue by mattgarrish** [w3c/wpub#108]
Picking up from issue #103, I'm wondering if having a required HTML document as a publication resource is a separate need from what the manifest address resolves to.

As already explored in issue #94, there are many useful reasons for having at least one HTML document, not the least of which is that it would clearly align a web publication with the Web App Manifest model. It also provides at least one document that will work in a "webby" way for vanilla-anything (user agents, spiders, etc.).

We've been arguing about the need for this in the context of the address, which probably muddies the questions, as what the address resolves to is a separate question and there are many different opinions on that given all the possible addresses a web publication might have.

If an HTML document is not a required resource, we appear to have a problem with the address: it may force the content creator to put an HTML page up on the web for the sole sake of satisfying a manifest requirement (i.e., because web publications themselves won't be required to include html documents).

So, with that history out of the way, is it reasonable to make it a requirement that all web publications must include at least one HTML resource that links to the manifest?

If so, we could potentially remove the designation of it being an entry page and just have it as a construction requirement. The address could be decoupled from it without changing its requirements, but now there would always be a document it can refer to, and that authors will already be providing as an up-front requirement.

**Comment by llemeurfr** [comment]
> requirement that all web publications must include at least one HTML resource that links to the manifest

I agree with this assertion

I'll just comment that the notion of "inclusion" in a Web Publication is still fuzzy. If it means that this resource must be referenced in the manifest (in or out of the reading order), then it makes things tangible. 

**Note 1** I'm among those who think that a sufficient rationale of this requirement is to provide vanilla-browsers with a way to access the publication (we should avoid mixing it with discussions about WAM). Therefore calling it a "start" or "entry" or "landing" page is fine by me. 

**Note 2** such a document can easily be created automatically by publishing workflows (in case the presence of this new resource is perceived as a burden for current publishing workflows).

**Comment by iherman** [comment]
> I'll just comment that the notion of "inclusion" in a Web Publication is still fuzzy. If it means that this resource must be referenced in the manifest (in or out of the reading order), then it makes things tangible.

Yes, we were sloppy. But yes, at least as far as I am concerned, that is what I meant.

**Comment by caraya** [comment]
>If an HTML document is not a required resource, we appear to have a problem with the address: it may force the content creator to put an HTML page up on the web for the sole sake of satisfying a manifest requirement (i.e., because web publications themselves won't be required to include html documents).

Most publishers already do this for their books and resources in a catalog or other sales points.  Would it be wrong to consider this a landing page and the starting point for a user to interact with the publication?

**Comment by mattgarrish** [comment]
I've merged the prose that reflects this change in PR #110, so closing this issue.
