### ISSUE TITLE
Minor editorial issues (grammar)

### ISSUE THREAD

**Issue by WSchindler** [w3c/wpub#114]
In Chapter 1.2 "The manifest includes metadata that describe**s** the Web Publication, ..." should be replaced by "The manifest includes metadata that describe the Web Publication, ..."

In Chapter 3.1 " Some information can be obtained **in outside** the manifest, however." should be replaced by " Some information can be obtained _**outside**_ the manifest, however."

**Comment by mattgarrish** [comment]
Not convinced about metadata being treated as plural, as you don't speak of "metadatum". I've always treated it as "plural in form but singular in construction".
