### ISSUE TITLE
Is WP enhanced web content or a special implementation of the web?

### ISSUE THREAD

**Issue by mattgarrish** [w3c/wpub#12]
This question keeps bothering me as I try to understand whether WP is plain old web content that some user agents can enhance, or a special kind of web content that needs a certain class of user agent to consume.

Unless there is an expectation that all user agents (including browsers) will support the WP enhancements how do we deal with usability/accessibility? Does every publication have to be designed like a regular web site if the author wants it to be usable/accessible to anyone accessing it? Will it have links to the previous and next page if it consists of more than one document, links to the table of contents on every page, etc. in order for users to be able to read it?

If we do expect reasonably universal support, then what are the additions we need to avoid a web interface? (automatic next/previous page navigation, access to a table of contents)

It's hard to know what usability/accessibility look like at the WP level without having a clear idea which scenario is expected.

**Comment by HadrienGardeur** [comment]
A WP is a collection of resources on the Web that are collected together using a simple manifest that contains:

- metadata about the publication
- one or more collection of links

A WP should not:

- require any specific URI convention (URI ending with a /, well-known location)
- restrict how resources are hosted (domain, subdomain, path)
- require content negotiation
- require any specific HTTP header

The design of a WP (presence of various links) is entirely up to the author.

**Comment by rdeltour** [comment]
Thanks for the question Matt, it keeps bothering me as well. I for one would love that WP content would gracefully degrade to non-WP-aware browsers.

**Comment by WSchindler** [comment]
I think we agree that ideally all user agents (including browsers) should be able to consume a WP. What I don't see clearly yet is: What are the distinctive features of a WP in contrast to a traditional complex web site? Is it the explicit manifest or what else?

**Comment by HadrienGardeur** [comment]
@WSchindler the distinctive feature is the manifest.

It provides a declarative way to convey useful information about the publication to a UA.

The UA can then decide to do whatever it wants, for example (just a few ideas):

- preload specific resources to speed things up
- cache these resources for offline reading
- provide specific UI elements to interact with the publication
- save specific metadata to enhance the browser history (I could search in my history using an author's name for instance)
- use the publication's metadata when a Web Publication is added to your device's homepage (similar to Web App Manifest)
- switch to reader's mode when it opens a Web Publication

Dedicated reading apps such as Pocket or Instapaper, could rely on this manifest to save a Web Publication instead of trying to guess how the article can be extracted.

**Comment by lrosenthol** [comment]
@mattgarrish 

> Does every publication have to be designed like a regular web site if the author wants it to be usable/accessible to anyone accessing it? Will it have links to the previous and next page if it consists of more than one document, links to the table of contents on every page, etc. in order for users to be able to read it?

I like to think about it exactly the opposite.  
Every publication *can* be designed like a regular web site, if that is how the author wishes to do so.  All features of the web (including links, navigation elements, etc.) can be included in a publication and a UA will present them to the user (just as it does a standard web page).

In addition, we *may* also choose to provide machine-readable information (in the manifest?) that will help a WP-aware UA to provide alternative user experiences (if it wants).

**Comment by mattgarrish** [comment]
> Every publication can be designed like a regular web site, if that is how the author wishes to do so.

Doesn't this lead to "this publication is only viewable in X" labels, though?

**Comment by dauwhe** [comment]
[Scholarly HTML](http://scholarly.vernacular.io) is a profile of HTML that, among other things, defines that everything outside the first ```<article>``` element in ```<body>``` is ignored by a scholarly html-aware application:

>The article content is everything that is contained inside the first article element in document order that has a typeof="schema:ScholarlyArticle". Everything part of the body outside of that subtree is ignored. This enables publishers to surround the article content with any amount of supporting markup, for instance for headers, footers, or navigation, as well as to wrap the article inside arbitrary markup that may be needed for stylistic reasons.

One thing we could do is to say that WP-aware reading systems should only display what is in ```<main>```, and if publishers need to create their own UI for the proverbial "vanilla browser" it could happen outside ```<main>```.

**Comment by danielweck** [comment]
Interesting and intriguing suggestion, @dauwhe 
This would impose quite a significant authoring requirement to content creators / publishers though.

**Comment by mattgarrish** [comment]
It is intriguing. It also satisfies the need for the user to jump past the repeated content of the publication, something that will be needed for accessibility conformance.

It's not as elegant as EPUB, where authors don't have to concern themselves with things like page-to-page navigation, of course. I'm still trying to understand if that's what we're trying to bring to the Web, too, or just certain technical enhancements like offline-ability.

But if we aren't concerned about an epub being unpackaged to work on the web -- only that it be consumable like a PWP hosted from the web by UAs that recognize the format -- then we sidestep the (painful) duplication it's going to impose to make WPs supported across (non-)conforming UAs. (Of course, every content document will require a ```main``` element.)

The most pain then resides with web authors to make their content work both in enhanced user agents and plain old UAs. I don't know if that's acceptable, but it's less confusing than an hour ago.

**Comment by lrosenthol** [comment]
On Mon, Jul 17, 2017 at 5:06 PM, Daniel Weck <notifications@github.com>
wrote:

> Interesting and intriguing suggestion, @dauwhe <https://github.com/dauwhe>
> This would impose quite a significant authoring requirement to content
> creators / publishers though.
>
Agreed - very interesting indeed!   Thanks for the reference!

**Comment by lrosenthol** [comment]
On Mon, Jul 17, 2017 at 5:37 PM, Matt Garrish <notifications@github.com>
wrote:

> It is intriguing. It also satisfies the need for the user to jump past the
> repeated content of the publication, something that will be needed for
> accessibility conformance.
>
> Why is "jumping past repeated content" an accessibility requirement?


> It's not as elegant as EPUB, where authors don't have to concern
> themselves with things like page-to-page navigation, of course.
>
That's also a failing of EPUB as well, because it doesn't give
authors/publishers any control.


> I'm still trying to understand if that's what we're trying to bring to the
> Web, too, or just certain technical enhancements like offline-ability.
>
IMO, we shouldn't bring anything here to the web - it already has a model
for navigation.   But I know this is one area for discussion/debate...


> But if we aren't concerned about an epub being unpackaged to work on the
> web
>
We certainly believe that a PWP (of which an EPUB 4 is a profile) will
certainly need to be able to work when unpackaged as a regular WP. And
because of this mapping/inheritance model - I would not expect there to be
any problem with this. (that says nothing about EPUB3, which is an issue
for the CG how/if they wish to address it)


> The most pain then resides with web authors to make their content work
> both in enhanced user agents and plain old UAs. I don't know if that's
> acceptable, but it's less confusing than an hour ago.
>
Why is there pain?  I don't see any issue for standard web authors...or for
(P)WP authors.

**Comment by HadrienGardeur** [comment]
> We certainly believe that a PWP (of which an EPUB 4 is a profile) will certainly need to be able to work when unpackaged as a regular WP. And because of this mapping/inheritance model - I would not expect there to be any problem with this. (that says nothing about EPUB3, which is an issue for the CG how/if they wish to address it)

This needs to be its own separate issue, I strongly feel that this not something that can be achieved outside the context of a proxy/CDN.

**Comment by mattgarrish** [comment]
> Why is "jumping past repeated content" an accessibility requirement?

https://www.w3.org/TR/WCAG20/#navigation-mechanisms-skip

> That's also a failing of EPUB as well, because it doesn't give
> authors/publishers any control.

You have control through the default reading order in the spine. You don't have to duplicate and maintain the default reading order in two places (and table of contents, and metadata, etc.), which is what you get in a degradable web publication.

> will certainly need to be able to work when unpackaged as a regular WP

Sure, but whether a publisher expects it to be unpackaged onto the web is their choice. They can bypass this built-in redundancy if not is what I was trying to suggest, since an EPUB doesn't have to work with a vanilla browser. You can make EPUB content entirely for an EPUB ecosystem, where this duality doesn't exist.

**Comment by lrosenthol** [comment]
On Mon, Jul 17, 2017 at 6:46 PM, Matt Garrish <notifications@github.com>
wrote:

> Why is "jumping past repeated content" an accessibility requirement?
>
> https://www.w3.org/TR/WCAG20/#navigation-mechanisms-skip
>
Assuming that we needed Level A, sure.   But there are (currently) no
requirements that a WP be accessible at any level... (which I know will be
a huge debate amongst the community)


> That's also a failing of EPUB as well, because it doesn't give
> authors/publishers any control.
>
> You have control through the default reading order in the spine. You don't
> have to duplicate and maintain the default reading order in two places (and
> table of contents, and metadata, etc.), which is what you get in a
> degradable web publication.
>
Today, sure.  But reading order isn't a requirement (at this time), so I
could only have it in one place.

You really need to stop thinking in EPUB 3.x terms.  We aren't trying to
build - with WP - an EPUB clone.  That's what EPUB 4 is for.

WP will be a much more lightweight approach to publications - because it
needs to be the common foundation for any type of publication both on the
web or off.



> will certainly need to be able to work when unpackaged as a regular WP
>
> Sure, but whether a publisher expects it to be unpackaged onto the web is
> their choice.
>
Whose choice?  The publishers?  Not necessarily.  An online book store or a
University might choose to republish in expanded form.


> They can bypass this built-in redundancy if not is what I was trying to
> suggest, since an EPUB doesn't have to work with a vanilla browser. You can
> make EPUB content entirely for an EPUB ecosystem, where this duality
> doesn't exist.
>
 Are you speaking about EPUB 3 or 4?  I don't believe that EPUB 4 will have
all the same attributes as EPUB 3...

**Comment by mattgarrish** [comment]
> Assuming that we needed Level A, sure.

You asked why bypass blocks are an accessibility consideration. If you can't even meet Level A, you don't have an accessible publication. Seamlessness with accessibility concerns is a good thing in my book.

I appreciate your faith in the web and that we build this without any undue consideration for how people will make content, but that's only one view. As I've said already, I'd like to understand the design decisions we're placing on authors and the experience of users to judge the approaches, and simply understand what publications will look like. Building in a technology bubble is a bad idea.

> We aren't trying to build - with WP - an EPUB clone.

I never said we were. I'm trying to understand what the common foundation is and how a WP has to be built to handle its various needs, and what that means for the intersection of WP and EPUB.

> WP will be a much more lightweight approach to publications

This, again, seems to depend on the person. In NYC, it was suggested that EPUB might just be WP with some additional requirements for accessibility. I'm not judging approaches, but which prevails will shape the nature of publications.

**Comment by laudrain** [comment]
In Web Publication, I still consider **Publication** to have its own reality that may differs from this of a Web Site: WP content is **published**: it has a date of publication, any part of its content can be refered to as being found is **that publication** (with metadata title, authors, identifier, date, copyright, ...).
I think this is true not only for books and journal articles.

IMO, this should not lead to special User Agent to consume (why IDPF/W3C merge?) but more in specific rules on designing OWP content (like I understand Scholarly HTML is doing).
This would bring some burden on authoring, but certainly not much more than today's EPUB rules.

**Comment by TzviyaSiegman** [comment]
This issue is addressed by https://github.com/w3c/wpub/issues/52 Web Publication affordances, as discussed in meeting on [2017-08-28](https://www.w3.org/2017/08/28-pwg-minutes.html#item04).

**Comment by iherman** [comment]
See [telco discussion](https://www.w3.org/publishing/groups/publ-wg/Meetings/Minutes/2017/2017-08-28-minutes#section3) on closure.
