### ISSUE TITLE
Do we consider a (JSON) manifest to be part of a `<script>` element

### ISSUE THREAD

**Issue by iherman** [w3c/wpub#122]
The HTML (and JSON-LD) specs allow for such content to be part of an HTML `<script>` element. Would we consider this as a possible place for a Web Publication Manifest?

**Comment by iherman** [comment]
Two points in favor:

1. For very simple WP-s, having the manifest as part of the (possibly only) HTML file in the WP may make the full WP structure way simpler
2. One of the reasons to consider JSON-LD as a syntax is that schema.org could then extract the metadata information and include it into, e.g., the Google Knowledge Graph. I am not sure schema.org would follow a `<link>` element, though...

**Comment by llemeurfr** [comment]
Seems like a hack ... it would mean that publication metadata (scope = a set of documents) is in one specific HTML document, in a place where the user agent expects JS code. Or, if this is an option, that there are several options for representing metadata. And options are always a pain for user agents.

**Comment by dauwhe** [comment]
This is not only how JS works, but how CSS works—you can link to an external file, or include it directly. I'd be wary of taking away authoring flexibility to make life easier for user agents.

**Comment by iherman** [comment]
I am not sure "one specific HTML document, in a place where the user agent expects JS code" is correct. The JSON-LD is perfectly separate and can use whatever `@id` it wants.

As for the "hack": first of all, it is a perfectly valid usage of the `<script>` element. There is no hack. Also, see any example on schema.org (just [picked one at random](http://schema.org/ContactPoint)) which uses exactly that. There are also [some recent crawl data](http://webdatacommons.org/structureddata/2017-12/stats/stats.html) which show that around 10% of all Web Pages use _embedded_ JSON-LD as source of metadata. I would not call that a hack either...

**Comment by iherman** [comment]
Oops, @mattgarrish, indeed, my bad.

Except that #25 seems to be more general, and the separate discussion thread on gist looks at alternatives (like `data` URLs or `<meta>` elements) that are not addressed here.

Also, the schema.org issue was not relevant at the time, which gives this special flavor.

I will close #25, referring to this one.

**Comment by BigBlueHat** [comment]
@llemeurfr it's not a hack. They're known as "data blocks" in the HTML spec:
https://www.w3.org/TR/html5/semantics-scripting.html#data-block

**Comment by mattgarrish** [comment]
I don't think script is a hack, but it introduces complexity as we discussed previously. It fits with one case where you want everything in one page, but isn't that encapsulation problem perhaps more relevant to pwp scenarios?

The appendix that Romain referenced in #25 makes a good point that when the manifest is embedded it becomes more costly to figure out if the web page has changed or the manifest.

It also means we have two externalizing mechanisms: link and script/@src.

If we allow embedding, we have to consider that people will do it even for multi-document publications. I can see this leading to confusion (e.g., people replicating their manifest across every document in the publication, or not understanding why they embedded it in one but then have to link from others). This is education, of course, but I agree with @llemeurfr that more ways of doing things isn't always better.

**Comment by iherman** [comment]
Note that, as one of the commenters on that gist [remarked](https://gist.github.com/marcoscaceres/7783977#gistcomment-964282), you can do it today, per standards, the following ways:

```
<link rel="something" href="#data"></link>
<script id="data" type="application/json+ld">
...
</script>
```

in other words, the lifecycle must deal with that case, too (I do not think it does)...

**Comment by llemeurfr** [comment]
@BigBlueHat, ok for the 'data-block'. My other remarks were 1/ metadata about the whole publication (= a set of documents) set in one of these documents. I would be more relax if  embedding the manifest was exclusively targeting mono-document publications in the spec (which would solve 1/ and simplify the processing model IMO).

**Comment by mattgarrish** [comment]
And you can also do it as a data: url in the link element and avoid script, too.

**Comment by iherman** [comment]
Please let us not data urls, those are horrible:-)

**Comment by BigBlueHat** [comment]
@HadrienGardeur do you mean from some other primary resource?

**Comment by HadrienGardeur** [comment]
Well, using the media-type is slightly problematic as well.

if we use the default JSON-LD media type, there's no way of easily identifying that a resource belongs to a publication without parsing the JSON document itself (plus, we'd have to rely on the context or some other properties to identify a WP Manifest).

If we roll our own media type, it's easy to identify that the script contains a WP manifest, but we lose some of the benefits stated by @iherman previously: crawlers won't index these metadata unless they have specific WP support.
Crawlers usually have flaky support for JSON-LD, some of them are completely unaware of context documents and treat JSON-LD as pure JSON + schema.org.

FYI, in [RWPM we list three different methods for discovering a manifest](https://github.com/readium/webpub-manifest#discovering-a-manifest): `link` in HTML, `Link` in HTTP header and `script` in HTML. But we adopted a dedicated media type plus the `manifest` rel instead of a dedicated rel value like in the WP infoset (`publication`).

**Comment by HadrienGardeur** [comment]
Hmm, I forgot about the `profile` media type parameter though. This could identify the WP Manifest, but I think that my comment about crawlers is still relevant (they might skip the `script` element because they don't handle media type paramters and/or LD).

**Comment by iherman** [comment]
@llemeurfr 

> My other remarks were 1/ metadata about the whole publication (= a set of documents) set in one of these documents. I would be more relax if embedding the manifest was exclusively targeting mono-document publications in the spec (which would solve 1/ and simplify the processing model IMO).

There is a big difference between the `<meta>` elements, for example, and the data block. The `<meta>` element are metadata _for the enclosing document_, i.e., it would be semantically wrong to use them for WP metadata. But there is no such association of a data block and the enclosing document. If I store JSON-LD in a data block, I would be required to add a `@id` term anyway, and that sets the semantics right. Ie, I do not see that as a major problem.

That being said, I would agree with you that the usage of a data block for a manifest becomes really useful for publications that consist of one HTML file (plus accompanying files for, say, data). But that is a major use case in my view: scholarly publications are a typical case. For such publications the ease of creating and maintaining this would be very beneficial.

**Comment by iherman** [comment]
@HadrienGardeur 

> Hmm, I forgot about the profile media type parameter though. This could identify the WP Manifest, but I think that my comment about crawlers is still relevant (they might skip the script element because they don't handle media type parameters and/or LD).

Yes, it is indeed messy. But, that being said, it goes both ways: I am not sure schema.org does collect data from JSON-LD when it is in a separate file linked via `<link>`; it relies on embedded JSON-LD only.

(I wonder if @danbri can comment on this...)

**Comment by danbri** [comment]
Schema.org does not collect data.

**Comment by iherman** [comment]
@danbri but schema.org does collect embedded JSON-LD in an HTML content, doesn't it? Otherwise how does it use JSON-LD?

**Comment by danbri** [comment]
Search engines use JSON-LD and Microdata and RDFa; At Schema.org we define the schemas. We also give some examples in those formats, but they are not exclusive or final - e.g. some projects use schema.org schemas in Turtle syntax. The project was launched with a fairly strong "use microdata" message but that is now more pluralistic, which softened the prescriptive tone. Microdata probably remains the most widely supported syntax in terms of large search engine implementations, but JSON-LD seems to be the trend.

Currently all the examples on Schema.org for JSON-LD do use the script element as a wrapper within HTML. This is also the only format that Google shows in its main documentation for schema.org structured data. I understand that Bing can use that style of JSON-LD in several places, if perhaps not everywhere at this time (/cc @tmarshbing), I guess but don't know that Yandex is similar - you might check their [validator](https://tech.yandex.com/validator/) which does handle JSON-LD.

Google's JSON-LD extraction is also applied after Javascript has been run for a while against the document, this allows widgets etc to inject structured data. We have also experimented with using it in a more feed-like style but I don't believe that is publicly documented. Schema.org itself doesn't say a lot about these options. It's a delicate balance between pluralism vs confusing publishers with every possible encoding and publication style.

**Comment by iherman** [comment]
Thanks @danbri !

**Comment by HadrienGardeur** [comment]
It's also worth pointing out that AMP relies on schema.org + JSON-LD in `script` as well.

**Comment by HadrienGardeur** [comment]
Some additional context:

- RWPM explicitly allows embedding its manifest in a script element
- I couldn't find anything about embedding in the draft for the WAM

**Comment by iherman** [comment]
I think it was considered for the WAM and rejected at some point (there was a separate discussion on a gist).

**Comment by dauwhe** [comment]
I think the manifest should be embedded via `script` in the entry page. 

1. This allows a web publication to consist of a single resource. As Ivan notes, this is a major use case in itself. And there's some advantage to having a single solution, instead of a special case for this.

2. It provides a single home for information about the publication, which was a strong request in #193. Note that this decision is independent of any decision about expressing any aspect of the infoset in HTML or JSON. This makes for an easy story to tell: "A web publication needs an entry page, which contains information about the publication". 

3. Publication metadata becomes discoverable without scripting. 

Here's an example (which I haven't JSON-LD'd because I'll leave the @id stuff to my betters):

```html
<!DOCTYPE html>
<html>
  <head>
    <title>Journal of Applied Cetology, May 2018</title>
    <script type="application/json">
    {
    "spine": [{
        "href": "classification/index.html"
      },
      {
        "href": "fin/index.html"
      }
    ],
    "address": "www.example.com/Journal/2018/05/",
    "reading-progression": "ltr",
    "resources": [
      "classification/index.html", "fin/index.html"
    ]
  }
   </script>
   <link rel="stylesheet" href="../../../reader.css">
  </head>
  <body>
    <nav role="doc-toc">
      <ol>
        <li><a href="classification/index.html">Whale Classification in Moby-Dick</a></li>
        <li><a href="fin/index.html">The Semiotics of Fins</a></li><!--these are WPUBs also!-->
      </ol>
    </nav>
  </body>
</html>
```

I've been building prototypes with both embedded and linked metadata, and if you're creating the WP at the publication URL, embedded is easier. You don't have to use `fetch()` to get the manifest, and you avoid lots of fooling around with promises :)

A reading system using WPUB still has to look in the entry page to find the link to the manifest; having the manifest there shouldn't be an insurmountable obstacle.

**Comment by dauwhe** [comment]
Note that an embedded manifest doesn't prevent linking to it from other files:

```html
<link rel="publication" href="www.example.com/Journal/2018/05/#wpub-manifest">
```

> ... and if your publication contains more than a single resource in its reading order, it becomes more difficult to deal with an embedded JSON than a linked one.

Much depends on the architecture. If (as I mentioned) I'm creating the web publication at the URL of the web publication, then it's quite easy, as all my script is already running in the window of the start page. Is it that difficult to grab the content of the script element from somewhere else?

> That's also incorrect.
> If all infoset items are expressed using JSON, wherever we include that JSON becomes the "single home for information".
> This is not tied to how we embed JSON.

WPUB requires an HTML entry page. So by "single home of information" I mean that all of the requirements of a web publication can be satisfied with a single file, whether or not we choose to serialize some of that information in HTML.

**Comment by HadrienGardeur** [comment]
@dauwhe while it doesn't prevent linking, the fact that the manifest is buried behind a media fragment identifier and an HTML document makes it harder to access (and slower since you'll need to fetch an HTML document that's potentially much larger + parse HTML).

I wouldn't hide the most important part of our infoset behind something that can be so easily broken.

**Comment by iherman** [comment]
This is now part of the spec.
