### ISSUE TITLE
Covers are currently missing from our infoset

### ISSUE THREAD

**Issue by HadrienGardeur** [w3c/wpub#128]
Covers are extremely useful for ebooks as well as audiobooks, but we don't mention them at all in our current infoset.

I believe that this requires an update of our infoset.

**Comment by HadrienGardeur** [comment]
With the current WebIDL from the draft, I introduced the concept of links to our manifest: https://w3c.github.io/wpub/#link-webidl

This could be enough for covers (they could also be listed in `resources` which contains the list of resources), but we need to either identify a rel value (nothing seems an ideal fit in the IANA link registry) or create one.

For comics, the concept of an alternate cover is very important as well. schema.org has a dedicated property for it: http://bib.schema.org/variantCover

**Comment by HadrienGardeur** [comment]
A question about this was sent in December to the IANA link registration list: https://mailarchive.ietf.org/arch/msg/link-relations/f_sraVSVWym6o3VkeT6Tl-mBt7I

Unfortunately no one answered.

**Comment by dauwhe** [comment]
If we extend Web Application Manifest, we could use the `icons` member for covers.

**Comment by HadrienGardeur** [comment]
Correct, and if we extend the WAM, we'll need to define multiple new values for `purpose`: https://w3c.github.io/manifest/#purpose-member

That said, we'll need to be extra careful if the cover is only marked as such in `icons` and not in the list of resources:

- most UAs expect image resources in `icons` to have the ratio of a square
- we could end up with cropped covers being displayed on the homescreen when a publication is installed (something that authors and publishers would hate)

**Comment by HadrienGardeur** [comment]
Could we have covers in our infoset as a first step?

cc @iherman @mattgarrish

**Comment by mattgarrish** [comment]
> Could we have covers in our infoset as a first step?

Seems like a no-brainer to me.

**Comment by HadrienGardeur** [comment]
I'm closing this issue since it was covered in #156.
