### ISSUE TITLE
WP affords alternative modalities

### ISSUE THREAD

**Issue by TzviyaSiegman** [w3c/wpub#133]
[2.1.3 Alternative modalities](https://www.w3.org/TR/pwp-ucr/#multimedia)
The notion of a Web Publication should enable specific publications like audio books, graphics books, and mixed media.
(picking up from https://github.com/w3c/wpub/issues/52)

**Comment by HadrienGardeur** [comment]
This partially duplicates #78

**Comment by iherman** [comment]
Dave Cramer & Marisa will make a writeup for this affordance, based on the discussion on 2018-05-31

**Comment by marisademeglio** [comment]
#134 covers timed media (audio, audio+text, video + transcript), so I think that just leaves graphics, which IMO is handled by HTML and wouldn't require anything extra from us; but are there use cases (that have been brought to our attention) that would challenge this?

**Comment by wareid** [comment]
Affordances addressed in the UCR document, as mentioned in the meeting on Feb 4 2019, I am closing this issue.
