### ISSUE TITLE
WP affords "paging" through a publication

### ISSUE THREAD

**Issue by TzviyaSiegman** [w3c/wpub#137]
[2.1.10 Pagination](https://www.w3.org/TR/pwp-ucr/#pagination)
It should be possible to see the Web Publication in a “paginated” view.
picking up on #52 
See also https://w3c.github.io/wpub/#feature-presentation

**Comment by HadrienGardeur** [comment]
We also have something in our draft: https://w3c.github.io/wpub/#aff-pagination

**Comment by iherman** [comment]
Josh will make a writeup for this affordance, based on the discussion on 2018-05-31

**Comment by wareid** [comment]
Affordances addressed in the UCR document, as mentioned in the meeting on Feb 4 2019, I am closing this issue.
