### ISSUE TITLE
previous and next via link relations

### ISSUE THREAD

**Issue by dauwhe** [w3c/wpub#14]
As we talk about the reading order of a web publication, we should at least acknowledge that HTML already has link relationships to describe the previous and next documents in a sequence.

A reader could even navigate to the next document by pressing the space bar in pre-Blink Opera. I believe Firefox had UI as well, but it was removed. Various browser extensions still provide this functionality.

**Comment by murata0204** [comment]
#18 is one possibility.   Given a URI for a part-in-(P)WP, it becomes possible to get the URI of the manifest.

**Comment by dauwhe** [comment]
The working group consensus (conference call of 28 August 2017)  is that these particular HTML link relations are "irrelevant" to web publications.

**Comment by iherman** [comment]
See [telco discussion](https://www.w3.org/publishing/groups/publ-wg/Meetings/Minutes/2017/2017-08-28-minutes#section3) on closure.
