### ISSUE TITLE
WP affords offline reading capabilities.

### ISSUE THREAD

**Issue by jmulliken** [w3c/wpub#141]
A WP can be read in a browser offline with no change in fidelity from the online experience

**Comment by TzviyaSiegman** [comment]
See also https://github.com/w3c/wpub/issues/22

**Comment by HadrienGardeur** [comment]
The "no change in fidelity" part is IMO somehow problematic.

If a resource depends heavily on JS + APIs, there will be a pretty massive impact in "fidelity", yet there's really nothing we can do about this.

**Comment by jmulliken** [comment]
I wonder if there's something we can adapt from web-archiving technologies that are able to capture and play back certain JS. For example, see the web-archived JS-heavy  https://webrecorder.io/sup/enchanting-the-desert/20170706223633/http://enchantingthedesert.com/console/

It's slow to load, but once it does, it presents the same fidelity and functionality as the live site (http://enchantingthedesert.com).

**Comment by iherman** [comment]
@jmulliken is there some sort of a more precise "definition" for this fidelity term in archival circles? I agree it could be an excellent starting point for WP-s in general...

**Comment by TzviyaSiegman** [comment]
From [Edge feedback](https://lists.w3.org/Archives/Public/public-publ-wg/2018Apr/0008.html):

- The manifest-based approach could make sense for very static content, but it seems the web publications also want to make use of the dynamic nature of the web. How does that work? If I take a web publication offline, can it be updated? Do I need to re-download the whole thing again? How does versioning work?
- •	Figure 1 shows how the parts are related. HTML documents (which are viewed as resources listed in the infoset) may include other resources not listed in the infoset--Are these things not considered part of the publication? What is to be done about them when using the manifest to take the publication offline?
- Is an offline WP a PWP? Or is that a separate concept?
- Who is responsible for taking the WP offline? The book author or the browser? Or both?
-

**Comment by TzviyaSiegman** [comment]
Further from Edge:
In Scope section:
1.3 Scope
The spec seems expressly interested in having the web publication stay "live" rather than referencing dated publications--so changes are expected. For publications taken offline, is there an expectation that they take updates?

**Comment by jmulliken** [comment]
> The manifest-based approach could make sense for very static content, but it seems the web publications also want to make use of the dynamic nature of the web. How does that work? If I take a web publication offline, can it be updated? Do I need to re-download the whole thing again? How does versioning work? <

Although WP do use dynamic features, there's still an idea that what refers to or contains the dynamic content is published or fixed. There may be dynamic resources in a WP, but the text and structure surrounding those resources is as fixed as any typical (edition of a) publication. nevertheless, we need to consider how the UA will handle those resources.

> HTML documents (which are viewed as resources listed in the infoset) may include other resources not listed in the infoset--Are these things not considered part of the publication? What is to be done about them when using the manifest to take the publication offline? 
 Is there a way to automate a kind of placeholder denoting "external content?"

> Is an offline WP a PWP? Or is that a separate concept? <
Separate, right? PWP implies more publisher-defined parameters, some of which might take on these other challenges, yes?

> Who is responsible for taking the WP offline? The book author or the browser? Or both? <
I think our work here assumes it's the browser.

> The spec seems expressly interested in having the web publication stay "live" rather than referencing dated publications--so changes are expected. For publications taken offline, is there an expectation that they take updates? <

Content isn't necessarily expected to change in a WP. But if code does, would a new offline version change the user's experience?

**Comment by WSchindler** [comment]
A PWP is a packaged format while **offlining** a WP is IMO not the same as packaging a WP and downloading it afterwards. Thus an offlined WP and a PWP are not the same thing.

**"External content"** - let's say a quote from Wikipedia or some scholarly article or a reference to an external data set from a third party - could not be controlled by a publisher or author so that there is always the risk that you might not dereference its URL at a future point in time. You could thus not see this content as a fully integral part if it's more than simple text embedded in your narrative. When offlining a WP, we should thus have a way to describe a chunk of content as "external" and a placeholder (based on an attribute?) that would signal why this part would not be accessible when you are offline.

**Comment by HadrienGardeur** [comment]
I've already made [a similar comment](https://github.com/w3c/dpub-pwp-ucr/issues/161#issuecomment-383930725) to what @iherman said elsewhere:

> IMO, we shouldn't talk about offlining at all. Instead, we should strictly talk about:
>
> - packaging
> - or caching
>
> Packaging is meant to store a complete and stable version of a WP, while caching is meant to provide access to the resources of the publication if the connection is flaky, slow or you need to go offline for a limited period of time.

**Comment by iherman** [comment]
@HadrienGardeur "caching" has some sort of a loaded meaning to Web Caching, hence my reluctance of using the term. But I have the impression that we agree on the concept level...

**Comment by HadrienGardeur** [comment]
Well, it's exactly Web caching, so I'm perfectly fine with that.

The only difference is that we might have code that trigger GET requests for resources in the background (to cache them) + code that intercepts network requests (for example, a Service Worker).
But that's pretty normal Web behaviour, that's exactly how Web Apps are relying on SWs as well.

**Comment by WSchindler** [comment]
Could it be feasible that you would download the resources from a WP - including the manifest - to a permanent storage (e.g. a specific directory on your local hard disk or file server)  and a WP-aware RS would then be able to interpret the contents of this directory (and its subdirectories) as a WP without prior packaging?

**Comment by HadrienGardeur** [comment]
> Could it be feasible that you would download the resources from a WP - including the manifest - to a permanent storage (e.g. a specific directory on your local hard disk or file server) and a WP-aware RS would then be able to interpret the contents of this directory (and its subdirectories) as a WP without prior packaging?

There's no such thing as permanent storage on the Web today.
But you seem to be describing a PWP based on Web Packaging.

**Comment by jmulliken** [comment]
The Affordances task force call yesterday included a call-to-arms to use the [template](https://github.com/w3c/wpub/issues/143#issuecomment-374888961) developed in issue 143 to draft tentative descriptions for each affordance. Here's my stab at offlining. I fully expect much feedback and consternation. I would just ask that we use the template to try to build on this somehow. So if you'd suggest modification, please just go ahead and modify, add, subtract, etc. in addition to advocating your pov.

Offlining

1. Short Description: A WP should afford the capability to be taken offline. In the event that network connection is not available, for example, the user should be able to continue reading, navigating, and annotating the publication. A user should also be able to store and retrieve the WP for later use in an offline browser environment. Offlining should be enabled by background processes and/or a user-activated toggle.

2. Dependency: Such affordance relies on the manifest containing a complete list of contents and local or external resources which the browser will need to make available in the event of network loss. 

3. Use case: See the following use cases from 2.1.6 Going Offline: https://www.w3.org/TR/pwp-ucr/#onloffl.

4. Examples: Current examples analogous but not synonymous with offlining include browser cache (link?) and web app service workers (link?). Caching would need to be further optimized for longer-term storage defined by the needs of WPs. Another point of reference is web-archiving, which enables a crawl of an entire domain, with the option of patching external resources, to be stored in a single WARC file that can then be displayed offline with seemingly no loss of fidelity. Rendering of WARC files is currently unsupported by a browser alone. (True?)

5. Testing: Testing offline capability entails loading a page from a WP while online and then successfully navigating to other parts of the WP while offline. Additionally or alternatively, the UA or reading system could offer a toggle between online and offline reading. In that case, testing would entail entering a WP at any point of content, switching to offline mode, and then successfully navigating through the rest of the publication.

**Comment by iherman** [comment]
Deborah will make a writeup for this affordance, based on the discussion on 2018-05-31

**Comment by wareid** [comment]
Affordances addressed in the UCR document, as mentioned in the meeting on Feb 4 2019, I am closing this issue.
