### ISSUE TITLE
Improving infoset & WebIDL for creators

### ISSUE THREAD

**Issue by HadrienGardeur** [w3c/wpub#151]
Our current infoset is extremely vague regarding creators:

- can we have more than one creator?
- can we express roles as well (authors, translator, editor...)?
- if so, do we use separate properties and members per role in our WebIDL dictionary?
- do we expect to include identifiers (ISNI, VIAF...) as well?
- do we need to provide a sortable string for dedicated UAs?

We already know that these creators will need to be localized as well.

For reference, [RWPM](https://github.com/readium/webpub-manifest) provides the following members: `author`, `translator`, `editor`, `artist`, `illustrator`, `letterer`, `penciler`, `colorist`, `inker`, `narrator` and `contributor`.

They can be expressed as:

- a single string 

```
"author": "James Joyce"
``` 
- an array of strings

```
"artist": ["Shawn McManus", "Colleen Doran", "Bryan Talbot"]
``` 
- an object or array of objects... 

*... with a sortable string*

```
"author": {
  "name": "Marcel Proust",
  "sort_as": "Proust, Marcel"
}
```

*... and/or localized strings*

```
"author": {
  "name": {
    "ru": "Михаил Афанасьевич Булгаков",
    "en": "Mikhail Bulgakov",
    "fr": "Mikhaïl Boulgakov"
  }
}
``` 

*... and/or an identifier*

```
"author": {
  "name": "Jules Amédée Barbey d'Aurevilly",
  "sort_as": "Barbey d'Aurevilly, Jules Amédée",
  "identifier": "http://isni.org/isni/0000000121317806"
}
``` 

related #150

**Comment by HadrienGardeur** [comment]
Here's my take on these questions:

> can we have more than one creator?

Yes.

> can we express roles as well (authors, translator, editor...)?

IMO this is definitely necessary, but I wouldn't recommend following the model used in EPUB 2 (two elements + MARC relators).

> if so, do we use separate properties and members per role in our WebIDL dictionary?

I think that we need at least a few different members for the most important roles.

> do we expect to include identifiers (ISNI, VIAF...) as well?

This is an area where things have vastly improved since EPUB was initially created, I think it's worth considering.

> do we need to provide a sortable string for dedicated UAs?

This could be a separate issue as well, since we need to consider the same question at least for `title` as well.

**Comment by BillKasdorf** [comment]
I definitely think we need to accommodate identifiers. In addition to ISNI and VIAF, ORCID is very important as a disambiguator in scholarly publishing. It's a contributor (aka author) ID and it's required by a lot of journals.

**Comment by TzviyaSiegman** [comment]
I have concerns about creating something that is unique to WPUB. Our goal is to be usable on the Web. Therefore our goal should be to use things with which the Web is familiar. How does one establish authorship (and similar) on the Web today? It is usually through schema.org, which may need a review.

**Comment by HadrienGardeur** [comment]
> I have concerns about creating something that is unique to WPUB. Our goal is to be usable on the Web. Therefore our goal should be to use things with which the Web is familiar. How does one establish authorship (and similar) on the Web today? It is usually through schema.org, which may need a review.

RWPM is using schema.org as well.

For the WAM, there's absolutely nothing right now and you can't really re-use schema.org (no support for JSON-LD, no mapping to existing vocabularies either).

That said, I don't think we need to talk about serialization immediately, we can discuss infoset and WebIDL first.

**Comment by HadrienGardeur** [comment]
I'll create a new branch with the proposed WebIDL, I don't think that what we have right now is acceptable.

We need at least:

- the ability to include multiple authors
- an identifier per author

I'll defer the rest:

- sortable strings for authors
- how we support various roles

**Comment by iherman** [comment]
#161 has been merged; closing this issue

**Comment by HadrienGardeur** [comment]
This issue is not completely resolved but I can open a new one, focused on roles.
