### ISSUE TITLE
Add to reading/publication list

### ISSUE THREAD

**Issue by HadrienGardeur** [w3c/wpub#153]
In the recent additions related to the lifecycle, I introduced [a new section about a publication list](https://w3c.github.io/wpub/#aff-add-to-list) as well in affordances:

> User Agents SHOULD provide a list of publications where the User can browse, search, add and remove their publications.
>
> When a User Agent obtains a manifest for a Web Publication that's not currently listed in the list of publications, it MAY provide an affordance to add it to the list.
>
> This affordance has the following requirements:
>
> 1. it SHOULD display the title of the Web Publication
> 2. it MAY display additional metadata from the infoset

It's worth pointing out that this is already fairly consistent with the way browsers currently handle things:

- **Edge** has a reading list, closely integrated to its reader mode
- **Firefox** recently integrated Pocket as its default reading/publication list
- **Safari** has a reading list as well on both iOS and macOS
- **Chrome** has a reading list on iOS (couldn't find it elsewhere)

These reading list are usually tied to a visual icon that's closely related to books and/or reading:

- on **Firefox**, it's behind a "bookshelf" icon
- on **Safari**, it's behind a "book" icon and a "reading glasses" icon
- on **Edge**, it's behind a "stack of books" icon

In all implementations, adding a publication to this list triggers both offline support and a specific reading mode as well.

**Comment by BigBlueHat** [comment]
FWIW, Chrome uses the term "shelf" when you "install" a Web App Manifest-enabled Web App in Chrome on the desktop.

Certainly a "shelf" concept is not new to publications...and we should define the affordances for it. However, I do think keeping the needs and affordances of the "shelf" separate from the needs of the "publication" may also be necessary.

**Comment by iherman** [comment]
I remain unconvinced that the whole area of a shelf (or whatever its name is) should be our concern. I have no problem _providing_ the necessary data (like the icon, or whatever we inherit from the WAM if we go down that route), but I think that is where we should stop. In WP, we define, essentially a "format" for a single publication, and many aspects of the UA's behaviour should be left undefined by us. Much like EPUB in this respect, b.t.w.

**Comment by HadrienGardeur** [comment]
If we keep the current text (or something similar to it), I don't think that it will be problematic at all.

To rephrase what's in the draft, a UA:
- SHOULD provide a list of publications where the User can browse, search, add and remove their publications
- MAY provide an affordance to add it to the list

This affordance:
-  SHOULD display the title of the Web Publication
- MAY display additional metadata from the infoset

As I've said in a previous comment in this thread, all major browsers already provide a reading list, which is an extremely good fit for publications as well.

Some of them also provide an affordance to add a resource to that list, for instance in Firefox there's an "add to Pocket" button while using the reader mode.

The only thing we're adding (or enhancing) is related to our infoset: that the affordance should somehow hint at the publication using its title.

**Comment by BigBlueHat** [comment]
The [WAM spec's Installable web applications](https://w3c.github.io/manifest/#x2-installable-web-applications) section says the following:
> For example, on user agents that support installation, a web application could be presented and launched in a way that, to the end-user, is indistinguishable from native applications: such as appearing as a labeled icon on the home screen, launcher, or start menu.

Essentially, the WAM exists to provide installation and describe the experience of launching from a launcher without defining things outside of itself, but is (obviously) heavily informed by the needs of that launcher (i.e. provides icons, a name, etc).

Point being that we have less of a need to define what a "shelf" is or could be, and more of a need to define Web Publication requirements with an eye toward the needs of a shelf system--while also continuing to remember that there may never be a "shelf" in some user agent provided experiences.

**Comment by jmulliken** [comment]
As an affordance, can we simply use the language @HadrienGardeur suggests and then allow the WAM task force to address the "how?" Trying to identify whether we need to add a WAM label to this issue or if there's already another issue breaking down the "hows" of the reading/publication list.

**Comment by iherman** [comment]
I continue to question whether this affordance should be part of the WP specification in the first place. I do not have any problem with what @jmulliken proposes _provided we consider this as part of the WP_. However, the WP defines the features of a single publication and does not aim to specify the behaviour of any agents handling a collection of these. 

(Much like the EPUB specs, b.t.w. They do not contain any text, afaik, on what a RS should provide as shelf features...)

**Comment by iherman** [comment]
Issue to be closed by virtue of F2F discussion, including removing section 7.2

**Comment by iherman** [comment]
Removed 7.2, committing to main branch, and closing.
