### ISSUE TITLE
Default direction need to be compatible with epub 3.1

### ISSUE THREAD

**Issue by rakutenjeff** [w3c/wpub#160]
The original comment is from https://github.com/w3c/wpub/pull/142#issuecomment-368597956

> How about set default direction to "Reading System can choose default direction" which is same as idpf defined in http://www.idpf.org/epub/30/spec/epub30-publications.html#sec-spine-elem? It mightbe convenient when we need to convert from idpf to web infoset.

I believe there are still other similar items remains I am trying to filter out. But the reason I report this issue is I hope can get a consensus of compatibility between wpub and epub (Following is picked up from https://github.com/w3c/wpub/pull/142#issuecomment-369612141 about more detail of compatibility).

> my image of relationship between wpub and epub is wpub define what should be in manifest (and maybe define json serialization as well), and epub address those manifest items in packaged wp (epub) domain. So the manifest should be compatible. One of benefit is current publisher who already has millions of epubs would be easy to step into WP stage in the future.

**Comment by mattgarrish** [comment]
I modified the section while doing some editorial cleanup to include an "auto" value which allows the RS to choose. You can see the changes here: https://w3c.github.io/wpub/#wp-reading-progression

Is this sufficient to address your concern?

**Comment by rakutenjeff** [comment]
Thanks. Yes this resolved the default reading progression. I agree with closing this. I am still comparing between wpub and epub 3.1 might add more later on. Can I treat this fix as `consensus of compatibility between wpub and epub` ? I think wpub need to include all the information that epub 3.1 current has except some epub or xml specified items. I wish in the future when publisher has data (no matter which format, could be just database field) created base on wpub spec it would be possible and easy to generate epub opf from this data. Do I need to proposal this in email or during meeting? Or just create a new issue for discussion?

**Comment by iherman** [comment]
@rakutenjeff I would say: "intention for compatibility between wpub and epub". There may be corner cases.

I think it would be better to propose that during a meeting or simply create a new issue. As you prefer. (Well, we won't have a meeting next week, so an issue might be better...)

**Comment by rakutenjeff** [comment]
Thanks @iherman . Will propose it through a new issue.
