### ISSUE TITLE
Track AMP related activity and specs

### ISSUE THREAD

**Issue by BigBlueHat** [w3c/wpub#166]
AMP is the progenitor of the Web Packaging spec we are being encouraged to consider for PWP. It is also the source of several other specifications that may be of value to our work, and (consequently) we should be involved in these discussions if possible:
https://github.com/ampproject/amphtml/blob/master/contributing/web-standards-related-to-amp.md#overview-of-web-standards-and-features-related-to-amp

**Comment by iherman** [comment]
Issue moved over to the generic WG repo (see https://github.com/w3c/publ-wg/issues/26)
