### ISSUE TITLE
Handling roles for creators

### ISSUE THREAD

**Issue by HadrienGardeur** [w3c/wpub#167]
This is a follow-up to #151 and the recent #161 pull request.

Now that our WebIDL can support multiple creators and canonical identifiers for them, we need to continue discussing how roles will be handled.

I think there are essentially two different solutions:

- using a generic element with a specialized vocabulary for roles (like in EPUB 2/3 where we use `dc:creator`and `dc:contributor` + MARC relators)
- using specialized elements per role (for instance, roles extracted from schema.org)

[RWPM](https://github.com/readium/webpub-manifest) is a mix of both with the following dedicated roles that are mapped to schema.org: `author`, `translator`, `editor`, `artist`, `illustrator`, `letterer`, `penciler`, `colorist`, `inker` and `narrator`.

As a fallback option, RWPM also has a `contributor` element (also mapped to schema.org) with a `role` member that relies on MARC relators.

The exact scope of our infoset is vague, but my personal preference would be to align with schema.org and adopt at least a subset of the roles that are available.

**Comment by iherman** [comment]
I think in general aligning with schema.org is a good move. It is time publications are recognized by schema, and that their metadata end up in various knowledge graphs...

**Comment by HadrienGardeur** [comment]
This is now covered by our draft: https://w3c.github.io/wpub/#wp-creator-manifest
