### ISSUE TITLE
Minor issues on the lifecycle algorithms

### ISSUE THREAD

**Issue by iherman** [w3c/wpub#170]
I have played, yesterday and today, with a basic [Node.js implementation](https://github.com/iherman/WPManifest) of the manifest lifecycle algorithms, just to get a feel for it (and to play with some aspects of Javascript:-). While doing so, some minor issues popped up; see below.

**Comment by iherman** [comment]
The minor things I have hit:

* [ ] At some point we have to define more details on the 'conversion' of the manifest into the object described by the IDL. For example:
    - the JSON serialization may allow for relative URL-s in resources; the IDL should not. The conversion should handle that, but... which base? The manifest URL? The document URL? (I would opt for the manifest URL.)
    - is the idiom `"lnk":"http:..."` allowed in lieu of a full link object? If so, the conversion should detect that and produce the right object.
    - etc.

    Nothing major, but we will have to clarify these, infoset item per infoset item.

* [ ] What should happen if the manifest is not o.k.? Ie, what should the processing do if the manifest does not abide to the requirements in terms of content and syntax? (B.t.w., it may be useful to have a JSON Schema defined for the manifest when the time comes.)


As for the reading order algorithm:

* [ ] Not clearly defined what "algorithm termination" means. I suggest, for symmetry, that this means returning an empty reading order Array
* [ ] after step 2/3: if navigation document link is null, the algorithm terminates
* [ ] In step 10: if the document contains several 'nav' elements, only the first one is considered (in document order).
* [ ] Should there be a separate `@role` set for the navigation element, actually?
* [ ] In 10.3 the base for the relative path is the URL of the navigation document URL; that must be specified

(@HadrienGardeur, I am happy to modify the document incorporating these, if and when we have a group agreement.)

**Comment by iherman** [comment]
Also: the current reading order algorithm does say that

> Strip any fragment identifiers from the references.

I would think that the query part as well as the authentication part of a URL should also be stripped. Ie, just keep the "bare" resource reference, with the protocol, domain, and path.

**Comment by HadrienGardeur** [comment]
@iherman I'm wary about spending too much time discussing and updating the lifecycle as long as we don't have clear answers for:

- the serialization
- the `rel` value used to identify the manifest (#132 )
- what we allow for the reading order infoset (#148)

I've made multiple pull requests focused on the WebIDL because this isn't as much tied to these issues and could easily be tweaked whenever we adopt a serialization.

I would mark this issue as defer.

**Comment by iherman** [comment]
@HadrienGardeur I have no problem with that. I just wanted to get these recorded as they popped up while I was playing with Javascript+Node...

**Comment by HadrienGardeur** [comment]
@iherman Readium will be implementing something closely related to that (parsing a manifest rather than discovering it) with the OPDS 2.0 parser: https://github.com/readium/readium-opds-swift/blob/master/readium-opds/OPDS2Parser.swift
