### ISSUE TITLE
infoset feedback

### ISSUE THREAD

**Issue by TzviyaSiegman** [w3c/wpub#175]
[Feedback](https://lists.w3.org/Archives/Public/public-publ-wg/2018Apr/0008.html) from Edge
3.2 Infoset requirements

- Accessibility compliance information OK but what does it really mean? How are user agents expected to use it? Can we trust what the web publication says? What’s the format? Is there free-form text?
- Address / Canonical identifier: Can we have concrete examples? If there really is need for a canonical identifier that must map to a URL, it should just be a URL.
- How does versioning work?
- Privacy policies: Why a web publication would need a privacy policy and not a regular web page (web sites usually have privacy policies, not individual pages)? What if I copy a web publication, do I copy the privacy policy with it?
- Either the title should be required or we should specify a “bad” fallback to the URL. We should avoid giving user agents flexibility to create a good experience out of bad data, as it then encourages tool authors to allow bad data to be created that may not work across different user-agents.

**Comment by laudrain** [comment]
Thanks @TzviyaSiegman 

I have sliced this inforset feedback in smaller issues: #178, #179, #180, #181, #182.
I propose to close this one.

**Comment by TzviyaSiegman** [comment]
Good idea. Thank you
