### ISSUE TITLE
Infoset feedback: title

### ISSUE THREAD

**Issue by laudrain** [w3c/wpub#182]
From [Feedback](https://lists.w3.org/Archives/Public/public-publ-wg/2018Apr/0008.html) from Edge

In **3.2 Infoset requirements**

Either the title should be required or we should specify a “bad” fallback to the URL. We should avoid giving user agents flexibility to create a good experience out of bad data, as it then encourages tool authors to allow bad data to be created that may not work across different user-agents.

**Comment by laudrain** [comment]
In WP spec, a title in the infoset isn't mandatory. 
Best is to have a non empty title in the Infoset.
But point **3.3.11 Title** gives the User Agent directions on how to build a title when the author doesn't give any. The URL of the manifest may be used by the UA as a "bad" fallback...

**Comment by iherman** [comment]
Isn't this issue now ready to be closed? See http://localhost:8001/LocalData/github/wpub/#title

Cc: @laudrain @TzviyaSiegman

**Comment by laudrain** [comment]
As we had no comment from Edge team, I think so.

**Comment by TzviyaSiegman** [comment]
I would prefer to explicitly ask @BCWalters to confirm that this works for Edge team.

**Comment by BCWalters** [comment]
This looks fine given the new language and organization of the spec.

**Comment by iherman** [comment]
Thanks @BCWalters. Closing...
