### ISSUE TITLE
Resources SHOULD or MAY provide a link to the manifest

### ISSUE THREAD

**Issue by deborahgu** [w3c/wpub#191]
Per the discussion in #189, we need to fix the language in 

> Resources SHOULD provide a link to the manifest of the Web Publication to which they belong to enable discovery

Either it needs to be a MAY, or, per @TzviyaSiegman's [comment about terminology](https://github.com/w3c/wpub/issues/189#issuecomment-387501106) , we need to make it very clear what are the exceptions to the cases where resources link to the manifest.

**Comment by deborahgu** [comment]
Two options I propose:

1. Change to MAY.  This is my preference.
1. Keep as SHOULD, and add a list of exceptions.

The list of exceptions will vary based on #189's resolution. However, at a minimum, the exceptions would include:

* If the the resource and the WP are controlled by different authors.
* If the resource creator doesn't want WP discovery to be automatic from the resource.

Alternately, the language should more explicitly express the appropriate conditions for including a link to the manifest, [as I said in that ticket](https://github.com/w3c/wpub/issues/189#issuecomment-387463604).

```
if:
    a resource is a component of a canonical parent
and if: 
   the owner of the resource wants readers of the resource to know about the canonical parent
then:
    the resource should link back to the manifest
```

**Comment by llemeurfr** [comment]
+1 for MAY. One should be able to generate WP html resources without knowing the URL of the (future) manifest. Not even knowing that the resource will be part of a WP. And non html resources will not handle such links anyway.
We can consider such link to the manifest as a cherry on the cake for web discovery, but even that may be erroneous as search bots will look for manifests on the web, not resources. 

Laurent

**Comment by mattgarrish** [comment]
A "may" sounds right. It's more important for various reasons what the manifest lists as belonging to the publication than what claims to belong to the publication via a manifest link, since the author has no control over what might claim to be a part of any given publication (a security issue we'll eventually have to tackle, along with the prose in https://w3c.github.io/wpub/#h-ednote-2).

**Comment by iherman** [comment]
@mattgarrish will you make this change?

**Comment by mattgarrish** [comment]
Yes, almost caught back up after a lazy week off. :) Will get to this today.

**Comment by GarthConboy** [comment]
Though without this link back to the manifest, there is no way for a WP-aware RS/UA to correctly enter a publication (know it's one and know its bounds) when entering at an arbitrary resource of the WP.  I'd think we should be clear about this downside of not providing such a link back.

**Comment by iherman** [comment]
What would be that link if the manifest is embedded in the primary landing page?

**Comment by GarthConboy** [comment]
Good question -- just a URI to the entry page?  An RS/UA could suss that out by type?

**Comment by mattgarrish** [comment]
> What would be that link if the manifest is embedded in the primary landing page?

Not sure I follow. We say:

> When a manifest is embedded within an HTML document, the link MUST include a fragment identifier that references the script element that contains the manifest (see 3.3 Embedding a Manifest).

**Comment by mattgarrish** [comment]
The primary entry page is also the exception because it MUST either have a link or embed the manifest, not that it MUST always have a link. I was trying to avoid rewriting that in two spots, but maybe there's an additional qualifier that will help.

**Comment by mattgarrish** [comment]
Although I'd question why the primary entry page can't both embed the manifest and link to it, now that I look at that section again (i.e., is it really an _either_ or can it also be a both?).

**Comment by iherman** [comment]
@mattgarrish 

Several comments...

- The question is whether, if the manifest is embedded in resource `A` (the primary page), what would we expect to appear in the link to the manifest in resource `B`. We can
    - require to use a fragment identifier (ie, something like `A#manifestID`), or
    - require to use `A`, and the UA should figure out (via the HTTP response, for example) that the return value is an HTML, in which case one more step will be necessary.

    I am not sure which of the two solutions I would prefer, to be honest
- On your other question: I must admit my thought always was that even if the manifest is embedded in the primary entry page, that page MUST nevertheless include a link, pointing at the embedded manifest via a fragment ID. I think this is better because it provides a cleaner processing, but I see now that the text in the draft is not really clear about this...

**Comment by mattgarrish** [comment]
> * The question is whether, if the manifest is embedded in resource `A` (the primary page), what would we expect to appear in the link to the manifest in resource `B`.

But didn't we already answer this with the quoted text I provided above? If the manifest is embedded, the link MUST include a fragment identifier that references the script element. Or are you suggesting that we should consider loosening that restriction?

> my thought always was that even if the manifest is embedded in the primary entry page, that page MUST nevertheless include a link, pointing at the embedded manifest via a fragment ID

That's what I'd prefer. I think we may have lost this requirement when we created the primary entry page section and made it the required location for an embedded manifest, as linking was previously required in all cases.

**Comment by HadrienGardeur** [comment]
> On your other question: I must admit my thought always was that even if the manifest is embedded in the primary entry page, that page MUST nevertheless include a link, pointing at the embedded manifest via a fragment ID. I think this is better because it provides a cleaner processing, but I see now that the text in the draft is not really clear about this...

+1 on that suggestion

Since we don't have our own media type, the only way to detect that the entry page contains an embedded manifest for a WP would otherwise be to sniff the context documents listed.

I don't think that's a good option, I'd much rather require the presence of a link with the proper rel value, pointing to the right fragment identifier.

**Comment by iherman** [comment]
> But didn't we already answer this with the quoted text I provided above? If the manifest is embedded, the link MUST include a fragment identifier that references the script element. Or are you suggesting that we should consider loosening that restriction?

No, I am certainly not suggesting anything else; but the context of that text is (for me, I may be wrong) _within_ the primary entry page, and we are talking about other resources linking to the manifest via a fragment ID. I am fine with that mechanism, just have to make it clear in the draft.

I have the impression that we are violently agreeing:-)

**Comment by mattgarrish** [comment]
> but the context of that text is (for me, I may be wrong) _within_ the primary entry page

Hm, I wasn't getting that out of it. The "Linking to a manifest" section defines how _any_ resource links to the manifest, so applies to all manifest links (and that's where the fragment identifier requirement comes from). The only difference with the primary entry page is that it must have one of the two links, whereas the others are now optional.

I'll post a PR for review with a change to make the link required on the entry page again. Maybe that will help.

**Comment by iherman** [comment]
Closing issue by virtue of #340 being merged.
