### ISSUE TITLE
Must the manifest be listed in the resource list?

### ISSUE THREAD

**Issue by dauwhe** [w3c/wpub#192]
Our [spec says](https://w3c.github.io/wpub/#wp-resource-list), 

> The resource list enumerates all resources that are used in the processing and rendering of a Web Publication (i.e., that are within its bounds). This list is the definitive source that user agents have in determining which referenced resources belong to the Web Publication and which are external to it.

Do we need to list the manifest in the resource list in the manifest? Do we need to list all manifests that might appear in publication resources which might also be part of other publications?

**Comment by HadrienGardeur** [comment]
> Do we need to list the manifest in the resource list in the manifest?

I don't think so, but I still believe that the manifest should contain a canonical URL somehow.

> Do we need to list all manifests that might appear in publication resources which might also be part of other publications?

No, since they're not part of the publication. The resources of the publication will contain links to all sorts of resources that won't be listed either, this is not limited to manifests for other publications.

**Comment by iherman** [comment]
@dauwhe, this may be relevant to the implementation scenarios. The list of resources, as an abstract (infoset) item may be relevant in taking the publication offline and/or packaging it. In this respect, a manifest file, as an embodiment of the abstract infoset, may have to be listed, too, because one may want that to be part of the package.

It may be a bit redundant. But my vote would be to answer 'yes' to your question.

**Comment by mattgarrish** [comment]
> It may be a bit redundant.

It seems completely redundant as far as WPs are concerned. You don't have a WP/infoset without the manifest, so the user agent is always fully aware of the document and the address it obtained it from.

I would leave this to user agents to determine what to do with (store manifest or just the infoset data), unless there's some specific scenario involving PWPUBs that necessitates the manifest as a resource.

**Comment by HadrienGardeur** [comment]
> I would leave this to user agents to determine what to do with (store manifest or just the infoset data), unless there's some specific scenario involving PWPUBs that necessitates the manifest as a resource.

For a PWP, we absolutely need to store the manifest in a package.

That said, I don't think that the list of resource is the only way that we'll handle what's meant to be packaged. If we want to avoid duplication, a "PWP packager" will need to download resources listed in the reading order as well as those listed in the list of resources.
I don't think it's unreasonable to also say that the manifest should be downloaded and packaged as well.

> You don't have a WP/infoset without the manifest, so the user agent is always fully aware of the document and the address it obtained it from.

That's the part where I somehow disagree.

If we adopt Web Packaging, then the URL will be part of the packaging as well. But if we adopt another format (let's say ZIP, to enable compatibility with EPUB 3.x) we might not have this URL available at all times.

We could always fetch the entry page document and retrieve the URL for the manifest from it, but it might be easier to simply include a canonical location in the manifest itself (in Atom, feeds have a `link` element with `rel=self` for that specific use case).

**Comment by mattgarrish** [comment]
> For a PWP, we absolutely need to store the manifest in a package.

Yes, I only meant that I don't think it's imperative that it be considered a publication resource in the sense that it needs to be listed in the resource list. I agree with you that there are probably other, better, ways to achieve this.

I'm also curious how the manifest is listed in the resource list when it is embedded in, or serialized as, HTML? What identifies that a second entry is a manifest, as the media type of the parent resource would seem to need to be listed, and can a resource list even refer to fragments of documents?

**Comment by TzviyaSiegman** [comment]
> I would leave this to user agents to determine what to do with (store manifest or just the infoset data), unless there's some specific scenario involving PWPUBs that necessitates the manifest as a resource.

Perhaps this is an item to be flagged as differing in WP and PWP?

**Comment by HadrienGardeur** [comment]
> What identifies that a second entry is a manifest, as the media type of the parent resource would seem to need to be listed, and can a resource list even refer to fragments of documents?

It would be very weird for a list of resources to reference a specific fragment instead of a full resource.

Fragments should be strictly restricted to navigation use cases (TOC, landmarks, list of illustrations/audio/video or guided navigation).

**Comment by iherman** [comment]
I would propose:

- on the infoset level the manifest file is indeed part of the 'resource list' by default
- we already decided at the F2F that the resource list is not exhaustive by itself (eg, it does not include the resource listed in the default reading order); in sync with this we could say that the manifest itself does not have to (though may) include the manifest itself

Note, b.t.w., that the manifest is not necessarily a 'file', it may be a data block in an HTML file...

**Comment by iherman** [comment]
@dauwhe do you think this can be closed?

**Comment by dauwhe** [comment]
This is fun, as our spec allows so many alternatives that the manifest could be embedded in an HTML file that is *not* part of the publication. But I think we should say that the manifest is identified entirely by the mandatory reference from the publication address. Making it possible to reference the manifest from the resource list would then require us to decide what happens when the two links are different. 

I do think there should be language in the spec about this.

**Comment by iherman** [comment]
I agree that this should be mentioned in the spec.

@mattgarrish ?

**Comment by iherman** [comment]
Note the comment of @wareid :

>I should add I think publishers will really self-define the bounds of their documents (they're used to it), we should just specify that if they do not include something in the infoset, they should know that they are defining it as unnecessary to the core document.

In many respect, that same applies here: authors would be well advised to add the manifest file in the resources, but it is not required...

**Comment by TzviyaSiegman** [comment]
This is solved by [List of Resources](https://w3c.github.io/wpub/#wp-resource-list) and [Extra Resources](https://w3c.github.io/wpub/#wp-extra-resources).

**Comment by dauwhe** [comment]
Reading the current spec, I still have no idea as to how this issue was resolved. It appears I can list the manifest as a publication in the resource list or the list of extra resources, but this is optional. There appears to be no way to identify such a resource as **the** manifest (which is a feature, I think). Do we want to be this ambiguous about such a fundamental question? 

Much as I worry about using EPUB as a model, at least we make this issue [clear](http://w3c.github.io/publ-epub-revision/epub32/spec/epub-packages.html#sec-item-elem):

> Note that the manifest is not self-referencing: it MUST NOT include an item element that refers to the Package Document itself.

**Comment by GarthConboy** [comment]
I'd propose:  Manifest is referenced by the the Empty Page, or included in the Entry Page.  Seems the manifest may be self-referential, as the Entry Page may be in the default reading order.  And, it seems as when the manifest is not in the Entry Page, it would be fine for it to be in the extraResources (perhaps must or should be).

**Comment by iherman** [comment]
@dauwhe although not explicitly called out in the text (and it may have to be), we do have a `rel` value for the manifest which is `publication`. (see https://w3c.github.io/wpub/#wp-linking). This means that it is possible to add a manifest to the list of resources with a rel value.

Caveat: this does not say that this is _the_ manifest, ie, the manifest of the WP we are talking about; it is possible to simply include another manifest. I am not sure whether this is a feature or a bug.

However, beyond the possibility to add a reference to a manifest to the list of resources (internal or external) I am not sure I understand what processing dangers it has if it is there or not, ie, what the consequences of this are...

**Comment by TzviyaSiegman** [comment]
@iherman Regarding `rel=publication`, there is also a note there

> "The exact value of rel is still to be agreed upon and should be registered by IANA."

I have a lot of trouble delegating a new value for the entire WP that UAs will not likely recognize.

**Comment by iherman** [comment]
@TzviyaSiegman I am not sure I understand...

**Comment by dauwhe** [comment]
> I'd propose: Manifest is referenced by the the Entry Page, or included in the Entry Page. Seems the manifest may be self-referential, as the Entry Page may be in the default reading order. And, it seems as when the manifest is not in the Entry Page, it would be fine for it to be in the extraResources (perhaps must or should be).

1. I'm not worried about the case of manifests embedded in the entry page

2. I think we should be clear and unambiguous about the case of an external manifest. The identity and location of the manifest is strictly determined by the required link from the entry page. I think we should say that **this** is the single source of truth for the identity and location of the manifest. It must not be listed as a resource. Scripts or WP-aware user agents just need to know this.

**Comment by GarthConboy** [comment]
I'm okay with Dave's above.  I guess I like a rule, either must or must not (be included in the external case), is fine.

**Comment by BigBlueHat** [comment]
I'd also add that any child resources should reference the publication address and *not* the manifest (if it's external). Such that a `rel="publication"` value would be used to state that a child resource has a parent/publication resource. The UA would then consult the parent/publication resource (i.e. the Entry Page) for it's "manifest." This is especially important as some of our structural properties are expressible there.

**Comment by llemeurfr** [comment]
@BigBlueHat does it mean that some "child" HTML documents will have a link (rel=publication) to a "parent" HTML document, and the entry page (an HTML document) will have a link (rel=publication) to the manifest? If so it seems really confusing.
