### ISSUE TITLE
Which manifest applies?

### ISSUE THREAD

**Issue by dauwhe** [w3c/wpub#194]
A WP entry page must link to the publication's manifest. Other publication resources may contain a link to a manifest. 

What happens when the entry page links to manifest A, and then the user navigates to a publication resource which links to (only) manifest B? I've created a little example to illustrate the potential problem:

#### index.html

```html

<link rel="publication" href="manifestA.json">

```

#### manifestA.json

```json
{
  "address": "www.example.com/publication/index.html",
  "reading-order": [
    "index.html", "foo.html", "scylla.html", "charybdis.html"
  ],
  "reading-progression": "ltr",
  "resources": [
    "index.html", "foo.html", "scylla.html", "charybdis.html"
  ]
}

```

#### foo.html

```html

<link rel="publication" href="manifestB.json">
```
#### manifestB.json

```json
{
  "address": "www.example.com/publication/",
  "reading-order": [
    "index.html", "foo.html", "charybdis.html", "scylla.html",
  ],
  "reading-progression": "ltr",
  "resources": [
    "index.html", "foo.html", "scylla.html", "charybdis.html"
  ]
}

```

#### Question:

The user navigates from `index.html` to the next resource in the publication, `foo.html `.

But if the user again navigates to the next resource in the publication, do they end up at `scylla.html` (according to the original `manifestA.json` on the entry page) or at `charybdis.html ` (according to `manifestB.json` of `foo.html`, the current page)?

As far as I can tell, everything here is consistent with the current spec. Is this an authoring error? How would you tell?

**Comment by GarthConboy** [comment]
Hmmm... Admittedly with not enough thought, I'd say, if the publication was "entered" at `index.html` the resource after `foo.html` would be `scylla.html`, but if the publication was entered at `foo.html` the next resource would be `charybdis.html`.  It seems a UA/RS should process the first manifest it sees and call it a day.  It does not seem reasonable to have a requirement that a UA/RS goes to a manifest then looks for the first item in the reading order there and then looks to see if that resource has a different manifest.

**Comment by mattgarrish** [comment]
The persistence question always worries me, especially when resources could be scattered across different domains. This would fall into the publication mode or "state" that has to be created and maintained, but it always strikes me as quite complex compared to the web as it exists and functions today.

**Comment by HadrienGardeur** [comment]
Persistence in a WP enabled UA shouldn't be too difficult.

You would store:

- the URI of the manifest
- and the URI and reading progression of the current ressource

Once you've invoked the reader mode, I would expect a minimum level of statefulness, otherwise you would lose the context of the publication whenever you reach a resource of the publication that does not link back to the manifest.

**Comment by mattgarrish** [comment]
My concern is that we're creating a state in what is generally a stateless medium. How does having publication state impact on browsing history? How is the state returned to when backing up after leaving? Does the browser remember the publication the user was in, or does it discover that second manifest and initiate the other publication? Those sorts of nuances.

**Comment by HadrienGardeur** [comment]
@GarthConboy you're completely right that it would be the responsability of the UA to handle the state, but since the Web is meant to be stateless, I agree with @mattgarrish that this raises a number of questions outside the context of a specific (reader/publication) mode.

To be entirely stateless, we would have to:

- always reference the same manifest (`<link rel="publication">`) or the next resource (`<link rel="next">`)
- avoid the kind of situation that @dauwhe hinted that
- disallow resources from belonging to multiple publications

That's a very high price to pay, which is why I don't think that we can build an entirely stateless solution for publications on the Web with our current infoset.

**Comment by rakutenjeff** [comment]
IMHO I think once UA entered reading mode it does not need to care about the redundant manifest coming in each resource (xhtml).

How about we only trust manifest of `Entry Point`, thus, only "store" the manifest of `Entry Point` at the time UA's reading mode is triggered. Then it will ignore all following xhtml resources with a manifest.
In @dauwhe 's case, if user opened `www.example.com/publication/` or `www.example.com/publication/index.html` then manifestA.json would be loaded as manifest (then when user turn page to foo.html manifestB.json would not be treated as manifest). However if in any case user opened `www.example.com/publication/foo.html`, manifestB.json would be loaded as manifest cross whole web publication?

I also think either UA(reading mode) or RS would need a state to navigating user or display some metadata of this book.

**Comment by iherman** [comment]
Does the current (2018-07-25) draft give a clear enough answer via the primary entry page for a publication?

If so, propose closing...

**Comment by TzviyaSiegman** [comment]
@dauwhe are you OK with closing this issue?

**Comment by dauwhe** [comment]
> Does the current (2018-07-25) draft give a clear enough answer via the primary entry page for a publication?

I don't think it does. 

We don't have a lifecycle step for discarding a manifest. How does one leave a web publication? How does one deep-link between web publications? Presumably a link from a web publication to the entry page of a second web publication would apply the new manifest and discard the old manifest. Does it create a new browsing context? 

Would the situation be different if the entry page was also in the reading order of the first publication? Would the situation be different if the entry page was also in the resource list of the first publication? 

What happens if you link to something in the reading order of a new publication, but that page does not have a manifest link? If that page is not a resource of the original publication, I presume it opens as a regular web page, and no one knows that it's part of a web publication. Are we clear enough about that in the spec?

**Comment by wareid** [comment]
As discussed on Feb 4 2019, closing this issue, recent changes to the spec I believe resolve or at least change the circumstances enough to warrant a new issue if needed.
