### ISSUE TITLE
Which infoset items MAY/SHOULD/MUST be expressed in JSON vs HTML?

### ISSUE THREAD

**Issue by BigBlueHat** [w3c/wpub#197]
The infoset currently expresses two types of properties:
 - [Descriptive Properties](https://w3c.github.io/wpub/#infoset-meta) (aka metadata)
 - [Structural Properties](https://w3c.github.io/wpub/#infoset-structure)

The current specification draft combines the expression of both Descriptive and Structural properties into a [single "manifest"](https://w3c.github.io/wpub/#manifest) serialized as JSON.

Given the discussion and exploration in #193, this issue aims to discuss each property and consider if it might alternatively be expressed in HTML.

The new [experiments](https://github.com/w3c/wpub/tree/master/experiments) folder in this repo explores a few options of both singular JSON manifests (either ["inline"](https://github.com/w3c/wpub/tree/master/experiments/manifest_script) or ["separate"](https://github.com/w3c/wpub/tree/master/experiments/separate_manifest)) as well as an option which expresses [the Structural properties in HTML](https://github.com/w3c/wpub/tree/master/experiments/html-schema-org-json-ld).

For simplicity of discussion the property groups are below:
> -   [Descriptive Properties](https://w3c.github.io/wpub/#infoset-meta)
>     1.  [3.3.1 Accessibility](https://w3c.github.io/wpub/#wp-a11y)
>     2.  [3.3.2 Address](https://w3c.github.io/wpub/#wp-address)
>     3.  [3.3.3 Canonical Identifier](https://w3c.github.io/wpub/#wp-canonical-identifier)
>     4.  [3.3.4 Cover](https://w3c.github.io/wpub/#wp-cover)
>     5.  [3.3.5 Creators](https://w3c.github.io/wpub/#wp-creators)
>     6.  [3.3.6 Language and Base Direction](https://w3c.github.io/wpub/#wp-language-and-dir)
>     7.  [3.3.7 Last Modification Date](https://w3c.github.io/wpub/#wp-mod-date)
>     8.  [3.3.8 Publication Date](https://w3c.github.io/wpub/#wp-pub-date)
>     9.  [3.3.9 Privacy Policy](https://w3c.github.io/wpub/#wp-privacy)
>     10.  [3.3.10 Reading Progression Direction](https://w3c.github.io/wpub/#wp-reading-progression)
>     11.  [3.3.11 Title](https://w3c.github.io/wpub/#wp-title)
> -   [3.4 Structural Properties](https://w3c.github.io/wpub/#infoset-structure)
>     1.  [3.4.1 Default Reading Order](https://w3c.github.io/wpub/#wp-default-reading-order)
>     2.  [3.4.2 Resource List](https://w3c.github.io/wpub/#wp-resource-list)
>     3.  [3.4.3 Table of Contents](https://w3c.github.io/wpub/#wp-table-of-contents)

**Comment by deborahgu** [comment]
I'm not convinced this ticket is a good task for us to undertake. I understand the debate in #193, and I don't mean to rehash it here.  But I also maintain that putting both structural and descriptive metadata in a single location eases authorship, the creation of authoring tools, and debugging, and I would want there to be a _substantial_ technical benefit to separating them.

**Comment by HadrienGardeur** [comment]
@deborahgu I think this is mostly about finding a balance between redundancy vs having everything in the same place.

If we want to have everything in the same place, this will most likely involve *some* redundancy (hopefully as minimal as possible).

My take on this matter is that we should do a much better job than EPUB 2.x/3.x at avoiding redundancy. That said, I believe that there's more value in having everything in the same place (and easily accessable from any point in the publication, not just the entry page) rather than completely avoiding redundancy.

**Comment by iherman** [comment]
My first take is that _all_ descriptive properties should be in the JSON manifest. My reasons are:

- The often cited argument holds for all of these, whereby these type of HTML elements (language, title, etc.) are semantically meant for the enclosing HTML document and not for a group of documents which is the essence of a WP.
- These are all "metadata" in the traditional sense. If we want to consider schema.org among our considerations (which I think we should), using JSON (more exactly JSON-LD) makes a lot of sense. Again as cited before, using RDFa or microdata is much more complicated for authors.

Possible problems of redundancy may become much more complex for the structural properties; those require further discussions.

**Comment by iherman** [comment]
As a point of information, I made a rough attempt to map the descriptive infoset items onto schema.org:

https://github.com/w3c/wpub/wiki/Descriptive-Infoset-Properties-vs.-Schema.org-table

**Comment by HadrienGardeur** [comment]
Here's another point of reference, in Readium-2 we've mapped our terms to both schema.org and the EPUB 3.1 terms: https://github.com/readium/webpub-manifest/tree/master/contexts/default#mapping-to-schemaorg--epub-31

**Comment by iherman** [comment]
There is a clear convergence between the two:-)

The biggest outlier, I believe, is the (text) direction, ie, the ltr and rtl stuff. I wonder whether we should not try to convince the schema.org people that this is something they ought to put in in general, ie, it is not only a matter for publishing.

**Comment by TzviyaSiegman** [comment]
We have worked on something similar at Wiley with a focus on journal articles. It is closely aligned with https://w3c.github.io/scholarly-html/. I am confident that we could propose several extensions to schema.org if there are gaps. We would need to assemble a concrete and very specific proposal.

**Comment by HadrienGardeur** [comment]
For the cover and the privacy policy, the approach in Readium-2 is a little different:

- we looked for specific terms and couldn't really find a good fit (image is too vague and some of the bib.schema.org terms are too specific to comics)
- instead of mapping those to the metadata section of the Readium Web Publication Manifest, we decided to use links instead

**Comment by HadrienGardeur** [comment]
One major reason why cover and privacy policy can work better as "links" rather than as "metadata" is because they can both be included in structural properties as well.

In the case of a cover, it makes a lot of sense to have it in the list of resources as such:
```
"resources": [
  {
    "href": "https://example.com/cover.jpg",
    "type": "image/jpeg",
    "rel": "icon"
  }
]
```

Unfortunately, there's no better fit than `icon` for this rel in the IANA link registry.

**Comment by TzviyaSiegman** [comment]
Agreed at F2F that all descriptive metadata will be JSON-LD serialization; starting up from schema.org, and adjusting from there.

**Comment by iherman** [comment]
I think with the recent reorg of the spec, this issue can be closed.

@TzviyaSiegman ?

**Comment by BigBlueHat** [comment]
@iherman the new organization introduces several new categories that make their use a bit (more) unclear. We now have 4 categories: 2 from before and 2 new ones...
* 4.3 Descriptive Properties
* 4.4 Informative Properties
* 4.5 Structural Properties
* 4.6 Resource Categorization Properties

I'm not sure what 4.4 and 4.6 add to mix and would prefer we remove them or explain (with some intro text in each of those sections) why they're different than Descriptive or Structural (sorry @mattgarrish).

**Comment by iherman** [comment]
The infoset/manifest is now considered as closed in the first round, except for technical issues. Closing this
