### ISSUE TITLE
WAM required or not

### ISSUE THREAD

**Issue by GarthConboy** [w3c/wpub#199]
Resolved on call: "Proposed resolution: Publications, as specified here, are not necessarily Progressive Web Applications. On the other hand, WAM is tightly coupled to a Progressive Web Applications, thus,, we will not require the usage of the WAM and our specification should not be dependent on it. The WP Manifest should be specified independently of the WAM. Of course, a particular WP may be rendered via a PWA, and therefore use a WAM, but that is orthogonal to this specification."

It was noted that the last sentence above is wishy-washy, likely stating the obvious, likely redundant, and, regardless, should not be included in spec language.

**Comment by iherman** [comment]
See https://www.w3.org/publishing/groups/publ-wg/Meetings/Minutes/2018/2018-05-21-pwg.html#section2-3
