### ISSUE TITLE
Info Set for privacy

### ISSUE THREAD

**Issue by rickj** [w3c/wpub#203]
https://w3c.github.io/wpub/#wp-privacy needs more clarity, and not be so general.  Most of the privacy policy collection and enforcement is upstream from the document markup, except where the markup explicitly collects data.

**Comment by TzviyaSiegman** [comment]
I question whether privacy policy belongs in the infoset at all

**Comment by iherman** [comment]
I think this is covered on the infoset level, and I do not see our spec going into more details on what a privacy report may contain. I would propose to close this issue. @TzviyaSiegman ?

**Comment by TzviyaSiegman** [comment]
@prototypo was planning to provide more info about privacy, but that can wait until next draft.

**Comment by iherman** [comment]
Ok. Closing it for now
