### ISSUE TITLE
manifest: metadata

### ISSUE THREAD

**Issue by TzviyaSiegman** [w3c/wpub#21]
Per issue https://github.com/w3c/wpub/issues/15, there is discussion about whether the minimum manifest must include any metadata. 

I am of the opinion that a small subset of metadata is either a MUST or can be implicit. See also https://github.com/w3c/wpub/issues/15#issuecomment-320723064

**Comment by lrosenthol** [comment]
On Mon, Aug 7, 2017 at 1:39 PM, Tzviya <notifications@github.com> wrote:

> Per issue #15 <https://github.com/w3c/wpub/issues/15>, there is
> discussion about whether the minimum manifest must include any metadata.
>
> I am of the opinion that a small subset of metadata is either a MUST or
> can be implicit. See also #15 (comment)
> <https://github.com/w3c/wpub/issues/15#issuecomment-320723064>
>
And I would just wonder if title (issue #20) isn't just one of those piece
of metadata...

**Comment by HadrienGardeur** [comment]
A manifest SHOULD include metadata about a WP but (aside from the on-going discussion about title) I don't think that this should be a requirement.

With regards to metadata:

- we need built-in extensibility
- we should rely as much as possible on existing vocabularies (schema.org)
- we probably want to look into JSON-LD as a good candidate for what we need

**Comment by iherman** [comment]
I think that, on an abstract level, the manifest MUST have a metadata "slot", although that slot may be empty. But users must be able to add metadata.

I agree with @HadrienGardeur on the usage of external vocabularies as much as possible, but that is a general design principle.

**Comment by HadrienGardeur** [comment]
@iherman that was one of the question that remained unanswered in yesterday's call: how do we document such design principles? 

IMO they can be as important (if not more) than the list of requirements that we're currently working on.

**Comment by iherman** [comment]
> @iherman <https://github.com/iherman> that was one of the question that remained unanswered in yesterday's call: how do we document such design principles?
> IMO they can be as important (if not more) than the list of requirements that we're currently working on.
> 
> 

I wouldn't mind setting up a separate wiki page for now on the publ-wg repo. Indeed, we had a number of  design principles listed in various comments, and collecting these might be a good idea. Wanna start? (Now that you are in the relevant github team, you can create and edit wiki pages:-)

**Comment by laudrain** [comment]
About the title, I'd like to add that if we want a WP to be accessible by spec, it is a MUST.
Or we decide that a WP conformant to the spec may not be accessible.

**Comment by iherman** [comment]
@TzviyaSiegman, isn't this issue obsolete by now? If so, we may want to close it...

**Comment by TzviyaSiegman** [comment]
This issue resolved with the publication of https://www.w3.org/TR/2018/WD-wpub-20180104
