### ISSUE TITLE
Is 'cover' a structural property?

### ISSUE THREAD

**Issue by iherman** [w3c/wpub#210]
This was [discussed and proposed at the F2F meeting in Toronto](https://www.w3.org/publishing/groups/publ-wg/Meetings/Minutes/2018/2018-05-30-pwg.html#section4-1), but no decision has been taken.

**Comment by iherman** [comment]
In my opinion: yes.

**Comment by llemeurfr** [comment]
if it wasn't we would miss an affordance, as the user agent would not be able to display the cover for presenting the book in a local bookshelf. (even if we don't spec anything about bookshelves, this seems an important feature of user agents).

**Comment by HadrienGardeur** [comment]
For the cover specifically, we could simply use:
```
{
  "@type": "http://bib.schema.org/CoverArt",
  "url": "cover.jpg",
  "fileFormat": "image/jpeg"
}
```

That said, I'd like to have an option that works consistently for all similar properties (privacy policy as pointed in #203, table of contents).
There are already existing rel values for most of them but not for a cover. We could either:

- submit a new rel value to IANA for a cover
- use the schema.org URI

```
"resources": [
  {
    "rel": "cover",
    "url": "cover.jpg",
    "fileFormat": "image/jpeg"
  },
  {
    "rel": "contents",
    "url": "/toc",
    "fileFormat": "text/html"
  },
  {
    "rel": "privacy-policy",
    "url": "/terms",
    "fileFormat": "text/html"
  }
]
```

**Comment by iherman** [comment]
Closing by virtue of #232.
