### ISSUE TITLE
"order" in the reading order in JSON-LD

### ISSUE THREAD

**Issue by iherman** [w3c/wpub#212]
Care should be taken that, in JSON-LD, a JSON 'array' does not necessarily means strict order (this is an ugly side effect of… don't ask:-). This means that we will have to be careful how to define the reading order in terms of JSON-LD.

**Comment by iherman** [comment]
This is just a placeholder issue, in fact: it is necessary to use the `@list` feature of JSON-LD when defining the relevant term (is it "spine"?) in the Web Publication Manifest context file.

**Comment by llemeurfr** [comment]
This is another incentive to create our own context, and use `"@container": "@list"`in the definition of the reading order property. This will avoid overloading the syntax of the property in each instance via `@list`. 

Ref. https://json-ld.org/spec/latest/json-ld/#sets-and-lists

**Comment by dauwhe** [comment]
So we can't do this...

```json
{
    "spine":  ["a.html", "b.html", "c.html"]
}
```

...but we have to do this...

```json
{
    "spine": {
      "@list": ["a.html", "b.html", "c.html"]
    }
}
```
unless we add a context...

```json
{
  "@context": {
    "spine": {
      "@container": "@list"
      }
    },
    "spine":  ["a.html", "b.html", "c.html"]
}
```

...even though most implementations would process structural metadata as JSON rather than JSON-LD? This sounds like complexity that doesn't serve the user. I just hope I don't have to write the blog post explaining why arrays are ordered in JSON but not JSON-LD :)

**Comment by akuckartz** [comment]
@dauwhe Well, the strange thing is that sets are always ordered in JSON. JSON-LD correctly handles (unordered) sets :-)

**Comment by HadrienGardeur** [comment]
Is there a good place to start drafting this WP context document? Directly in this repo?

Right now, I think that we need to:

- define both `resources` and `reading_order` (I'm surprised to see `spine` again, we used it in EPUB and RWPM but I thought that the term would disappear)
- indicate that `reading_order` is a list using `"@container": "@list"`
- maybe map `reading_order` to a schema.org term? (http://schema.org/hasPart)

**Comment by iherman** [comment]
I would think we could put it into the "common" folder of this repository. I will then have to put up a redirection in the /ns directory from the 'canonical' version of the context file's URL to this one. But that is not urgent, probably.

**Comment by iherman** [comment]
I believe by virtue of #215 this issue can be closed now.
