### ISSUE TITLE
Mismatch in the accessibility references in the current text and schema...

### ISSUE THREAD

**Issue by iherman** [w3c/wpub#216]
The current draft says:

> The infoset SHOULD include a link to an accessibility report when one is available for a Web Publication. It is RECOMMENDED that the report be included as a resource of the Web Publication.

which suggests that the acceessiblity report is more a structural property (i.e., linking out to a full report) rather than descriptive. This is in contrast with the discussion in Toronto where accessibility was listed as a descriptive property

Cc @avneeshsingh @GeorgeKerscher

**Comment by iherman** [comment]
My proposal would be to allow for both: recommend the usage of the accessibility terms of schema.org but, _also_ introduce a structural property for an accessibility report.

**Comment by laudrain** [comment]
Structural properties are supposed to "express key structures" (https://www.w3.org/TR/wpub/#infoset-expl).
Personally, I don't see accessibility metadata expressed in a report to be "key structures".
But more as giving global information on the accessibility state of the publication.

**Comment by iherman** [comment]
@laudrain: the properties described in schema.org (see also the relevant [wiki page](http://www.w3.org/wiki/WebSchemas/Accessibility)) may be enough then, at least in the core manifest. If so, the description of the infoset item may have to be changed...

**Comment by laudrain** [comment]
**@iherman**: you mean that "linking out to a full report" implies "structural property" ?
But it could also be "extensibility" as links to other "metadata records" are in 3.5 Extensibility.
Then the proposal could become:
- a11y properties in schema.org in **3.3 Descriptive properties**
- link to the full a11y report in **3.5 Extensibility**
What do @avneeshsingh @GeorgeKerscher think?

**Comment by iherman** [comment]
Yes, that is an alternative, too.

**Comment by GeorgeKerscher** [comment]
Hi,
 
Sorry for being so slow to respond, but DAISY meetings in Germany.
 
I believe this is descriptive in nature about the publication. However, there should be metadata about the publication that is carried in the publication. So, from that perspective, would it be a resource, but not in the reading order?
 
Best
George

**Comment by iherman** [comment]
@GeorgeKerscher this may then be another example for the separate 'list' discussed in #225. Which is perfectly fine, it only requires to define another 'rel' value to identify that this is a report, and the rest falls out painlessly...

**Comment by avneeshsingh** [comment]
The accessibility metadata is mostly for discovery. The external report provides felexibility beyond schema.org accessibility metadata. It can also have ONIX codes in it.

I think that we are discussing the list of resources and not resources in default reading order. So, does the recommendation to include accessibility report in list of resources create any major problem?

**Comment by iherman** [comment]
> I think that we are discussing the list of resources and not resources in default reading order. So, does the recommendation to include accessibility report in list of resources create any major problem?

No:-) The only reason I raised this is when mapping the infoset onto the manifest, we end up with two different things:

1. usage of the schema.org accessibility terms that you know very well
2. the possibility to add link to a separate accessibility report

And my only question was whether it is all right to have _both_. I have the impression that we are fine having both indeed...

**Comment by avneeshsingh** [comment]
Indeed.

**Comment by clapierre** [comment]
Yes we would want to have both, as ONIX currently doesn't support all of the new accessibility metadata for conformance and discovery but does allow for a link to a report which would include anything it currently does not support, so having both would be ideal.

**Comment by iherman** [comment]
Changing this to editorial, I think we have an agreement
