### ISSUE TITLE
Expressing the language of an item, say, "name"

### ISSUE THREAD

**Issue by iherman** [w3c/wpub#219]
The requirement is that it should be possible to express the language of, say, the title or name of the author individually. This does not seem to work in Schema.org...

**Comment by iherman** [comment]
In pure JSON-LD, the following idiom is acceptable and produces the right result:

```
{
  "@context":"http://schema.org",
  
  "name" : {
    "@value": "Karinthy Frigyes",
    "@language" : "hu"
  }
}
```

However, the same example is rejected by the [Google tester](https://search.google.com/structured-data/testing-tool). Indeed, `name` has the value of `Text`, ie, only a text value, and the structure above is not accepted.

Maybe discuss it with the schema.org maintainers...

**Comment by HadrienGardeur** [comment]
But from a JSON-LD perspective, what you've expressed should be just `Text` with the language set to `hu`. Is this truly a problem with schema.org rather than Google's ability to support JSON-LD correctly?

**Comment by iherman** [comment]
@HadrienGardeur: I do not know. As I said, to be discussed with them.

At the moment, I included that type of structure in #221 , but flagged it with this issue.

**Comment by HadrienGardeur** [comment]
It's also worth pointing out that with a context document, we could use `"@container": "@language"` on various terms.

Instead of:

```
"name" : {
  "@value": "Karinthy Frigyes",
  "@language" : "hu"
}
```

... you could write: 

```
"name" : {
  "hu": "Karinthy Frigyes"
}
```

**Comment by iherman** [comment]
In JSON-LD: yes. But is that acceptable in Schema.org: I do not believe so...

**Comment by HadrienGardeur** [comment]
Once again, the issue is with Google's ability to work with JSON-LD, not with schema.org terms.

**Comment by iherman** [comment]
This is now part of the draft, and schema.org is looking at this. Closing this issue.
