### ISSUE TITLE
yet another 'resource list' in the manifest?

### ISSUE THREAD

**Issue by iherman** [w3c/wpub#225]
At this moment (see also #221 ) we have two "lists" of resources in the manifest, mirroring the infoset: reading order and list of resources. (In JSON, `readingOrder` and `resources`). How exactly do we represent a cover reference and/or the privacy policies? We did agree that we represent these in the manifest as external lists (see again #221 and also #222 for initial proposals), but we did not decide yet how exactly the mapping for cover is done.

**Comment by iherman** [comment]
I see two possibilities:

1. We add cover and privacy policy to "resources', with their own media type and possible specific names (titles). I guess this is a bit like EPUB3 does.
2. We introduce a _third_ entry, something like `extraLinks`, which contains an array of those extra resources, again with media type and possible specific names.

Pros/cons

- Con 1: the resources may be typically used for packaging/offlining/caching/; the author may not want to add, say, an onerous privacy policy file to that lot
- Con 2: it may be an overkill...

I am (mildly) in favour of No. 1.

**Comment by GarthConboy** [comment]
Color me also mildly in favor of #1.

**Comment by HadrienGardeur** [comment]
I'm strongly in favour of option 2 because I think this is something useful for a good number of infoset items:

- linking to an external metadata record (#162)
- linking to a privacy policy (#163)
- linking to alternate representations (#159)
- discovering various services (such as search #149, dictionaries or annotations)

It's also worth pointing out that from a WebIDL perspective, this is something we'll need anyway (we'll extract useful links from HTML as well and place them in our WebIDL).

I think it's also worth pointing out that it's not entirely up to us to decide if it's option 1 or 2 for every publication.
IMO, some publications will consider that the privacy policy is part of the publication and simply list it under `resources`, while other publications might consider that this is an external resources (and should show up in something like `extraLinks` or `links`).
Same idea for cover as well, which could potentially show up in both.
For the metadata record and alternate representations (for instance a link to an EPUB4 equivalent), this is a slightly different story as they will always be external to the publication.

**Comment by TzviyaSiegman** [comment]
I am in favor of option 1.

**Comment by GarthConboy** [comment]
If we think of the things that this could be used for:

- Cover
- Privacy policy
- A11Y declarations
- external metadata

If we were to encode them in "resources" that implies that we want said items to be within the "bounds" of the publication (yes affordance specific).  Most of the above, in my mind, are fine to be considered within bounds, thus I remain okay with option #1.

However, if we can come up with examples of such "ancillary data" that doesn't want to be considered within "bounds," that would push me toward option #2.  Perhaps external metadata would be one of these?  Would a complete ONIX record want to be within the bounds of, say, search?

**Comment by laudrain** [comment]
**@GarthConboy** not the whole ONIX record perhaps, but a chunk of it (bibliographic metadata) that will not change in time.
IMO our spec should provide for both. I agree with **@HadrienGardeur** that the author should be able to choose "inbound" or "outbound" for those resources, depending on use cases we cannot completely foresee now.
Then I would say I am for #1 and #2...

**Comment by iherman** [comment]
@laudrain 

> Then I would say I am for #1 and #2...

No. 1 is already the case:-)

@GarthConboy 

> However, if we can come up with examples of such "ancillary data" that doesn't want to be considered within "bounds," that would push me toward option #2. 

I find two examples so far compelling:

- The full ONIX metadata which we may not want to be loaded into a cache, for example
- Links to server side search facilities and/or dictionaries

---

Going with No. 2 may have an extra attraction to @GarthConboy : we could call it `ancillaryResources`, ie, we can use his favourite term after all... 😁

**Comment by HadrienGardeur** [comment]
@GarthConboy @iherman

I would also add the following two examples:

- limiting search to relevant resources
- downloading a packaged version of a publication

If we include a privacy policy in `resources`, it will become searchable. I don't think that we want search results for this document, for a good reason: it's not always part of the publication itself.

If we adopt ZIP for EPUB4, it won't be easy to package a WP until Web Packaging is mature and widely available. Linking to a pre-packaged version of the same publication makes a lot of sense, and this is also an external resource.

With a third structural element, we would have a clear distinction between:

- resources that are part of the publication and in the reading order
- resources that are part of the publication but not in the reading order
- resources that are related to the publication but not part of it

This is a very clean approach to this problem, and it lets the author decide exactly how each resource should be treated.

Given the fact that this third group would consist entirely of external resources, I would rather use `links` or `externalResources` than `ancillaryResources` (once again, "ancillary" is incomprehensible for most of the world).

Here's a full example to illustrate things better:

```
{
  "@context": ["https://schema.org", "https://www.w3.org/ns/wpub.jsonld"],
  "url": "http://example.com/publication",
  "links": [
    {
      "url": "/policy",
      "rel": "privacy-policy",
      "fileFormat": "text/html"
    },
    {
      "url": "publication.epub4",
      "rel": "alternate",
      "fileFormat": "application/epub4+zip"
    },
    {
      "url": "/opensearch.xml",
      "rel": "search",
      "fileFormat": "application/opensearchdescription+xml"
    }
  ],
  "readingOrder": ["introduction.html", "chapter1.html", "chapter2.html"],
  "resources": [
    {
      "url": "stylesheet.css",
      "fileFormat": "text/css"
    },
    {
      "url": "cover.jpg",
      "rel": "http://schema.org/CoverArt",
      "fileFormat": "image/jpeg"
    }
  ]
}
```

**Comment by iherman** [comment]
`externalResources` sounds right to me (although `ancillaryResources` would have been fun 😁 ).

But we can leave the bikeshedding to a telco...

**Comment by iherman** [comment]
See https://github.com/w3c/wpub/issues/216#issuecomment-397813761 (and https://github.com/w3c/wpub/issues/216#issuecomment-397864854) for another example of usage.

**Comment by iherman** [comment]
Trying to close the issue: 

**Proposed 1:** introduce another entry to the manifest, termed `externalResources` as mean for structural infoset properties. The value is an array of `PublicationLink` objects. 

**Proposed 2:** define a number of URL-s for the purpose of structural properties, as used as possible `rel` values, namely, `https://www.w3.org/ns/wpub#accessibility-report`, `https://www.w3.org/ns/wpub#cover`, `https://www.w3.org/ns/wpub#privacy-policy`.

Notes:
- we may want to see whether the rel values above may be, eventually, be registered as rel values by IANA, but it is not 100% necessary
- at some point we may have to have some sort of a registry mechanism to ensure that further URL-s can be registered for `rel` values. These three are the counterpart of what is part of the minimal infoset as defined in the draft.

Cc: @TzviyaSiegman @GarthConboy @HadrienGardeur @laudrain @mattgarrish

**Comment by iherman** [comment]
> * for the accessibility report, we could probably use describedby from the IANA link registry

I am not sure about that. This is probably a very general `rel` value and this is very specific. @GeorgeKerscher what do you think?

> * we could consider using the same rel value for external metadata records as well (with a different media type)

You mean use the same mechanism for external metadata: absolutely yes, I missed that. I am not sure what you mean by "the same rel value"; is there a suitable IANA entry for this?

> * for the cover we should either consider using http://schema.org/CoverArt or registering cover at IANA

I was not sure about that one. Is it always "Art"? I heard that, in some cases, a cover may be an HTML file, I am not sure that would account for CoverArt... (though the description is "The artwork on the outer surface of a CreativeWork", which is fairly general).

That being said: I am not sure that would be semantically correct. CoverArt is, from an RDF point of view, a type. On the other hand, the values for rel are not types, are simply identifiers for "things" that may or may not have a type (beyond 'Thing'). Strictly speaking this is not the same.

> * for the privacy policy, privacy-policy is already registered at IANA

Brilliant, I missed that!

**Comment by HadrienGardeur** [comment]
> I am not sure about that. This is probably a very general rel value and this is very specific. @GeorgeKerscher what do you think?

As long as we have a very specific media type for accessibility reports, this should work fine.

If such reports are using a more generic media type (let's say `text/html` or `text/json`) then we might consider rolling out another rel. But given the importance of accessibility, this should be considered as a generic `rel` value for the Web registered at IANA.

> You mean use the same mechanism for external metadata: absolutely yes, I missed that. I am not sure what you mean by "the same rel value"; is there a suitable IANA entry for this?

I'm suggesting using `describedy` as well.

**Comment by iherman** [comment]
>> You mean use the same mechanism for external metadata: absolutely yes, I missed that. I am not sure what you mean by "the same rel value"; is there a suitable IANA entry for this?
>
> I'm suggesting using describedy as well.

I am fine with that.

**Comment by iherman** [comment]
Just for the records, the modified version of https://github.com/w3c/wpub/issues/225#issuecomment-397865367 : 

** Proposal 2bis: **

For the infoset items in the draft, the `rel` values are:

- for external metadata files (eg, ONIX data): `describedBy`
- for privacy policy: `privacy-policy`
- for accessibility report: either `describedBy` or `https://www.w3.org/ns/wpub/accessibility-report` (to be determined, possibly get `accessibility-report` registered by IANA, eventually)
- for cover page: `https://www.w3.org/ns/wpub/cover-page` (to be determined, possibly get `accessibility-report` registered by IANA, eventually)

**Comment by GeorgeKerscher** [comment]
Hi,
 
I am concerned about using describedby, because of its very different semantics that is in aria-describedby. There it a resource is referenced which Assistive Technology  uses to send a text string to a TTS engine or refreshable braille.
 
Best
George

**Comment by iherman** [comment]
@GeorgeKerscher just to be sure we are in sync: the IANA 'describedby' relationship ("rel") value is not the same as the ARIA term (it is unfortunate that there is a name clash). The IANA rel value refers to a relationship between two resources, and described in the [POWDER](https://www.w3.org/TR/powder-dr/#appD) spec by: 

> The relationship A 'describedby' B asserts that resource B provides a description of resource A. There are no constraints on the format or representation of either A or B, neither are there any further constraints on either resource.

There is no relationship to assistive technologies.

My problem was/is whether this relationship is too general to signify an accessibility report (which, itself, is in, eg, HTML, ie, the media type would not help in identifying the nature of the beast).

**Comment by llemeurfr** [comment]
@iherman, @HadrienGardeur 

a/ re. Proposed 1: I'd really prefer to keep the term "links" rather than "externalResources". A link implicitly links to something external, and short/simple names are always better.

b/ UA developers already have troubles dealing with metadata variants in JSON-LD (e.g. single/multiple authors as string/structure etc.), we shouldn't ask them to search for the cover in different places. Let's consider that the cover, if it exists, is always a resource  (i.e. inbound). 

c/ in the IANA register, describedby isn't cameCase. 

d/ using urls as rel values would be ugly. We should better define our rel values in the specification, when HTML5 or IANA does not define them. In such a case we could define easily an "a11yreport" value or equivalent if there is no consensus around "describedby".

**Comment by HadrienGardeur** [comment]
> a/ re. Proposed 1: I'd really prefer to keep the term "links" rather than "externalResources". A link implicitly links to something external, and short/simple names are always better.

I also prefer `links` over `externalResources`.

> d/ using urls as rel values would be ugly. We should better define our rel values in the specification, when HTML5 or IANA does not define them. In such a case we could define easily an "a11yreport" value or equivalent if there is no consensus around "describedby".

URLs are the most common extension mechanism for `rel` values across many different serializations. That said, we're always free to add our own registry in addition to IANA if we want to have our own terms regardless of their inclusion in the IANA link registry.

**Comment by iherman** [comment]
@llemeurfr 

> a/ re. Proposed 1: I'd really prefer to keep the term "links" rather than "externalResources". A link implicitly links to something external, and short/simple names are always better.

I won't lie down on the road on this, but I am still more in favour of "externalResources". We use the term 'resources' all over the place, and one of the main different between 'resources' (that we already have) and 'externalResources' is that, well, those are external... The term is longer but more descriptive.

> b/ UA developers already have troubles dealing with metadata variants in JSON-LD (e.g. single/multiple authors as string/structure etc.), we shouldn't ask them to search for the cover in different places. Let's consider that the cover, if it exists, is always a resource (i.e. inbound).

UA developers can handle this, the question is whether it is o.k. to _impose_ a cover to appear only in the `resources` box. We are fairly lax so far in many places, this may be a surprising restriction. UA-s will have to do similar things with most of the entries in resources vs. external resources (the same argument could be held for privacy policy or accessibility report), so it is not clear to me why we would single cover out.

> c/ in the IANA register, describedby isn't cameCase.

Correct, my mistake.

> d/ using urls as rel values would be ugly. We should better define our rel values in the specification, when HTML5 or IANA does not define them. In such a case we could define easily an "a11yreport" value or equivalent if there is no consensus around "describedby".

URL-s are ugly, but that is what we have as an extension mechanism. Actually, I do not even think that what @HadrienGardeur proposes ("we're always free to add our own registry in addition to IANA if we want to have our own terms regardless") works well if we consider JSON-LD: if we refer to IANA then the only official extension mechanism _is_ to use full URL-s. (Mixing in the JSON-LD `@vocab` mechanism for these values would lead to complications with other vocabularies.)

That said, I think we can have very good reasons to get `accessibilit-report` accepted in general for the Web. I am less sure it is that obvious for a cover page.

**Comment by jeankaplansky** [comment]
I agree with @laudrain and @iherman - indicated by +1’s to specific comments.

**Comment by HadrienGardeur** [comment]
I see that this issue has been closed: what's the plan for voting on the term (`links` vs `externalResources`)?

**Comment by iherman** [comment]
@HadrienGardeur see #237

**Comment by avneeshsingh** [comment]
An important note for value, DescribedBy. We should have a dedicated value for accessibility because the accessibility report may have information additional to that in manifest. DescribedBy can work when accessibility report have metadata that describes accessibility metadata present in manifest, but it is not always true. for example the manifest may have accessibilityfeatures and accessibilitysummary, and the accessibility report may have a conformance report or certificate that confirms that the publication conforms to level AA.
So, if we are using IANA, we should have a value specifically for accessibility.

**Comment by iherman** [comment]
@avneeshsingh the current draft uses a dedicated `rel` value, namely `accessibility-report`. At present it is in our own namespace, but we should try to formulate it in a way that IANA accepts it as a general `rel` value for the Web. TBD at some point...
