### ISSUE TITLE
"expected" schema.org values

### ISSUE THREAD

**Issue by mattgarrish** [w3c/wpub#228]
To quote from the schema.org documentation:

> Although it might be helpful for search applications if structured data markup always followed schema.org very strictly, in practice this is unrealistic. Our schemas also continue to evolve in response to feedback, discussion and new applications of the data. Where possible we amend existing definitions incrementally rather than introducing lots of new properties for similar use cases. We have consequently based schema.org on a very flexible datamodel, and take a pragmatic view of conformance.
> 
> We expect schema.org properties to be used with new types, both from schema.org and from external extensions. We also expect that often, where we expect a property value of type Person, Place, Organization or some other subClassOf Thing, we will get a text string, even if our schemas don't formally document that expectation. In the spirit of "some data is better than none", search engines will often accept this markup and do the best we can. Similarly, some types such as Role and URL can be used with all properties, and we encourage this kind of experimentation amongst data consumers.
> 
> https://schema.org/docs/datamodel.html#conformance

I see that we use very strict examples in the specification (e.g., defining authors with type=Person and a name), but in the wild you'll often find properties expressed as simple text strings as expressed above.

The current wording for the properties typically also opens the door to variations, as it does not require strict adherence ("can be" instead of "must be"):

> The value can be one or more Person or Organization.

Should we take a position on how data has to be expressed in the manifest, or are we expecting user agents to similarly be accepting of whatever is encountered? It might be useful to be explicit about whatever position we are taking.

**Comment by llemeurfr** [comment]
Let's be frank: User Agents won't make much of the properties if their value type is unknown. 

I would have dreamed about being able to apply a JSON schema to the WP manifest. The variations or cardinality of properties like `authors` and `languages` (yes, conceptually there is an 's) and some variations of precision (an author as a string or name + id) won't allow for that. 

At least, the allowed variations must be carefully spec'd. If not, few UA will do anything, many will choke when an unknown structure appears.

**Comment by mattgarrish** [comment]
Closing this as the manifest tables all have a column called required value now, so the ambiguity is removed. If additional values are needed, separate issues can be opened for them.
