### ISSUE TITLE
Proposal: Add GitHub Issue Template for Affordance issues

### ISSUE THREAD

**Issue by BigBlueHat** [w3c/wpub#233]
Here's my remix of @iherman's [original affordance template](https://github.com/w3c/wpub/issues/143#issuecomment-374888961):
https://github.com/w3c/wpub/wiki/Affordance-Template

If this revised template strikes the right notes with the @w3c/publ-wg-chairs-editors, it may be helpful to turn this into a [GitHub Issue Template](https://blog.github.com/2016-02-17-issue-and-pull-request-templates/) for easier issue filing to fix [topic:affordances issues](https://github.com/w3c/wpub/labels/topic%3Aaffordances).

Cheers!
🎩

**Comment by TzviyaSiegman** [comment]
lgtm

**Comment by iherman** [comment]
lgtm, too. But it may be too late to use the github templates, unless we close and reopen all of them:-(

**Comment by TzviyaSiegman** [comment]
@BigBlueHat maybe we'll do this next time we start a repo?

**Comment by TzviyaSiegman** [comment]
affordances are being addressed in UCR. Next time, Gadget
