### ISSUE TITLE
Use LinkRole instead of PublicationLink

### ISSUE THREAD

**Issue by iherman** [w3c/wpub#235]
(Extracting a discussion on #232 into a separate Issue.)

Schema.org has a (currently "pending") type [LinkRole](https://pending.schema.org/LinkRole) which may be a good alternative to the (publication specific) [PublicationLink](https://w3c.github.io/wpub/#publicationLink). Maybe worth considering using the schema.org type.

---

Ref: https://github.com/w3c/wpub/pull/232#pullrequestreview-129576214, https://github.com/w3c/wpub/pull/232#issuecomment-398077232, https://github.com/w3c/wpub/pull/232#issuecomment-398079325

**Comment by iherman** [comment]
Looking at the two types, the mapping of the relevant properties would be:

* `url` is identical
* `name` is identical
* `description` is identical
* `rel` would be replaced by [`linkRelationship`](https://pending.schema.org/linkRelationship) although this is also pending, just like `LinkRole`
* `fileFormat` would be the same, but it is _not_ defined on that specific type, which may be a problem. (B.t.w, there is also a pending [`encodingFormat`](https://schema.org/encodingFormat), that has the same issue.)

**Comment by iherman** [comment]
See also https://github.com/schemaorg/schemaorg/issues/1959

**Comment by HadrienGardeur** [comment]
PublicationLink is meant to be our WebIDL, it was never my intention for this to be used in our JSON-LD manifest.

**Comment by HadrienGardeur** [comment]
From a manifest perspective, it makes sense to align with whatever's available in schema.org.

I'm just concerned once again by some of the decisions made by the schema.org community when naming such terms (`linkRelationship` vs `rel`, `encodingFormat` vs `type`).
Now that we have our own context document, it's always possible to use it for mapping those terms to something easier to use as well.

**Comment by iherman** [comment]
It is both. It is the name of the JSON-LD type that is used for the values of resources & co. That is already in the current draft:-) (In the schema.org world it seems that all objects is required to have a type.)

Obviously, if we move to LinkRole, we have to update the IDL as well.

**Comment by HadrienGardeur** [comment]
> Obviously, if we move to LinkRole, we have to update the IDL as well.

We don't have to, but it makes the life of implementers much easier if we do.

There's no need to rename the dictionary in the WebIDL, but we can switch from `rel` to `linkRelationship` and from `fileFormat` to `encodingFormat` (to avoid a superseded term).

**Comment by iherman** [comment]
I am not fond of the schema.org names, but I would prefer to keep to them nevertheless and not hide them. Authors should be aware that they use schema.org, they may then use the various outreach materials that the schema.org community, for example.

(We can come back on this issue later, b.t.w., let us not worry about this now...)
