### ISSUE TITLE
accessibility report?

### ISSUE THREAD

**Issue by TzviyaSiegman** [w3c/wpub#239]
I am trying to recall where the concept of accessibility report as a piece of content comes from. As a publisher, I have never included an accessibility report in a publication. I have included accessibility information via schema.org, but that shouldn't require any special treatment.

Any accessibility report I have created has been for internal use only and would not be useful to a user. 
Would someone please clarify what the intent of accessibility report is? Does it accomplish something different from the accessibility metadata already available:
https://schema.org/accessMode
https://schema.org/accessModeSufficient
https://schema.org/accessibilityAPI
https://schema.org/accessibilityHazard
https://schema.org/accessibilitySummary
https://schema.org/accessibilityFeature
(See details at https://www.w3.org/wiki/WebSchemas/Accessibility)

**Comment by mattgarrish** [comment]
The schema.org metadata provides information about the usability of the content, but doesn't in itself tell you whether the content has been tested for conformance against any given standard, or how it fared in such an assessment.

An accessibility report could take a variety forms. In addition to what Ben mentions, there would also be the final report from the SMART tool or a WCAG 2.1 conformance report. These can be enhanced by the schema.org properties (one change in WCAG 2.1 is that it now mentions doing this), but they don't serve the same purpose.

The reason we have both is that there was an under-specified "accessibility" placeholder that could have served either purpose.

**Comment by iherman** [comment]
The accessibility report is now part of the draft. I would propose to close this issue. @TzviyaSiegman @mattgarrish

**Comment by mattgarrish** [comment]
I'm fine with closing.

**Comment by TzviyaSiegman** [comment]
i'm fine with closing
