### ISSUE TITLE
embedded manifest requires id?

### ISSUE THREAD

**Issue by mattgarrish** [w3c/wpub#245]
In order to reference the script from the manifest link, shouldn't an id attribute also be required/recommended?

Right now, the only requirement I can find is that the script element have a specific media type. The section on obtaining a manifest doesn't go into extraction and whether the user agent is expected to parse a document until it finds a script with the specified media type if the resource is HTML and no fragment has been provided in the URL.

**Comment by iherman** [comment]
+1 to have a must. Otherwise the link from the <link> element does not work...

**Comment by iherman** [comment]
Already in the draft, closing.
