### ISSUE TITLE
Flatland: An Audiobook Experiment of Many Dimensions

### ISSUE THREAD

**Issue by HadrienGardeur** [w3c/wpub#247]
As part of the audiobook TF, I've started an experiment based on our current draft for WP:

- there's [a manifest](https://w3c.github.io/wpub/experiments/audiobook/flatland.json)
- [an entry page with a basic audiobook player](https://w3c.github.io/wpub/experiments/audiobook/)
- and [a table of contents](https://w3c.github.io/wpub/experiments/audiobook/toc.html)

I'll continue to update and improve this example as the WP draft evolves and the audiobook TF adopts specific best practices.

Quick notes about the current version:

- the entry page contains a link to the manifest
- it also contains a basic player with the following features:
  -  loads the manifest dynamically
  - sets the title of the page to the title of the WP and displays a cover
  - uses an `audio` element to listen to all audio tracks sequentially in the reading order
  - saves your current position (resource + timestamp) in the audiobook using local storage
  - has controls to move to the next/previous tracks
- the idea is to provide the ability for non WP aware UAs to listen to the whole audiobook without having to manually switch between tracks
- in the table of contents, references to various parts/sections of the audiobook rely on media fragment, which works fine in modern browsers

On my TODO list:

- add support for the TOC in the basic JS player
- use track and TOC info while listening to the audiobook

Any thoughts/comments/requests on how this experimentation could be further improved?

**Comment by danielweck** [comment]
In the manifest example, can we also have a JSON representation of the TOC, to demonstrate that hypothetical audio-centric reading systems do not have to parse HTML?

**Comment by HadrienGardeur** [comment]
@danielweck that's not possible with the current WP draft.

WebIDL has support for it, but it's meant to be the result of processing the HTML `<nav>` element.

If we ported this over to the manifest, it would be very similar to the WebIDL:
```
"toc": [
  {
    "name": "Part 1 - This World",
    "url": "http://www.archive.org/download/flatland_rg_librivox/flatland_1_abbott.mp3#t=71",
    "children": [
      {
        "name": "Section 1 - Of the Nature of Flatland",
        "url": "http://www.archive.org/download/flatland_rg_librivox/flatland_1_abbott.mp3#t=80"
      },
      {
        "name": "Section 2 - Of the Climate and Houses in Flatland",
        "url": "http://www.archive.org/download/flatland_rg_librivox/flatland_1_abbott.mp3#t=415"
      },
      {
        "name": "Section 3 - Concerning the Inhabitants of Flatland",
        "url": "http://www.archive.org/download/flatland_rg_librivox/flatland_1_abbott.mp3#t=789"
      }
    ]
  }
]
```

If you'd like to consider a JSON representation of the ToC, it's probably best to open a separate issue.

**Comment by GarthConboy** [comment]
Very nice Hadrien.  Awesome to see a real world example, using our very young spec, of something that couldn't be done in EPUB, and also addresses a serious industry need.

**Comment by llemeurfr** [comment]
The question raised by @danielweck will come over and over I think. We are forcing audiobook authors to create an HTML table of content for their audiobook, as a complement of the JSON manifest that contains the necessary audiobook metadata and core structure (a manifest which will usually be crated by their authoring tool automatically). I suspect that such ToCs will be raw HTML, with no fancy layout, automatically created by the authoring tool also. The UA will display the ToC as-is (just in case there is a fancy layout). The result will be visually dull.

**Comment by GarthConboy** [comment]
I have to say I don't care too much about visible dull... it will be machine processable into the very much required metadata needed for a useful ToC in an audiobook player (way better than just "Track N" created from the various MP3 [or whatever] fragments).

**Comment by HadrienGardeur** [comment]
**Update:** I've completed the TOC, it now covers the entire audiobook.

**Comment by HadrienGardeur** [comment]
**Update:** A link from the entry page to the TOC has been added. A future revision of the JS code will also handle the ability to dynamically update that value based on the manifest.

**Comment by HadrienGardeur** [comment]
Yeah that's fine @TzviyaSiegman
