### ISSUE TITLE
reading progression - conflict in spec

### ISSUE THREAD

**Issue by TzviyaSiegman** [w3c/wpub#259]
There is a conflict in the section on reading progression direction (https://w3c.github.io/wpub/#reading-progression-direction)
section 4.4.8.1 says "The default value is auto."
section 4.4.8.2 says "If this value is not set, its default value is ltr."

@mattgarrish do you recall what we concluded?

**Comment by mattgarrish** [comment]
Don't recall a discussion, but why wouldn't "auto" be the default? That's the value that says the author didn't define anything, or has no preference, so use whatever is natural for the reader.

**Comment by iherman** [comment]
The note at the end of https://www.w3.org/TR/html52/dom.html#the-dir-attribute says 'ltr'. We should go with that...

**Comment by mattgarrish** [comment]
It also technically doesn't have a default value:

> The attribute has no invalid value default and no missing value default.

You only get to ltr through the algorithm, which we don't have an equivalent of. In fact, our statement about how to compute auto is flawed:

> direction is determined from the value of the property.

How can you determine the direction from the word "auto" or from the absence of the property altogether, so no value?

Also, "auto" should never be a value of the infoset, should it? It would only be valid in the manifest, as the infoset would have to have the computed ltr or rtl value. In which case, do we need "auto" at all, or only an algorithm to specify ltr/rtl when not set?

**Comment by mattgarrish** [comment]
Or is "auto" trying to say that you have to calculate a value every time you parse an infoset value? That would make a little more sense, but I still wonder whether it really belongs as a possibility in the infoset.

**Comment by iherman** [comment]
I am fine ditching 'auto' altogether...

**Comment by mattgarrish** [comment]
Ya, I can't wrap my head around it, as the infoset contains the computed values so the direction has to be one or the other by that stage. It's only within the manifest that it could be unspecified.

But should we consider a better algorithm for computing? Like html dir, if it is not specified, ltr is assumed. If auto is specified at the manifest level, maybe the title is inspected first for directionality?

Maybe I'll make a PR with some thoughts in this direction.
