### ISSUE TITLE
Cover infoset requirements is unclear

### ISSUE THREAD

**Issue by deborahgu** [w3c/wpub#260]
In the WP draft, [Structural Properties: Cover: Infoset Requirements](https://w3c.github.io/wpub/#cover-infoset) is unclear:

> User agents SHOULD NOT use the cover image as the sole means of selecting or accessing Web Publications. A user agent SHOULD use the Web Publication's title and creators as text alternatives for such interfaces.

**Comment by deborahgu** [comment]
Proposed text (and I'll make a PR if I'm interpreting it correctly):

>     A user agent SHOULD provide the Web Publication's title and creators, in textual form, as access points for a Web Publication. User agents SHOULD NOT rely on the cover image, with or without alternative text, as the sole means of selecting or accessing Web Publications. 

Alternately, a slightly different rule:

>     A user agent SHOULD provide the Web Publication's title and creators, in textual form, as access points for a Web Publication. User agents SHOULD NOT rely on the cover images without textual alternative as the sole means of selecting or accessing Web Publications.  If the cover images are displayed using the Web Publication's title and creators as alternative text, the cover images MAY be the sole means of selecting or accessing Web Publications.

I prefer the former but I can see the latter as a valid interpretation.

**Comment by iherman** [comment]
I prefer the first option, too, FWIW

**Comment by TzviyaSiegman** [comment]
i prefer the first option.

**Comment by laudrain** [comment]
I also prefer first option

**Comment by mattgarrish** [comment]
The first sentence is not about the cover image anymore, but about how user agents are expected to design their interfaces. It shouldn't be in the cover property, but probably belongs somewhere in the user agent features or on a section on selecting publications.

**Comment by wareid** [comment]
Since there is no infoset, this is no longer relevant. 

@francofaa @atyposh Can you check this is covered in the use case document?

**Comment by francofaa** [comment]
@wareid I don't think that there is any change required in the ucr

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/publishing/groups/publ-wg/Meetings/Minutes/2019/2019-03-18-pwg#section2-12).

- No actions or resolutions
<details><summary><i class="differentiate">View the transcript</i></summary>
Cover infoset requirements is unclear<br/>
Wendy Reid: <a href="https://github.com/w3c/wpub/issues/260">https://github.com/w3c/wpub/issues/260</a><br/>
Wendy Reid: #260: Cover infoset requirements is unclear<br/>
… No more infoset<br/>
… close<br/>
</details>
