### ISSUE TITLE
wording of the spec on different identifiers

### ISSUE THREAD

**Issue by llemeurfr** [w3c/wpub#263]
Just to be sure that I understand well (and others too), we've got:

the canonical identifier (id) = an address (URL) which is stable in time, i.e. it must not change if the WP evolves or is moved between different locations; it may be a WP address, or not;
identifier(s) (from schema.org) = any string value (may be a URL or not), which scheme is expressed via the property name (a sub-property of identifier, e.g. isbn)
the WP address = an address (URL), that cannot be used as an identifier because a WP may be duplicated at different locations. As a consequence, a WP may have several WP addresses. It references the entry page of the WP (HTML). In this entry page one finds a reference to the WP manifest or the WP manifest itself.
the address of the WP manifest = an address (URL), that exists only if the manifest is not embedded in the entry page, and that has no specific description in the spec.
Am I right?

I still feel unsure about the relationship between the canonical id and the WP address. The following snippets in bold, from 4.4.3.1, show some contradictions:

"If a Web Publication is hosted at more than one address, the canonical identifier allows a user agent to identify the shared relationship between the versions and to determine **which of the available addresses is primary**.

The canonical identifier is also intended to provide a measure of permanence above and beyond the Web Publication's address . Even if a Web Publication is permanently relocated to a new address, for example, the canonical identifier will provide **a way of locating the new location** (e.g., a DOI registry could be updated with the new URL , or a redirect could be added to the URL of the canonical identifier).

When assigned, the canonical identifier needs to be unique to one and only one Web Publication, **independent of its address(es)**."

I would prefer to keep the last sentence = canonical id and WP address(es) are independent, period.

**Comment by iherman** [comment]
@llemeurfr 

I would propose an intermediate solution. As it reads today, it is in the normative part and therefore the first two quoted sections indeed suggest some additional normative requirement on how the canonical identifier is used. Although, I believe, what is written there reflects current practice, I am not sure it is our role to _require_ all this. In this sense I share your uneasiness.

What about turning those two paragraphs into notes (which automatically mean that is not normative)? it may need some word-smithing to separate them this way, but that is a detail...

@mattgarrish what do you think?

**Comment by mattgarrish** [comment]
I don't have a problem with that, as they're basically informative paragraphs in what, as you say, is a normative section. I'll see what I can do to mod.

**Comment by mattgarrish** [comment]
After going over the section, I think my interpretation of what needs saying and where is a little different. Have a look at this reformulation and let me know if it works: https://rawgit.com/w3c/wpub/identifier-notes/index.html#canonical-identifier

**Comment by mattgarrish** [comment]
Hm, I'm getting confused the more I look at address/canonical identifier. I've made some more tweaks to both sections to make the best sense of it I can. See PR #265 for the mods, as they're across two sections now.

**Comment by HadrienGardeur** [comment]
I also find the fact that we allow both `id` and `@id` for the same thing quite confusing.

It doesn't really matter that the schema.org context maps `id` to `@id`, most of our UAs won't be truly JSON-LD aware and will require extra processing if we allow both.

**Comment by mattgarrish** [comment]
What was the reason for the mapping, was it to account for authors mistakenly writing "id" without the "@"?

**Comment by llemeurfr** [comment]
I also still find all this pretty confusing. 

@id is a JSON-LD property, the identifier of a node about which we make assertions. 
schema.org defines https://schema.org/identifier, and sub-properties (specializations) like https://schema.org/isbn.
But where does this 'id' comes from? 

More generically, my understanding is that a WP has one or more identifiers. They are all unique in the sense that they two different WPs can't have the same identifier. These identifiers can be used interchangeably, but the publisher should choose one as the value of @id, because of the JSON-LD syntax. This @id is a URI, and therefore the value must "embed" the scheme it belongs to. 
Other identifiers can be expressed as schema.org properties, and their values can be strings (e.g. "isbn":"978-23-56734-23-1". 

So, what can we call a canonical identifier here? the @id property because it is a JSON-LD required value (is it? from https://www.w3.org/TR/json-ld/#node-identifiers I think so). 
Is it a de-referencable address? it's not required, it's a SHOULD in the JSON-LD spec.

**Comment by mattgarrish** [comment]
My guess would be that 'id' is an attempt to mask some the json-ld nature of the property from people who won't understand what the '@' sign is doing at the front. It's not a schema.org property, but if you specify 'id' as plain old json it still results in @id if you parse as json-ld.

If that's the case, I don't necessarily have a problem with it, but as @HadrienGardeur says, we should have some additional rules like:
- @id/id should not be used together
- if they appear in the same manifest, they must have the same value
- user agents must use the value of @id when both are specified

**Comment by mattgarrish** [comment]
Although... wouldn't @id/id specified in the same file be invalid? If id maps to @id, then isn't it technically specifying the same property twice?

We already have @type/@context/@language in the specification, so @id alone doesn't seem in need of mapping.

**Comment by HadrienGardeur** [comment]
Yeah, I agree with @mattgarrish that it's probably best to limit our spec to `@id`.

**Comment by mattgarrish** [comment]
I've updated PR #265 to remove "id".

**Comment by iherman** [comment]
Seems a leftover that was not closed though incorporated in the draft...
