### ISSUE TITLE
encodingFormat supersedes fileFormat

### ISSUE THREAD

**Issue by HadrienGardeur** [w3c/wpub#267]
Our current draft relies on `fileFormat` for `links`, `readingOrder`, `resources` and our WebIDL.

Since https://schema.org/fileFormat is marked as `supersededBy` https://schema.org/encodingFormat and doesn't even show up in https://schema.org/CreativeWork or https://schema.org/Book anymore, we should replace all references.

**Comment by mattgarrish** [comment]
I've updated the spec to fix this, as it's clearly wrong.
