### ISSUE TITLE
Draft 2018-07-11: Minor editorial glitches

### ISSUE THREAD

**Issue by WSchindler** [w3c/wpub#269]
- 4.5.2.1
"Issue 203: Info Set for privacy
**https://w3c.github.io/wpub/#wp-privacy** needs more clarity, and not be so general. Most of the privacy policy collection and enforcement is upstream from the document markup, except where the markup explicitly collects data." --> highlighted link doesn't work properly.

- 6.3.3.2 Affordances:
"The table of content is referred to in the Web Publication Manifest (see 4.6.2.2 Manifest Expression) and is expressed using **and** HTML element; see 4.6.2 Table of Contents for further details." 
--> use "an" instead of "and"

- A4 LocalizableString dictionary:
"Some metadata in **te** infoset have strong requirements for internationalization." --> replace "te" by "the"

**Comment by iherman** [comment]
@WSchindler I took care of the 2nd and 3rd entry. The first is a verbatim copy of the issue description (done automatically be the publishing script), so it is not a matter of changing here...

Thanks!

(Closing)
