### ISSUE TITLE
Mixture of Person and Organization?

### ISSUE THREAD

**Issue by iherman** [w3c/wpub#284]
The current manifest says for, e.g., "publisher" that it is an array of Persons _or_ Organizations. It does not say whether the array should be homogeneous, ie, whether contains objects of identical types. The current manifest suggests that it is not strictly homogeneous, but it is something that may have to be decided. 

Is there a use case where the list of, say, publishers, can include some persons mixed with some organizations?

**Comment by laudrain** [comment]
In Publishers I don't think so, the list would be only Organizations: co-publishers.
But In Creator, Contributor, there may be a mix of Persons AND Organizations.

**Comment by iherman** [comment]
Thanks @laudrain.

I must admit I would prefer not to have different constraints for different categories. Ie, if, for some categories like creators, a mixed list is o.k., then I would prefer to keep it open for all categories...

**Comment by mattgarrish** [comment]
> I must admit I would prefer not to have different constraints for different categories.

This seems to come from schema.org itself, but it doesn't appear to be worth the bother of enforcing. There are always edge cases, and all excluding one class does is force you to report an organization as a person or a person as an organization.

**Comment by iherman** [comment]
@mattgarrish @laudrain 

What we say is that we leave it as it is: all these arrays might be "non-homogeneous". I am fine with that.

Although the normative text is fine, do you think it is worth putting an editorial note somewhere making this clear @mattgarrish ?

**Comment by mattgarrish** [comment]
Ya, I've been scratching my head trying to think of a clear way to say it in the tables so we don't have to note across properties:

- One or more Person and/or Organization
- One or more of: Person, Organization
- A mix of one or more Person or Organization

Preferences? Other ideas?

**Comment by laudrain** [comment]
> One  or more Person and/or Organization 

has my preference.

**Comment by mattgarrish** [comment]
> is grammatically correct... does that work for our purposes

As a normative statement, yes, but right now we have tables that define the properties and indicate their required values ("One or More Person or Organization") in a specific column. If we can find an equally short replacement for these, then the information will be apparent even on lazy reading. (And who doesn't like it when you can be lazy and still get the information you need? :)

**Comment by tcole3** [comment]
Regarding the original question, simultaneous publication can result in multiple publishers, and though very uncommon currently, recording a person as publisher used to be more common and could become more than an edge case pattern again. Also library catalog rules conflate distributor and publisher, which further increases chance of a mixed array for publisher. But I agree much more likely in creator role. 

Library catalog rules specify that when multiple publishers, they are listed in repeated instances of the same subfield regardless of whether Person or Organization - so heterogeneous list. 

However, with regard to mixed list for creators/contributors, the MARC21 format used by libraries to catalog books separates Person creators/contributors from Organization (Corporate) creators/contributors into different data fields, e.g., MARC 700 (Person) vs. 710 (Corporate). But personally, Not a distinction schema.org makes and I do not recommend this as a model pattern for Web Publication metadata.

**Comment by RachelComerford** [comment]
@mattgarrish "One or more People or Organizations" ?

**Comment by iherman** [comment]
@mattgarrish should we close this by virtue of #296? It does answer my original question...

**Comment by mattgarrish** [comment]
I'm good with closing. If we need to reconsider the content models for any of the creators, we can do that separately (I think it's a good idea to look at consistency, even if it breaks with schema.org, or means we should propose amendments).
