### ISSUE TITLE
Manifest: are we creating a JSON-LD metadata framework or a JSON structure? 

### ISSUE THREAD

**Issue by llemeurfr** [w3c/wpub#288]
In https://github.com/w3c/wpub/pull/285, @iherman touched a sensitive spot about variations in the way a manifest can be written. I quote Ivan: "... should be acceptable, too. This is a perfectly valid JSON-LD, actually accepted by schema.org processors, too; furthermore, all strings are converted into this idiom by the JSON-LD expansion algorithm that may be used along the line. We cannot invalidate that. We can recommend to use either a string or an object with a language, but we should not require the presence of language."  

Are we creating a "semantic metadata framework" in which authors can generate flexible data, given their intimate knowledge of JSON-LD? or are we creating a interchange format as a JSON structure, that authors and UA must closely follow, and that "by design" is JSON-LD compliant?

In the first case, the schema.org ontology and the JSON-LD syntax are the rules to be followed; we are in the situation left by RDF, RDF Schemas, OWL...
In the second case, we can provide stricter syntactical rules for the webpub manifest, validated by a JSON schema. We just have to guarantee that this JSON syntax is compliant with JSON-LD rules and that a manifest can be expanded in RDF triples if somebody is interested.

For instance, in the second case, we can require the presence of a language attribute if several titles are declared in a manifest. In the first case, no.

**Comment by iherman** [comment]
@llemeurfr you are right, I may have been too liberal in my reaction:-) We may have to indeed define a strict "profile" of JSON-LD and the JSON schema may be a good tool for it (with the caveat that JSON Schema, as a technology, is not yet fully stable).

**Comment by HadrienGardeur** [comment]
It's not just about JSON Schema. As a spec, it would be a huge departure from EPUB if we didn't had good definitions of how terms should be expressed.

As I pointed out in #287, there are some massive gaps right now in our draft and for some terms (all contributors) we're missing the necessary information to make sure that authors and UAs can work well together.

**Comment by iherman** [comment]
@HadrienGardeur, looking also at https://github.com/w3c/wpub/issues/287#issuecomment-409512101, I think the term "massive gaps" are a bit of an overstatement...

Yes, these issues will come up and that is exactly the reason whey the type of work you are doing is massively (sic!) important...

**Comment by HadrienGardeur** [comment]
@iherman right now the answer to @llemeurfr initial question is that we indeed have a "JSON-LD metadata framework ".

If we want a manifest that's also easily parsable/processable as pure JSON, there is a significant gap, I really don't think that's an overstatement.

**Comment by BigBlueHat** [comment]
There's some prior art here, fwiw. [ActivityStreams 2.0](https://www.w3.org/TR/activitystreams-core/#naturalLanguageValues) uses two properties: one for the default language string value and one for a [language map](https://www.w3.org/TR/json-ld/#language-maps). So...

```json
{
  "@context": "https://www.w3.org/ns/activitystreams",
  "type": "Object",
  "name": "This is the title"
}
```
...or with multiple languages...
```json
{
  "@context": "https://www.w3.org/ns/activitystreams",
  "type": "Object",
  "nameMap": {
    "en": "This is the title",
    "fr": "C'est le titre",
    "es": "Este es el título"
  }
}
```

Web Annotation took a different approach for its [Embedded Textual Body](https://www.w3.org/TR/annotation-model/#embedded-textual-body) objects by simply requiring them to be objects (in or out of an array). We did also provide a `bodyValue` property for very minimal use cases. The text in those is considered to be a `text/plain` string with an unknown language.

Regardless, there are options for handling these (and other) scenarios.

**Comment by HadrienGardeur** [comment]
I also have a strong preference for language maps over `@language` + `@value` but unfortunately they're not processed by Google properly.
Language maps can be validated using JSON Schema and avoid the problem with multiple strings for the same language.

In RWPM, we use the same property (`title`) but allow both a string or a language map for it:

_Single string_
```
"title": "Moby-Dick"
```

_Language map_
```
"title": {
  "fr": "Vingt mille lieues sous les mers",
  "en": "Twenty Thousand Leagues Under the Sea",
  "ja": "海底二万里"
}
```

**Comment by BigBlueHat** [comment]
@HadrienGardeur the JSON-LD language map + fallback to string in default language feature is rather nice. Do you have JSON Schema written for RWPM to handle those two variations?

**Comment by HadrienGardeur** [comment]
@BigBlueHat yes, I wrote a JSON Schema for RWPM that handles that part.

We would simply use the following statement for all localizable strings:
```

"anyOf": [
  {
    "type": "string"
  },
  {
    "type": "object",
    "patternProperties": {
      "^((?<grandfathered>(en-GB-oed|i-ami|i-bnn|i-default|i-enochian|i-hak|i-klingon|i-lux|i-mingo|i-navajo|i-pwn|i-tao|i-tay|i-tsu|sgn-BE-FR|sgn-BE-NL|sgn-CH-DE)|(art-lojban|cel-gaulish|no-bok|no-nyn|zh-guoyu|zh-hakka|zh-min|zh-min-nan|zh-xiang))|((?<language>([A-Za-z]{2,3}(-(?<extlang>[A-Za-z]{3}(-[A-Za-z]{3}){0,2}))?)|[A-Za-z]{4}|[A-Za-z]{5,8})(-(?<script>[A-Za-z]{4}))?(-(?<region>[A-Za-z]{2}|[0-9]{3}))?(-(?<variant>[A-Za-z0-9]{5,8}|[0-9][A-Za-z0-9]{3}))*(-(?<extension>[0-9A-WY-Za-wy-z](-[A-Za-z0-9]{2,8})+))*(-(?<privateUse>x(-[A-Za-z0-9]{1,8})+))?)|(?<privateUse>x(-[A-Za-z0-9]{1,8})+))$": { 
        "type": "string" 
      }
    },
    "additionalProperties": false,
    "minProperties": 1,
  }
]
```

Since this validates BCP 47 languages as well, there's a pretty complex regular expression in there, but the rest is very straightforward.

**Comment by iherman** [comment]
As @HadrienGardeur said, language maps are currently not recognized by schema.org processors. I hate it, but we cannot change this, so I think we should forget about this possibility.

**Comment by akuckartz** [comment]
Google can and should change that.

**Comment by iherman** [comment]
@akuckartz you are right, but the real question is: will it? Put it another way: should this community take the bet (risk?) that this would happen? I do not think so.

I have no problem keeping this alternative open for a version two of WP at some point, that would concentrate on allowing richer JSON-LD constructions "in". 

Note that the `{"@value":"...", "@language":"..."}` JSON-LD idiom is also _not_ understood today, alas!. But that is a fundamental JSON-LD construction and there are noises that at least the Google parser will understand that. But I do not think we have any indications on the language mapping, which is a convenience feature of JSON-LD.

**Comment by llemeurfr** [comment]
@iherman I agree with @akuckartz: we must not make the WP spec more complex that is should be because a validation look is far from perfect today. Google will make its JSON-LD validation tools better, especially if we alert their team about our issues with the weight of the W3C: this is exactly why the IDPF merged in the W3C by the way. Or something else will do so (why not CWI or INRIA?).

And I would hate to add in a version 2 of a standard "yes another" variant of a way to express something. This is not IMO how standards should evolve.  An other should have clear and simple guidelines, expressed in our specs and additional best practices, and he should not scratch his head about how to do things.

**Comment by iherman** [comment]
@llemeurfr unfortunately I disagree, though I will not lie down the road on this if this is how the WG decides. But I think expecting Google to change this just because we ask is not realistic. The very reason we chose schema.org was to allow metadata for publications to be searched somewhat more easily than they are today even if we knew that would mean some constraints. We should, at least, contact schema.org before we consider doing this.

---

Also: I am not sure of the proposal. Does it mean

1. Using language maps is the _only_ means to express, eg, multilingual titles?
2. Language maps is an add-on to the possibility to use `@value`+`@language`?

While, as I said, I can live with (although I don't approve) (2), I do not think we could say (1). Using the `@value`+`@language` is a fundamental JSON-LD idiom which we cannot ignore.

**Comment by llemeurfr** [comment]
@iherman ok let's contact schema.org on this issue.

I would like the we specify ONE way to express one feature. I disagree that we cannot choose   "language maps is the only means to express, , eg, multilingual titles" if we like that. If this is allowed by JSON-LD, this is our call to choose it as our syntax. 

Again, JSON-LD is to be considered as a framework, and if it offers several variants to express something, can cannot let authors scratch their head reading the JSON-LD spec; we must offer them the (unique) best solution we find.

Let's not do again what we endured with RDF/XML (with XML structures using rdf:type properties everywhere).   see also http://www.jenitennison.com/2008/02/17/rdf-and-xml-q-and-a-which-should-i-use.html

**Comment by iherman** [comment]
@TzviyaSiegman maybe we should get a phone call with @danbri again on whether and what they intend to do on the internationalization aspect, ie, multilingual text. I have not received any feedbacks lately...

**Comment by HadrienGardeur** [comment]
I wasn't aware that `@language` + `@value` were not supported by Google either. In that case, I think we should strongly consider language maps as a better approach to this problem.

> Also: I am not sure of the proposal. Does it mean
>
> 1. Using language maps is the only means to express, eg, multilingual titles?
> 2. Language maps is an add-on to the possibility to use @value+@language?
> 
> While, as I said, I can live with (although I don't approve) (2), I do not think we could say (1). Using the @value+@language is a fundamental JSON-LD idiom which we cannot ignore.

I think this is where I have a strong disagreement with you @iherman. (1) is IMO perfectly acceptable and part of our work designing a good JSON document for this manifest. 
I see JSON-LD as a toolbox from which we should pick the best tool for what we need to do, we don't need every tool in that box though.

Language maps solve a number of problems that we're facing right now:

- they're easy to validate
- we won't have the issue of multiple strings for the same language with them
- the syntax is IMO much cleaner, it becomes very explicit which language is used for each string

**Comment by iherman** [comment]
My proposal is to defer until we get more information from schema.org as for the future of their language processing. @TzviyaSiegman and @GarthConboy, on their meeting with @danbri, already signaled that this is one of our main issues, and the answer back then was (I believe) that they are looking at this issue. If we get more information then:

1. if they implement _only_ the `@value`+`@language` then this is what we use this and only this;
2. if they implement language mapping then this is what we use and only this.

Cc @danbri, do you have any more information that you can share with us?

**Comment by iherman** [comment]
@llemeurfr, the language map problem has been pushed into its own issue (#299); is it o.k. closing this issue? I believe we have an agreement on the higher level question.

**Comment by llemeurfr** [comment]
Ok for closing and discuss language maps elsewhere. 
> @llemeurfr, the language map problem has been pushed into its own issue (#299); is it o.k. closing this issue? I believe we have an agreement on the higher level question.
