### ISSUE TITLE
Array of strings in links/resources/readingOrder

### ISSUE THREAD

**Issue by HadrienGardeur** [w3c/wpub#290]
While working on a JSON Schema for our current draft (see #287), I was surprised to see that we allow strings in `links`/`resources`.

While I understand why we allow this in `readingOrder`, I find the use of strings problematic overall for a number of reasons:

**1. `links`**

Since this is meant to enumerate resources that are not part of the publication but could remain useful, without a `rel` and `encodingFormat`, there's strictly nothing that a UA could do with these resources.

Let's take the example of a link to an ONIX record:

_As a string_
```
"links": ["record.xml"]
```

_As an object_
```
"links": [
  {
    "url": "record.xml",
    "rel": "describedby",
    "encodingFormat": "application/onix+xml"

  }
]
```

I really can't think of a single use case where a string would be sufficient.

**2. `resources`**

References in `resources` are a little trickier. With just a string, we could in theory still package and cache these resources.

In practice, things are a little different though:

- some of these resources could be too large to fit in a cache (audio or video resources) or in a package
- unsupported formats would also make very little sense in a cache (once again, this is quite common for audio/video where there are many competing formats)

To make the proper decision whether to cache/package a resource, a UA would ideally need to know:

- the media type of the resource (available in `encodingFormat`)
- some additional info about the nature of the resource (size in bytes for example)

There are also other use cases where knowing the media type is important. For example if a UA wants to preload CSS/fonts/JS to optimize rendering speed, it would need to be able to identify these resources (using `encodingFormat` once again).

While this isn't as clear cut as `links`, there's IMO a strong argument for always listing such resources with at least their media type.

**3. `readingOrder`**

As we can see in the audiobook experiment that I've created, handling an audiobook in an optimal way requires that we identify the media type of resources listed in `readingOrder` as well.

Since most WP will strictly use HTML, I think that allowing strings is fine, but we need to know how these strings will be processed while parsing the manifest and creating WebIDL.

IMO, we should add spec language to indicate that strings will be processed as references to HTML resources. If an author wants a UA to process such resources differently, they must use the object form and indicate a media type using `encodingFormat`.

**Comment by iherman** [comment]
@HadrienGardeur,

I do not think there were any strong arguments in general. As you say, it was pretty much natural to do that for reading order, and I believe we simply reused the same structure, for the sake of symmetry, for resources and links. All this to say that if we decide those two take only Publication Links, I won't object. (Let us what others say.)

That being said... some minor points in your arguments that we have to take into account. As far as I know, browser implementations do not trust the media types assigned to resources; they are considered not to be trustworthy. (Maybe @Mustlaz or @BCWalters can tell us more about this). Ie, if a reference is "something.png", browsers will consider it as an image and look at the HTTP return for further information. In other words, if such a link is put, for whatever reasons, into a `resource` without any further information, it will work.  

That being said, I can believe that EBook readers are more 'careful'. I do not know.

That also means that I would not want to restrict these strings to be considered to be HTML resources only, even in the reading order. If the reading order contains, e.g., an SVG file "example.svg", that should be acceptable, too.

**Comment by HadrienGardeur** [comment]
Rendering is quite different from some of the use cases covered in this issue and IMO it only applies to `readingOrder`.
For rendering, while strings might be acceptable for WP, I don't think they would be acceptable for EPUB4 without a clear default.

You could say that `"resources": ["foo"]` is the equivalent of `<link href="foo">` in an HTML document. I don't think that a browser would do anything with that or even attempt to fetch it, same thing for a WP UA.

But instead if we use `"resources": [{"url": "foo", "encodingFormat": "text/css"}]` or `<link href="foo" rel="stylesheet">`, then we open the door to a different behaviour from the UA, where a GET request might get triggered.

**Comment by iherman** [comment]
I still believe that consistency in our definitions is important. We have three manifest properties that have similar structure: readingOrder, resources, links. I believe imposing constraints on some of those while being permissive on other is a source of possible errors. I would prefer to treat them all the same way and, as we have seen, it does make a lot of sense to allow for simple strings for one of them, I would prefer to keep them for all.

It would be fine to add a note to the sections on resources and links whereby it is recommended not to use simple strings for those, to emphasize the importance of the other attributes. Note, however, that in the current draft the only _required_ property for a PublicationLink is `url`, which is hardly better than a simple string...

**Comment by HadrienGardeur** [comment]
@iherman in RWPM, the model itself only requires a `href` (equivalent of `url`) but we require `type` (equivalent of `encodingFormat`) in multiple collections (including `resources`).

This is how we deal with that issue and this is validated in the JSON Schema as well.

A note is better than nothing IMO:

- objects in `links` SHOULD include an `encodingFormat` and a `rel`
- objects in `resources` SHOULD include an `encodingFormat`
- resources listed in the `readingOrder` that are not HTML SHOULD use the object form and `encodingFormat`
