### ISSUE TITLE
Document Collection Interface

### ISSUE THREAD

**Issue by dauwhe** [w3c/wpub#3]
_From @dauwhe on June 27, 2017 17:12_

Our [White Paper](http://w3c.github.io/dpub-pwp/#web-publication-apis) talks about the need for an interface and API for a collection of web resources. So really all we have to do is figure this out:

```
interface Collection: Node {
[SameObject] readonly attribute DOMImplementation implementation;
  readonly attribute USVString URL;
  readonly attribute USVString collectionURI;
  readonly attribute USVString origin;
  readonly attribute DOMString compatMode;
  readonly attribute DOMString characterSet;
  …a few missing details :)
};
```

Perhaps something like this, more than anything else we are discussing, is what it means for publications to be a first-class citizen of the web.

_Copied from original issue: w3c/publ-wg#13_

**Comment by dauwhe** [comment]
_From @GarthConboy on June 27, 2017 18:17_

Though it is worth noting that we purposefully removed a reference to such APIs from our charter during drafting in an effort to trim our scope.  Doesn't mean we can't expand to such APIs (Collection API, Publication object model), but it doesn't seem a required deliverable.

**Comment by dauwhe** [comment]
_From @baldurbjarnason on June 28, 2017 1:13_

My preference would be to punt any talk about such an API down the road, largely because if we let it wait a bit, the odds of us being able to do an API like that well increase dramatically.

Once you have a JSON-based manifest (or any sort of manifest JS in the browser can parse) then we can start experimenting with writing JS libraries that offer such an API. And if those work, then we can use that experience to polyfill the API to see what that would work like. And if that works, and if it poses to offer an actual advantage over external libraries, then we can put together a spec based on our experience.

So, my suggestion is to put it on the back burner.

**Comment by iherman** [comment]
Put on https://github.com/w3c/wpub/wiki/Beyond-Scope
