### ISSUE TITLE
How do we represent Kana for book title/publisher name/creator name

### ISSUE THREAD

**Issue by rakutenjeff** [w3c/wpub#309]
This is split from https://github.com/w3c/wpub/issues/299#issuecomment-413542119

In epub 3 we use following way to represent Kana ("クモノイト", pronunciation) versionand Kanji version ("蜘蛛の糸") of title. 
```
<dc:title id="title">蜘蛛の糸</dc:title>
<meta refines="#title" property="file-as">クモノイト</meta>
```

Can we find a way to represent this more properly?

The use case is RS needs Kana information of title or author to sort side-load Japanese book correctly. I have to say even though in epub "file-as" is still not a good solution since "file-as" can have too much information (such as script) rather than Kana.

How can we do this better?

**Comment by HadrienGardeur** [comment]
We don't have the equivalent of `file-as`, I've already filed an issue for that at https://github.com/w3c/wpub/issues/188.

I think the title of this issue is misleading though, as it doesn't have anything to do with `file-as`.

If you're trying to translate something, this is how it could be handled right now:

```
"name": [
  {
    "@language": "ja",
    "@value": "村上 春樹"
  },
  {
    "@language": "en",
    "@value": "Haruki Murakami"
  }
]
```

If we move to language maps, this would be expressed as:

```
"name": {
  "ja": "村上 春樹"
  "en": "Haruki Murakami"
}
```

**Comment by rakutenjeff** [comment]
Thanks @HadrienGardeur for referring. This is not different language script or translation. And I am not requesting equivalent of "file-as". I just need to find a way to let RS can process following metadata and understand that  "クモノイト" is Kana of book title "蜘蛛の糸".

```
<dc:title id="title">蜘蛛の糸</dc:title>
<meta refines="#title" property="file-as">クモノイト</meta>
```

As you can see from above example, "クモノイト" is just marked as additional information to this title and value of "file-as" could be anything rather than Kana. But RS needs more specific information to parse it and say "ok, クモノイト is Kana for this title 蜘蛛の糸 now we can use クモノイト as hint to sort books in library"

**Comment by llemeurfr** [comment]
Well, kana (hiragana / katagana) being scripts, a title in japanese + kana can be referenced via `ja-kana`. You'll find this code used in e.g.https://www.iso.org/schema/isosts/v1.0/doc/n-cvd0.html. The `kana`token comes from  iso 15924 (https://en.wikipedia.org/wiki/ISO_15924).

I believe an alternate title in kana can be expressed as:

```
"name": {
  "ja": "村上 春樹"
  "ja-kana": "クモノイト"
  "en": "Haruki Murakami"
}
```

**Comment by rakutenjeff** [comment]
oh, ok thanks @llemeurfr yes seems `ja-Kana` as @HadrienGardeur mentioned, it's all BCP-47 https://tools.ietf.org/html/bcp47#section-2.2.3
