### ISSUE TITLE
Why is resource list required?

### ISSUE THREAD

**Issue by dauwhe** [w3c/wpub#311]
resource-list is a [required property](
https://w3c.github.io/wpub/#wp-properties-req) for a WPUB manifest. 

How does this actually work? We don't require any particular component of a web publication to be in this list. What if a WP consisted only of HTML files that were in the default reading order? Would you then be required to have an empty resource list?

**Comment by HadrienGardeur** [comment]
I agree, it shouldn't be a required property (it isn't required in [the current JSON Schema](https://github.com/w3c/wpub/blob/master/schema/publication.schema.json)).

**Comment by rakutenjeff** [comment]
It looks like inherited from epub?
Maybe add some note to mention exception is when WP consisted only of items that is already in default reading order?

**Comment by iherman** [comment]
> It looks like inherited from epub?

Ah. That may be the case

> Maybe add some note to mention exception is when WP consisted only of items that is already in default reading order?

The draft currently says that:

> The resource list enumerates all resources that are used in the processing and rendering of a Web Publication (i.e., that are within its bounds) and that are not listed in the default reading order.

With that, I am not sure having that exception mentioned really makes sense.

I vote to remove it from the required list.

**Comment by mattgarrish** [comment]
> It looks like inherited from epub?

Not so much this as that this:

> and that are not listed in the default reading order.

was added later. Earlier on, it was an open issue whether resources in the reading order also had to be in resource list.

But a no-brainer change now, if there ever was one.

**Comment by TzviyaSiegman** [comment]
@mattgarrish make it so!

**Comment by mattgarrish** [comment]
Closing this with the commit of #313
