### ISSUE TITLE
"Web Publications" is not a search engine-friendly name

### ISSUE THREAD

**Issue by bitsgalore** [w3c/wpub#319]
Bit of a silly issue really but I'll just mention it just in case: a [Google query on "Web Publications"](https://www.google.com/search?q="web+publications") returns 267,000 hits, most of which are totally unrelated to the current standard! For visibility and ease of reference you might consider a name which is less generic and more search engine-friendly. For instance, searching for ["Open Web Publications"](https://www.google.com/search?q="open+web+publications") (hint, hint) already cuts down the number of hits considerably.

**Comment by danielweck** [comment]
> For instance, searching for "Open Web Publications" (hint, hint) already cuts down the number of hits considerably.

Problem: OWP stands for Open Web *Platform* already.
https://www.w3.org/wiki/Open_Web_Platform

**Comment by mattgarrish** [comment]
The OWP name was rejected for the reason @danielweck notes. I threw it out at some point when we were trying to come up with a names as I liked the symmetry, but others disliked it for that reason and because of the conflicting acronyms.
