### ISSUE TITLE
Supplemental Content in Audiobooks

### ISSUE THREAD

**Issue by wareid** [w3c/wpub#320]
A format issue we've encountered with publishers has been the inclusion of "supplemental" content in audiobooks. This is usually a PDF or EPUB included with the book that provides any charts or images referenced in the audio. 

In a WP it seems like it would be fairly straightforward to include supplemental content in a mainly audio WP, but I'd like to open up the discussion. I'm thinking it would be as simple as this(thanks to @HadrienGardeur for the main format, I'm just piggybacking off his excellent example):

```
"resources": [
    {"rel": "cover", "url": "http://www.fakeurl.com/images/cover.jpg", "encodingFormat": "image/jpeg"},
    {"rel": "contents", "url": "toc.html", "encodingFormat": "text/html"}
  ],

  "readingOrder": [
    {"url": "https://www.fakeurl.com/download/sample/chapter1.mp3", "encodingFormat": "audio/mpeg", "name": "Chapter 1"},
    {"url": "https://www.fakeurl.com/download/sample/chapter2.mp3", "encodingFormat": "audio/mpeg", "name": "Chapter 2"}, 
    {"url": "https://www.fakeurl.com/download/sample/chapter3.mp3", "encodingFormat": "audio/mpeg", "name": "Chapter 3"}, 
    {"url": "https://www.fakeurl.com/download/sample/charts.html", "encodingFormat": "text/html", "name": "Supplemental Content"}
  ]
```

**Comment by HadrienGardeur** [comment]
You could reference such contents in `links` or `resources` as well, if it's not intended to be displayed sequentially.

You could even point to the EPUB/PDF themselves, no need to necessarily unpack them before.
