### ISSUE TITLE
The primary entry page may be under specified

### ISSUE THREAD

**Issue by llemeurfr** [w3c/wpub#329]
From reading the specification, it is difficult to have an idea about what the primary entry page is made for. 

It's introduced in 3.5 resources as the only required resource in a WP. 
In 3.6 we discover that the ToC should be located there (if not the manifest should reference it). This is detailed in 4.6.2.
In 4.3.2 we discover that the Web Publication address is the URL of this resource (but 4.3.2.1 states that it may not be an HTML resource, in which case the user should not have access to it (SVG forbidden)).
In 4.3.5 we see that it can have some influence on the language and base direction of the WP, and in 4.3.9 that the title of the WP may be inferred from it. 

I wonder if such an important piece of information for WP should have its specification grouped in a specific section (in 3.5 ?).

**Comment by iherman** [comment]
I see the point, I have actually hit this issue at some point; it is an important concept and its role is scattered over the document. Yes, it may be better to regroup things at one place.

@mattgarrish ?

**Comment by mattgarrish** [comment]
I actually thought we had a section on it, but I probably just got confused by all the bikeshedding about the name we did. Certainly seems useful to detail it under the construction section.

**Comment by llemeurfr** [comment]
@mattgarish yes let's close it, the new section is a really good start. Thanks.
