### ISSUE TITLE
manifest must be embedded in primary entry page

### ISSUE THREAD

**Issue by mattgarrish** [w3c/wpub#333]
[As discussed](https://github.com/w3c/wpub/pull/331#issuecomment-419456205) in PR #331, there are currently no restrictions on what resource can contain the embedded manifest. Proposal is to restrict to the primary entry page (must provide a link to the manifest or must embed the manifest).

**Comment by dauwhe** [comment]
Yes. Absolutely!

**Comment by GarthConboy** [comment]
And semi-related... how does a WP-aware RS/AU know that a non-primary-entry-page resource is part of a WP.  E.g., a link to "chapter 27" -- how does such a RS/UA know to jump into "WP mode" following that link?  And, yea, all the "part of multiple WPs" issues arise too.

**Comment by BigBlueHat** [comment]
If we want any SEO value from the contents of the manifest, it MUST be embedded in the entry page.

**Comment by mattgarrish** [comment]
This is closed with #335.
