### ISSUE TITLE
primary entry page must be added to reading order when reading order not specified

### ISSUE THREAD

**Issue by mattgarrish** [w3c/wpub#334]
[As discussed](https://github.com/w3c/wpub/pull/331#issuecomment-419635650) in PR #331, the default reading order is required, but the primary entry page may be omitted from it when it is the only resource it would contain. Missing is a statement that, in this case, user agents must add the primary entry page to the default reading order when compiling the infoset.

**Comment by HadrienGardeur** [comment]
Isn't that covered in step 6 of [the canonical manifest algorithm](https://w3c.github.io/wpub/#canonical-manifest)?

**Comment by mattgarrish** [comment]
Yes, but there should be a clearer statement in 4.4.1.1 that matches the expected behaviour. All it says right now is that the entry page can be omitted.

**Comment by mattgarrish** [comment]
This is closed with #335.
