### ISSUE TITLE
4.7.3 Pagelist - typo "pagesList" vs. "pageList"

### ISSUE THREAD

**Issue by danielweck** [w3c/wpub#346]
https://w3c.github.io/wpub/#pagelist

There are occurrences of both:
`https://www.w3.org/ns/wp#pagelist` (singular)
and
`https://www.w3.org/ns/wp#pageslist` (plural)

The plural form seems to be correct for the URI identifier, and only used in this particular case. That being said, I would like to suggest using singular or plural consistently everywhere: in the JSON property, URI identifier, normative and informative prose, etc.

**Comment by iherman** [comment]
Closed through https://github.com/w3c/wpub/issues/346#ref-commit-0447a8b
