### ISSUE TITLE
typo? "table-of-contents"

### ISSUE THREAD

**Issue by danielweck** [w3c/wpub#347]
https://w3c.github.io/wpub/#table-of-contents-infoset
> User agents MUST compute the `table-of-contents` as follows:

`table-of-contents` should be "table of contents", I think.

Also, may I suggest to consistently use either the singular or plural form of "content(s)"?

**Comment by mattgarrish** [comment]
Yes, I caught these a little earlier while doing some tinkering in a branch.[1] If that PR doesn't materialize, I'll create a new one just for these.

[1] https://github.com/w3c/wpub/commit/2845a21570a4a7fad763f721bdc4118f954b9c88

**Comment by iherman** [comment]
Has been taken care of (just not closed...)
