### ISSUE TITLE
Explain the purpose of the "canonical manifest"

### ISSUE THREAD

**Issue by mattgarrish** [w3c/wpub#349]
The canonical manifest section appears without much in the way of introduction/explanation, which makes it confusing to understand. Yes, it's how you can get a json data structure from the manifest and the infoset rules, but why does this matter? Who is expected to create this manifest? When? In what context?

If the infoset is a non-language specific internal representation, then why define one process that creates a json representation of the infoset, in other words? Is it just intended as an example of how you might apply the rules for one kind of data representation?

An introduction that helps clear up its inclusion in the specification would really help.

**Comment by iherman** [comment]
The technical answer: it is a step to make ambiguities disappear when obtaining the manifest, and is used in step (9) of the process described in 6.1. Ie, it is can be seen as a purely technical step in obtaining the manifest and converting it into an internal data structure. It is used, therefore, by implementers and authors can probably ignore it.

Editorial answer: you are right:-) it may need some care. Actually, as one possible editorial step is to remove it as a separate top level section, and make it a subsection of section 6, probably a (new) 6.2. Whether that is enough to clear it, I am not sure, but it may help in properly positioning the beast...
