### ISSUE TITLE
Condition to have no readingOrder in a manifest

### ISSUE THREAD

**Issue by llemeurfr** [w3c/wpub#368]
In https://github.com/w3c/wpub/pull/367, because the manifest is embedded in the entry page and the entry page is the sole resource in reading order, there is no readingOrder item in this manifest. ok. 

But the [spec in 4.4.1](https://www.w3.org/TR/wpub/#default-reading-order) tells only part of this story: 
*The default reading order is specified directly in the manifest. However, if the reading order consists of only a single resource, namely the primary entry page of the Web Publication, the default reading order need not be specified.*

It should be written IMO:
The default reading order is specified directly in the manifest. However, if the reading order consists of only a single resource, namely the primary entry page of the Web Publication, **and if the manifest is included in this single resource**, the default reading order need not be specified.

**Comment by HadrienGardeur** [comment]
Even if the manifest is not embedded in the entry page, you could still infer the `readingOrder` using `url` if `readingOrder` is empty.

**Comment by llemeurfr** [comment]
@HadrienGardeur this is right, I'll close the issue.
