### ISSUE TITLE
Write an audiobook explainer

### ISSUE THREAD

**Issue by dauwhe** [w3c/wpub#372]
We should write an [explainer document](https://github.com/w3ctag/w3ctag.github.io/blob/master/explainers.md) as we design audiobooks, and share it with the TAG as early as possible.

**Comment by wareid** [comment]
https://github.com/wareid/audiopub-explainer

**Comment by wareid** [comment]
Adding propose closing since we have a PR in place to add the explainer :).

**Comment by dauwhe** [comment]
And we now have an audiobook explainer, thanks to @wareid !
