### ISSUE TITLE
TOC directly encoded in the manifest?

### ISSUE THREAD

**Issue by iherman** [w3c/wpub#376]
The current (2018-12-08) draft includes a [detailed algorithm](https://w3c.github.io/wpub/#app-toc-ua) for the retrieval of a TOC from HTML. Question is whether it should **_also_** be possible to add the TOC directly into the manifest (ie, bypassing the HTML) using the same data structure as produced by that algorithm.

**Comment by iherman** [comment]
The question was discussed in issue #291, and there was no consensus. **_Some_** relevant comments, and other issues:

- Issue #369 
- https://github.com/w3c/wpub/issues/291#issuecomment-438340767
- https://github.com/w3c/wpub/issues/291#issuecomment-438835941
- https://github.com/w3c/wpub/issues/291#issuecomment-439044346

**Comment by dauwhe** [comment]
Tables of contents are designed to be presented to end users. Over the last thousand or so years of print publishing, and the last few decades of web publishing, we have developed certain techniques to help authors express themselves. At the very simplest level, these include things like italics, superscripts and subscripts, bold text, etcetera. HTML handles these things effortlessly. 

But what about JSON? It is truly common for a TOC entry to contain an italic phrase. How would we express that in a JSON TOC? The solution I've seen is allowing embedded HTML in the JSON:

```json
"toc": [
    {
      "url": "http://www.example.com/part1/index.html",
      "name": "Part 1",
      "children": [
        {
          "url": "http://www.example.com/ch1/index.html",
          "name": "The Building of the <i>Titanic</i>"
        }]
...

```

This was a major issue with EPUB's NCX.

**Comment by laudrain** [comment]
@dauwhe if I understand well, this issue isn't about the visual TOC.
It's about the TOC when it has to be in the manifest, there are use cases that need it, for instance to achieve accessibility. BTW, This was one of the goal of NCX.

**Comment by dauwhe** [comment]
> @dauwhe if I understand well, this issue isn't about the visual TOC.
> It's about the TOC when it has to be in the manifest, there are use cases that need it, for instance to achieve accessibility. BTW, This was one of the goal of NCX.

My understanding is that the "machine-readable" TOC is made available to the user, but the manner of presentation is controlled by the user agent and not the author, much the way the NCX worked. 

I think it's important that this TOC still support some inline styling, as it does convey semantic meaning which should be available to all users. If many current EPUB reading systems strip out inline elements from the `nav`, I think that is a bug and not a feature. We should not limit the ability of document authors to express information, and we should not prevent user agents from displaying richer information. File formats should adapt to human needs, rather than humans adapting to the limitations of file formats.

**Comment by llemeurfr** [comment]
The interest for a JSON ToC comes mainly from the Audiopub TF, as it may well be that audiobook publishers will be worried if they have to create HTML documents as ToC. A simple authoring tool would help them add metadata + a simple hierarchical ToC to their work (with links to audio fragments).

**Comment by HadrienGardeur** [comment]
> If many current EPUB reading systems strip out inline elements from the nav, I think that is a bug and not a feature.

There's a good reason for them to do that:

- they can't trust the content, which means that they need to white list tags and sanitize strings
- these styles can interfere with their own (for Web Apps) or can't be easily rendered (for native apps)

Sure, you can just blame it all on reading systems, but understanding why they sanitize strings is IMO quite a bit more constructive.

**Comment by HadrienGardeur** [comment]
Just for the sake of curiosity, are you aware of any RS that can display such tags @dauwhe?

It seems that even Edge is sanitizing these strings and stripping HTML out of it for its own UI.

This is something that will also be useful to test in the EPUB CG as part of testing support for EPUB 3.2 across RS.

**Comment by GarthConboy** [comment]
I think audiobooks can be fine with pulling the TOC from HTML.  One approach is better than two.

**Comment by dauwhe** [comment]
> Just for the sake of curiosity, are you aware of any RS that can display such tags @dauwhe?

I made a test. AZARDI preserves italic. iBooks, Kobo, Google Play, and Kindle/Mac strip out the italic.

**Comment by dauwhe** [comment]
> There's a good reason for them to do that:
> 
> * they can't trust the content, which means that they need to white list tags and sanitize strings

In the case of EPUB, many people also put the nav doc in the spine, and so the reading system is obligated to display it. Are you saying that HTML that undergoes further processing requires a higher level of trust? It certainly makes sense to strip out JS here:

 ```html
<li><a href="chapter2.html" onclick=alert(9)>The Building of the <i>Titanic</i></a></li>
```
But I don't understand the security risk posed by ordinary HTML phrasing content like i, em, sup, etc.

> * these styles can interfere with their own (for Web Apps) or can't be easily rendered (for native apps)
> 

I expect most text rendering facilities used by apps of any sort can handle some simple things like italic. And if the web app has complete control over the presentation of this content, how is there a conflict?

> Sure, you can just blame it all on reading systems, but understanding why they sanitize strings is IMO quite a bit more constructive.

What I'm trying to express is a use case: it is much easier for readers to understand certain kinds of text when basic inline formatting, of the type supported by HTML, is available. And I'm concerned that this possibility will be absent in a JSON table of contents. 

Our goal as a working group is not to make something that works exactly like EPUB. Our goal should be to make something better—something that better serves the needs of end users. Having an italic word in a TOC entry is admittedly a small thing, but I think it's a real benefit to readers, and I am not yet convinced it's so difficult that the burden on implementors outweighs the benefit to end users.

**Comment by TzviyaSiegman** [comment]
Thanks, @dauwhe. I could provide several examples of scholarly publications that include math in TOC heads. They don't make much sense in EPUB. We hack around it badly.

**Comment by mattgarrish** [comment]
I would just caution that EPUB was intended to serve a wide variety of reading systems. An auditory system, for example, would only extract/use text labels. A low-power text reader similarly isn't going to manage more than simple display of the text content. For others, implementing a subset of HTML within their tree views is not as simple as just demanding it be done. The more rigidly we say what a reading system has to do, the more difficult we make it for these to conform. It may be something we don't care about for WP, but apples and oranges are getting compared at times in this thread.

I'm all for giving the user agent the choice to use the descendant HTML of an ```a``` tag, but ruling out a user agent from generating a text-only label strikes me as a bad idea.

**Comment by mattgarrish** [comment]
Also, the primary motivator for moving to the nav doc, beyond the complexity of the ncx, was to improve support for internationalization: http://github.com/w3c/publ-epub-revision/blob/wiki/Navigation.md

It might be good to expand the discussion beyond what North American/European reading systems make use of. If JSON can't support ruby, and ruby is critical for readers in Asia, then we definitely aren't making progress.

**Comment by iherman** [comment]
I am afraid we are engaging into a discussion which is **_not_** the subject of the current issue and we may also be reopening the discussions we had in issue #291 in "visual" TOC. We should try to avoid doing so.

* Whether the TOC, as expressed in [the draft](https://w3c.github.io/wpub/#app-toc-structure) is used by the User Agent as is (ie, just displaying the HTML), whether it is used to extract an internal data structure along the line of the [extraction algorithm](https://w3c.github.io/wpub/#app-toc-ua) and do what "traditional" user agents do, or anything in between is, currently, left to the User Agent. This is not at discussion in this issue. (If we want to discuss this, let us open a separate issue.)

    B.t.w., looking at the details of the extraction algorithms, the labels for links are extracted through the [accessible name](https://www.w3.org/TR/accname-1.1/#mapping_additional_nd_te). This means that, again in the current algorithm, HTML tags _will_ be stripped, but the content _will_ take into account such accessibility features like aria labels. This is good for accessibility (probably better than the EPUB 3.2 version) but may not be good for the types of effects that @dauwhe was talking about. If that detail of the algorithm must be re-discussed (eg, by requiring the extraction of an HTML text rather than the accessible name), **_let us open a new issue_**.

* The _only_ question in this issue is whether authors _MAY_ (**_not_** _MUST_) fill a JSON-LD manifest entry directly with a data structure that is to be extracted by the [extraction algorithm](https://w3c.github.io/wpub/#app-toc-ua). 

We should try to concentrate on this and only this issue here...

**Comment by HadrienGardeur** [comment]
I don't think the discussion was entirely out of scope either @iherman.

@dauwhe pointed out the lack of support for italics, superscript and similar tags as a major issue with the JSON approach.

I've pointed out that in practice, for a number of reasons, these tags are not extracted by UAs. As you've pointed out as well, they wouldn't be supported by our current take on the extraction algorithm either.

Now that this is out of the way, I think there are a number of pros and cons to saying that a manifest MAY contain a ToC in JSON-LD.

**Pros**

- it's very easy for UAs to process JSON, much easier than the extraction algorithm for HTML
- we could also extend our JSON-LD context to cover the ToC, which means that the ToC would be part of the RDF graph extracted from our manifest
- audiobooks and potentially visual narratives would not need to produce HTML just for the sake of having a ToC
- through our handling of localized strings, we can easily create a localized ToC as well

**Cons**

- it potentially duplicates information when an HTML ToC is also present
- we'll be limited to plain text (same as the current extraction algorithm)
- JSON can't be rendered by default, which means that UAs that are not WP-aware won't be able to display the ToC if it's only expressed as JSON

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/publishing/groups/publ-wg/Meetings/Minutes/2019/2019-02-11-pwg#section2).

- No actions or resolutions
<details><summary><i class="differentiate">View the transcript</i></summary>
Table of content issue<br/>
Wendy Reid: <a href="https://github.com/w3c/wpub/issues/376">https://github.com/w3c/wpub/issues/376</a><br/>
Wendy Reid: Next issue is related to tables of contents<br/>
… posting link to GitHub issue, regarding the location of the TOC…<br/>
… should we be directly encoding the TOC into the manifest, or should it be a separate file referenced in the manifest?<br/>
… the main issue is formatting. Keeping it HTML allows for rich formatting, but a separate file would be easier to process…<br/>
… a lot of user agents aren’t currently using styling, but it doesn’t have to remain that way…<br/>
… some providers may prefer a JSON file<br/>
Ivan Herman: I have a question to various reading system implementers: at the moment, the TOC is defined to be in HTML and we’ve spent an inordinate amount of time defining the format in HTML…<br/>
… my favorite option is to say that that’s where we stop, realizing that this means reading systems must be able to parse an HTML file, extract the TOC out of it, even if it doesn’t use any styling…<br/>
… what I have difficulty judging, is it really such a huge deal for reading systems, knowing that these days taking a public domain HTML parsing library and running it to extract the TOC is really not such a huge deal…<br/>
… it would make things much clearer if we had one and only one format for the TOC, and we didn’t have yet another option we have to define…<br/>
… is it really such a big deal?<br/>
… (i.e., to process the HTML file)<br/>
Garth Conboy: I’m fine with HTML and I’m also fine with only HTML, just because my take is that any reading system taking this packaged audiobook is likely to also be taking EPUB<br/>
Laurent Le Meur: I still agree that if we can make something simple in HTML, something easy to create by the publisher/studio, then I agree with only HTML. But we have to realize that the difficulty is with the authors who have to use this format, and not the implementers.<br/>
Geoff Jukes: I would be against (?) HTML due to the assets we receive - hundreds and hundreds a week…<br/>
… putting it in the manifest is eminently usable for us<br/>
Garth Conboy: It’s a serialization issue: is it that much easier to encode in JSON than HTML? I don’t understand why that’s hard<br/>
Geoff Jukes: It’s not hard, but for me it’s redundant in a lot of our use cases. I can’t think of a use case where creating an HTML file is of any use<br/>
… but a structured manifest, when we’re processing third party books, extracting structured metadata is easy. In the B2B world, if the specification requires HTML, some people will just ignore it…<br/>
… turning HTML as something freeform, into something structured, is harder. Whereas a manifest is structured<br/>
Garth Conboy: It sounds like you don’t want a TOC - you just want the manifest<br/>
Geoff Jukes: From an audiobook perspective, what publishers produce and what we exchange is just a bunch of files. They have filenames that are supposed to aid in sorting, but it’s super loose…<br/>
… we sometimes add what we call a chapter list, but not every book conforms to that…<br/>
… sometimes it’s literally just track 1, track 2, track 3…<br/>
… publishers don’t necessarily cut at chapter/part boundaries, it could be random or every X minutes…<br/>
… the list of files doesn’t correlate 1:1 to a neat book structure…<br/>
… every publisher has their own approach to displaying a chapter which might be broken into two or more parts…<br/>
Geoff Jukes: <a href="https://github.com/blackstoneaudio/audiobook-spec/blob/cfd468bb27b890b0e4a59a3345e806221a702fce/draft.yaml#L138">https://github.com/blackstoneaudio/audiobook-spec/blob/cfd468bb27b890b0e4a59a3345e806221a702fce/draft.yaml#L138</a><br/>
Tzviya Siegman: I’m growing confused about what Geoff is describing. I can think of numerous scenarios for audiobooks where the TOC isn’t necessarily designed…<br/>
… a lot of reading systems strip out CSS, but publishers and users want more information than just the filename. Eg if chapter 3 is read by a special narrator, that should be visible…<br/>
… we want to align with the work in synchronized media that Marisa is working on…<br/>
Mateus Teixeira: +1 to tzviya<br/>
Tzviya Siegman: if it’s just going to be a list in HTML, with CSS from the publisher, you can discard the CSS<br/>
Brady Duga: One of the uses for HTML: you could have ruby for eg Japanese chapter titles. This would be hard in JSON…<br/>
… you can recreate the properties of HTML in JSON if you want to, but it’s hard…<br/>
… what we want to do with the TOC is something that doesn’t exist in audiobooks: create a rich table of contents around the audio that has nothing to do with the structure of the audio files…<br/>
… I don’t care how the files are actually structured, I want to say ‘here are the chapter breaks throughout the audiobook’ - can reference one or many files…<br/>
… I want something analogous to an ebook TOC. It’s not something that exists today in the audiobook market<br/>
Garth Conboy: What Geoff is saying is that your classic audiobook doesn’t have this TOC in it - if you want to create a new audiobook with no or a barebones TOC, so be it - but doing a good job of Brady’s enriched TOC clearly doesn’t have to be part of the spec, but we want a way to do it<br/>
Wendy Reid: We’re talking about this in the context of the core spec. Maybe a better way to consider this is how each module can deal with TOCs. This problem could look very different in eg manga, academic publications<br/>
George Kerscher: I understand with the audiobook that you might get a flat list of filenames - I’ve seen different reading systems throw away the styling and add a machine-readable version of the TOC…<br/>
… I totally get lost, I don’t know what the subsections are when it’s just a flat list. The accessibility features of HTML provide me with useful information…<br/>
… I can understand that this is a subsection rather than a higher level chapter heading. Not in CSS, just natively in HTML<br/>
Geoff Jukes: +1 if optional<br/>
Ivan Herman: Maybe it’s not clear: the TOC is optional - this is already the case<br/>
… the modular approach (referred to by Wendy) could be ok, provided we make it clear that an audiobook reader MUST understand the HTML version<br/>
… every reading system must understand how the TOC is supplied<br/>
Wendy Reid: We will continue this discussion next time. No meeting next week<br/>
</details>

**Comment by HadrienGardeur** [comment]
> Garth Conboy: I’m fine with HTML and I’m also fine with only HTML, just because my take is that any reading system taking this packaged audiobook is likely to also be taking EPUB

@GarthConboy I think that not a correct assumption. There are a lot of audiobooks only reading systems available and there are also dedicated audio devices (including smart speakers). Neither of them currently support EPUB or HTML.

> Ivan Herman: I have a question to various reading system implementers: at the moment, the TOC is defined to be in HTML and we’ve spent an inordinate amount of time defining the format in HTML…
… my favorite option is to say that that’s where we stop, realizing that this means reading systems must be able to parse an HTML file, extract the TOC out of it, even if it doesn’t use any styling…
… what I have difficulty judging, is it really such a huge deal for reading systems, knowing that these days taking a public domain HTML parsing library and running it to extract the TOC is really not such a huge deal…

@iherman with the same approach as EPUB, it's not a big deal. But if any HTML is allowed, it becomes quite difficult to achieve properly.

> Brady Duga: One of the uses for HTML: you could have ruby for eg Japanese chapter titles. This would be hard in JSON…
… you can recreate the properties of HTML in JSON if you want to, but it’s hard…

@bdugas that's the theory,  but in practice I think that @dauwhe has only been able to identify one reading system capable of handling any kind of markup in its TOC and everywhere else only plain text is extracted.

Working with markup in any native UI element is difficult and most product owners working on reading apps would be against it anyway.

Here's a good example: https://twitter.com/micahsb/status/1093657329592033280

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/publishing/groups/publ-wg/Meetings/Minutes/2019/2019-02-25-pwg#section1).

- No actions or resolutions
<details><summary><i class="differentiate">View the transcript</i></summary>
ToC in JSON-LD<br/>
Tzviya Siegman: <a href="https://github.com/w3c/wpub/issues/376">https://github.com/w3c/wpub/issues/376</a><br/>
Tzviya Siegman: Next item on the agenda is the TOC. We need to come to a resolution on this issue. Github link posted. This is about if the TOC directly encoded in the manifest. We came close to a resolution but didn’t quite get there. Continued on github (and twitter…)<br/>
… the last point of discussion in our meeting was that - with audiobooks they don’t necessarily have a TOC, but we don’t make our specification audiobook specific or exclusive. So if serializing HTML or JSON were really very different…<br/>
… then some discussion about if the TOC is required. There’s a link in the github comments… If the TOC isn’t required then it doesn’t matter if it’s HTML or JSON. I believe what we’re coming around to is the TOC is required to be in HTML but it still remains optional<br/>
Proposed resolution: for AudioBooks, ToC is optional; serialized in HTML. (Garth Conboy)<br/>
Tzviya Siegman: the proposal is for WP, not just Adiobooks<br/>
Garth Conboy: we can have different rules for different profiles.<br/>
Wendy Reid: I want to state, we discussed this last time, and I believe it was Geoff – for audiobooks, we’re having the opposite problem. They don’t want HTML. The current environment for audiobooks, no one is using HTML. None of the readers are using HTML for audiobooks, so introducing it could cause a lot of issues.<br/>
… it’s still good that different profiles will have a different implementation, I just want to say that it shouldn’t have to be in HTML — Audiobooks have TOCs, but requiring HTML is the issues.<br/>
Ivan Herman: the fact that the TOC is optional is already in the document.<br/>
Tzviya Siegman: thank you for clarifying<br/>
Brady Duga: Is JSON already used by audiobook publishers? For reading systems/listening systems?<br/>
Wendy Reid: Blackstone and Kobo use JSON.<br/>
Garth Conboy: I was under the impression that the proposal I put in was where we were in agreement. If it’s optional, then we don’t really care ab out the serialization — so any system ingesting audiobooks can read any TOC. And we’d have rules as to how to serialize a TOC in HTML…<br/>
… I am not in favor of widening it to additional serialization<br/>
Geoff Jukes: We don’t use HTML for TOC, we use JSON — the main reason is that we don’t want our publishers to define how things are displayed. It’s optional and it’s use is optional — so we don’t mind it being part of the spec. If the TOC is optional, but having it requires we use it as such, that will not be OK.<br/>
… our applications are not EPUB3, they are audiobooks, and different.<br/>
… It would require additional application development for us to unserialize the HTML. It would also provide no value to us or our customers, so it seems crazy to think about.<br/>
Tzviya Siegman: I will point out that one of the things that comes up when working on specs is that we have to make compromises. It might require changes to the tool chains and how they operate. What we’re hearing is that google creates audiobooks in one way and Blackstone another. One will have to change.<br/>
… The value to creating the table of contents in HTML is that it would be useful in more than 1 implementation, not just audiobooks. All types of publications would have to allow for that possibility.<br/>
… instead of one publisher saying “I have to adjust my tool chain” all might have to think about the options. One possibility is we make a change that affects only audiobooks — but we’re trying to make things generic if we can.<br/>
Mateus Teixeira: +1 duga<br/>
Brady Duga: This has nothing to do with existing tool chain — we can parse HTML. If we adopt JSON it’s trivial. My note is that HTML is a better representation because it can do things like ruby which allows for more languages<br/>
Benjamin Young: +1 to HTML has more (i.e. i18n, a11ly, etc)–and that’s good<br/>
Laurent Le Meur: the reading system would have to handle both — just to clarify, not the publishers.<br/>
Tzviya Siegman: we do have to make a decision. Consensus is difficult, but compromise is key<br/>
Ivan Herman: What we can try to do as a pay forward, in general, for Web publication and the various profiles. We do not define a TOC in JSON in general. Some profiles may do something specific to their profile. The Audiobook profile could say: “for audiobooks, it’s possible to do it in JSON or HTML. It’s up to the publishers which way to go.” What I do not want to see is that Audiobooks say: ‘you must not do it in HTML, you must do it in JSON’ That will really create a schism that would be detrimental.<br/>
Garth Conboy: +1 Ivan<br/>
Wendy Reid: I agree with Ivan. I understand why HTML is important. It would be interesting to see audiobooks adopt rich-text experience. In terms of adoption as the industry stands today would be better with JSON. A JSON TOC within the manifest, then an HTML document with a rich version of the TOC.<br/>
… I know giving publishers options can create issues, but in the very least, if the publisher wants to create a rich-text verison, they can.<br/>
Luc Audrain: +1 to wendyreid<br/>
Ivan Herman: What this means is that in the audio profile, you’ll have to spec out not only the format, we’ll have to define if the publisher has two types of TOCs, which one wins? For the general web publication, what we have is what we have.<br/>
… We’ll have to spec this out for audiobooks only, and what it means for something to be audiobook and not audiobook.<br/>
Garth Conboy: I don’t think of the HTML as a rich-text format, as I don’t see it as something that is displayed. It’s meant to be machine readable. What I’d be proposing in the lines of compromise. In Audiobook land, the TOC can be JSON or HTML. If there are both, the HTML version wins.<br/>
Avneesh Singh: +1 Garth, html should win<br/>
Benjamin Young: Looking at linked resource, this is more an ask for Wendy and Geoff, but is that sufficient for the TOC you’re producing now? Or are you needing a TOC that is more complex and doesn’t map to the reading order?<br/>
Wendy Reid: Right now, the average audiobook we receive has a very basic TOC. Chapter 1 is this, and X long; chapter 2, etc… Sometimes we don’t even get chapters. Having a detailed TOC for the audio industry might be a push…<br/>
Benjamin Young: So that could be ranges of parts of files, right?<br/>
Wendy Reid: Yes, it could point to timings within files.<br/>
Proposed resolution: For AudioBooks ToC may be provided as serialized in either HTML or JSON, if both are present, only the HTML will be processed by the Reading System. (Garth Conboy)<br/>
Nick Ruffilo: Could we have two different designations for a TOC? Machine readable &amp; visual? JSON could be machine-readable, for example.<br/>
Geoff Jukes: We don’t use the JSON to define parts of resources — we don’t include timestamps. Our dataset is very minimal. It’s covered by the resource duration, the name of the file, the label — although we deal primarily in English…<br/>
… From a business-to-business perspective, I don’t have issues passing HTML as long as it is strictly defined — as the JSON is. My assumption is that when we tell users they can produce HTML, they will send anything.<br/>
Ivan Herman: Current structure for TOC in HTML -> <a href="https://w3c.github.io/wpub/#app-toc-structure">https://w3c.github.io/wpub/#app-toc-structure</a><br/>
Geoff Jukes: if it is strictly defined, then I don’t have a problem with it. For our existing applications, it’s of no use, but we’d translate that from B2B to something our apps use. As long as it’s strictly defined, I need it machine parsable.<br/>
Garth Conboy: Ivan just pasted in a relevant link for Geoff. The TOC we have spec’d in WP for HTML serialization. There are rules about pulling out anchors, chapter names, and it’s purely machine processible. Either HTML or JSON, if it comes in the package with the audiobook, it’s a huge improvement.<br/>
Proposed resolution: For AudioBooks ToC may be provided as serialized in either HTML or JSON, if both are present, only the HTML will be processed by the Reading System. (Garth Conboy)<br/>
Garth Conboy: It’s a big improvement than just a collection of files with an external TOC. Either of these — I think we’d be in a pretty good shape with this.<br/>
… It is designed to be machine-processable TOC, not necessarily a visual representation<br/>
Tzviya Siegman: In summary, our spec has very strict rules with HTML.<br/>
Garth Conboy: The spreadsheet is the worst of all possible worlds, but it does exist with some large publishers.<br/>
Brady Duga: We have experience using machine readable TOCs. We don’t have a huge issue with publishers going to town with the HTML. We convert it to something else. It can be converted to JSON and sent to clients.<br/>
… I wanted to add: I would rather have an ascii text based format than 2 formats. I don’t want to have JSON and HTML. I just want one. I prefer the HTML.<br/>
Tzviya Siegman: Geoff, we very much want to include the existing toolchain. I want to make it clear what our intent is with HTML. It’s a restriction on what is allowed in HTML — and it is very limited. I’m hoping we can come around to some agreement.<br/>
… We want this to work for the audiobook retailers that exist today. To comment on Nick’s proposal for rendered vs machine readable. That existed in EPUB2 — but we fought to get rid of it, so we aren’t going back. Nav was created to address that…<br/>
Proposed resolution: For AudioBooks ToC may be provided as serialized in either HTML or JSON, if both are present, only the HTML will be processed by the Reading System. (Garth Conboy)<br/>
Tzviya Siegman: Lets just review what Garth proposed, that way we can continue to review that and come to resolution on this.<br/>
Avneesh Singh: All the good things about HTML has already been said. The 2nd part — B2B and B2C — two use cases. Are we targeting B2B? It may shape up the specification in a different way. Our focus seems B2C.<br/>
Geoff Jukes: We deal with studios sending us raw audio, publishers sending us produced audio, and a consumer website. We send quite a bit of audio to other publishers as well — Kobo, etc. When I’m looking at this, I’m trying to find one system to rule them all…<br/>
… The end-user scenario is different, but the more that we can bake in, as early as possible, makes sense to me. If we can get publishers/partners to produce things early… We lose data as part of the process, because publishers do not send us standard data…<br/>
… publishers don’t send things with the same file naming conventions, etc. The more data we can standardize at the beginning, the better. I’m still new and trying to get caught up.<br/>
… As I can see it right now, an HTML TOC provides some options that we would use for our enhanced audiobooks, and it would be a natural lead-in. HTML does not seem like a good way to include the extended information we’d like to get from publishers, like hashes or filenames…<br/>
… that we can confirm the data we have is in the right order, etc. I’m a fan of JSON because it’s strictly structured, there are strict definitions for resources…<br/>
Ivan Herman: I would propose, at this point Geoff — on the one hand it’s extremely important to have your on board with what we do. On the other hand, it’s clear that there are lots of things that need to be caught up on. Some of the remarks are solvable with what we have now…<br/>
… I would be happy if we had a separate call — you, Wendy, I, Matt, etc. To look at some of the technical details to see where your problems are and if what we’re proposing is answering your concerns. In a sense help you to catch up on 1 1/2 years of WG work.<br/>
Avneesh Singh: +1 to Ivan<br/>
Ivan Herman: I think it would be important to have it done. I don’t want to leave you behind or make a resolution while this is still missing.<br/>
Tzviya Siegman: Wendy has been working with the audiobook publishers to try to get a meeting, but it’s difficult to get on the agenda. I like Ivan’s suggestion. A year or so ago we had a meeting with newer members. Not sure how many new members we have, but maybe it’s time.<br/>
Geoff Jukes: +1<br/>
Geoff Jukes: me alone :)<br/>
Laurent Le Meur: +1<br/>
Laurent Le Meur: oh, -1<br/>
Tzviya Siegman: Maybe we’ll talk about that at the chair’s meeting…<br/>
Tzviya Siegman: I agree with Ivan, that we should not have a resolution, as we have incomplete information.<br/>
</details>

**Comment by llemeurfr** [comment]
The choice seems to revolve around:

sol 1: HTML ToC only, with a precise structure and extraction algorithm.
-> i18n friendly, optionally styled, but impossible to validate. If the HTML does not follow the rules, the ToC will be unusable for many UAs (those which don't display the HTML as-is, but rather sanitize the content and extract a simple string based structure for native display). To process the HTML structure, the UA has to load the DOM first (processing the serialized HTML would be a nightmare). 

sol 2: HTML ToC (still highly structured) with a JSON fallback. 
-> The JSON structure is not styled, and has some limitations relative to mixed languages, but it is easy to validate and easy to process to a UA. If the HTML ToC is present, the UA will use it 
 (see sol 1). If not, the JSON structure will be used instead. A UA which intends to present an HTML ToC will have to transform JSON to HTML first, using its own styling rules. 

Whatever the solution is, Audiobook publishers will need an interactive tool to create a ToC out of a friendly UX (a ToC generator).  Therefore I don't really see why Audiobook publishers should prefer one solution over the other. For UAs, my personal take is that because the UA must be able to process the HTML ToC, it's less of a burden to have one use case only, i.e. HTML only (as JSON only is not one the table anymore).

**Comment by TzviyaSiegman** [comment]
Proposal: Restricted HTML as described in current draft

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/publishing/groups/publ-wg/Meetings/Minutes/2019/2019-03-25-pwg.html#section2).

- `RESOLVED:  the TOC is encoded using the restricted HTML as defined in the WPUB spec, and that is the only way it can be done`
<details><summary><i class="differentiate">View the transcript</i></summary>
2. TOC in Manifest issue<br/>
Tzviya Siegman: <a href="https://github.com/w3c/wpub/issues/376">https://github.com/w3c/wpub/issues/376</a><br/>
Tzviya Siegman: I think we may actually be able to close this with Wendy’s help. We have #376.<br/>
… there are numerous comments on this. I put a proposal as the last comment. Based on discussions and with many of the people of how TOCs exist in audiobooks. Wendy - anything to add?<br/>
Wendy Reid: That’s it…<br/>
Proposed resolution: Restricted HTML as described in current draft is the TOC as encoded in Manifest (Tzviya Siegman)<br/>
Tzviya Siegman: the discussion is mostly about how the TOC is noted in the manifest. This is about whether - how the algorithm works in the manifest…<br/>
Ivan Herman: I will try - (typing)<br/>
Proposed resolution: the TOC is encoded using the restricted HTML as defined in the WPUB spec, and that is the only way it can be done (Ivan Herman)<br/>
Brady Duga: +1<br/>
Ivan Herman: +<br/>
Ivan Herman: +1<br/>
Tzviya Siegman: +1<br/>
Ric Wright: +1<br/>
Wendy Reid: +1<br/>
Nick Ruffilo: +1<br/>
Tim Cole: +1<br/>
Benjamin Young: +1<br/>
Bill Kasdorf: +1<br/>
Laurent Le Meur: 0<br/>
Luc Audrain: +1<br/>
Dave Cramer: +1<br/>
Mateus Teixeira: +1<br/>
Tzviya Siegman: Resolved!<br/>
Resolution #2: the TOC is encoded using the restricted HTML as defined in the WPUB spec, and that is the only way it can be done<br/>
Ivan Herman: (Issue can be closed)<br/>
</details>
