### ISSUE TITLE
Other link-like elements allowed in the (HTML) TOC?

### ISSUE THREAD

**Issue by iherman** [w3c/wpub#377]
The current HTML [TOC model and algorithm](https://w3c.github.io/wpub/#app-toc-structure) restricts the actual "links" to content to the HTML `<a>` element. The question is whether it is worth and possible to expand it to:

1. `<img>`
2. `<audio>` and `<video>`
3. `<object>`

(`<object>` may be important for SVG content; including SVG via the `<img>` element may restrict SVG.)

**Comment by rdeltour** [comment]
> these elements, though usable as simple links

What do you mean?

Is there a real-life example of such a ToC, without these elements being wrapped in `a` elements in the first place?

**Comment by iherman** [comment]
@rdeltour 

> Is there a real-life example of such a ToC, without these elements being wrapped in a elements in the first place?

I do not know, I am just asking... If there is no real-life example then we can safely drop this. But it is worth asking...

**Comment by rdeltour** [comment]
OK 🙂 What I'm not sure I understand is how these elements (media elements, `img`, and `object`) would constitue a "link", more than any other flow content elements: are you thinking about interpreting these as links to the referenced media resources, e.g. in an audio book or comic book? If yes, then I think we should stick to HTML's semantics, with only `a` representing a link in the ToC.

We could, however, amend the algorithm to allow SVG links in an SVG-marked-up ToC?

**Comment by iherman** [comment]
Yes, I though of extracting links from these elements indeed.

**Comment by iherman** [comment]
All in all... @rdeltour made me realize that this was probably a stupid idea. I will close the issue, to avoid muddling the waters...

To use an SVG marked up TOC may be a nice idea if it is realistic. If so, it should be a separate issue, though.
