### ISSUE TITLE
Requesting TAG design review of WPUB spec

### ISSUE THREAD

**Issue by dauwhe** [w3c/wpub#384]
I believe we should request that the TAG review the Web Publications spec sometime soon. 

We would initiate this by filing an issue in the TAG's [design review](https://github.com/w3ctag/design-reviews) repository. We would need to provide links to our specs and our explainers—conveniently enough, we have explainers now!

A recent example of another group requesting TAG review can be found [here](https://github.com/w3ctag/design-reviews/issues/331). 

To prepare for this as a group, I think we should

1. Review and improve our explainers: 
[link to WPUB explainer](https://github.com/w3c/wpub/blob/master/explainers/wpub-explainer.md)
[link to Audio explainer](https://github.com/w3c/wpub/blob/master/explainers/audio-explainer.md)

2. Look through some of the existing TAG reviews. In particular, they like to ask if we've done a [security/privacy review](https://www.w3.org/TR/security-privacy-questionnaire/), and if we're familiar with the TAG's [API design principles](https://w3ctag.github.io/design-principles/). The latter should be looked at by those of us working on the WebIDL. 

3. Perhaps continue to try to answer questions that the TAG has asked in the past. I've included this in the explainer, but Andrew Betts, then on the TAG,  [did provide feedback to us](https://github.com/w3c/wpub/issues/32#issuecomment-362273649) which I don't think we've fully digested.

**Comment by TzviyaSiegman** [comment]
see https://github.com/w3ctag/design-reviews/issues/344

**Comment by iherman** [comment]
See #417 for the Tag review. @dauwhe, should we close this issue?

**Comment by iherman** [comment]
@wareid @TzviyaSiegman shouldn't we close this issue?
