### ISSUE TITLE
Project Scope

### ISSUE THREAD

**Issue by geoffjukes** [w3c/wpub#400]
I would be grateful if someone could, as plainly speaking as possible, explain the difference in scope between this project, and the pwpub project?

**Comment by TzviyaSiegman** [comment]
@geoffjukes Excellent question. Sorry it hasn't been clear. Here is the very short answer:

wpub is publications on a user agent, no packaging.
The current version of the wpub spec is simply metadata and manifest.
pwpub defines a packaging mechanism for wpub.

**Comment by geoffjukes** [comment]
Thanks @TzviyaSiegman. As a primarily infrastructure and operations engineer, I am not fully clear on your use of the term "User Agent".

If I use the words "Online" and "Offline" as being use-cases for Web publications. Would it be a stretch to say that this project is focused on the standards for providing "Online" access to a publication, and the `pwpub` project is focused on collecting those "online" resources into a single file, for access "offline"?

**Comment by wareid** [comment]
"User Agent" for our purposes is any platform that would display/use Web Publications, this is pretty broad, but can include web browsers, reading apps, devices, etc etc. Most of the time we're usually referring to web browsers/agents that use web views for rendering. 

Your use cases for online and offline are correct! There's a little more nuance (what happens to an "online" WP if you just happen to leave an area with Wifi?), but when we talk about "offlining" something, we are referring to packaging it or downloading it.
