### ISSUE TITLE
Why list resources for links?

### ISSUE THREAD

**Issue by mattgarrish** [w3c/wpub#406]
I'm not sure I understand the point of this:

> The links list SHOULD include resources necessary to render a linked resource (e.g., scripts, images, style sheets).

We mention links being used for resources that aren't critical to the rendering and for links out to other content. Neither of these cases lends itself to listing dependencies, does it?

Seems like it may have been related to an unrealized or removed use case.

**Comment by iherman** [comment]
I agree, this seems to be an editorial mistake. That remark is relevant for the separate `resources` but not for this one...

**Comment by mattgarrish** [comment]
Closing as this was removed with PR #407.
