### ISSUE TITLE
Normative references to expected values of "accessibility" properties are unclear.

### ISSUE THREAD

**Issue by jasonjgw** [w3c/wpub#422]
In the table in section 2.6.4.1, "expected value" links in the "required value" column refer to W3C wiki pages. However, wiki pages are inappropriate to cite as normative references, as they can change at any time.

On the other hand, the metadata properties have schema.org mappings, and schema.org is listed among this specification's normative references. Hence one might conclude that the schema.org pages are meant to be the normative references for the required values. However, this is unclear in the text of the specification as it currently stands. I think this should be clarified for both Web publication authors and for implementation purposes.

**Comment by iherman** [comment]
@avneeshsingh @danielweck @rdeltour  can you clarify this?

We may have to ask the director about this, to see how these references can/should be used normatively.

**Comment by laudrain** [comment]
I agree with @jasonjgw that we should rely directly to schema.org for accessibility metadata properties in WPUB too, as we already do in EPUB3 Accessibility 1.0.

**Comment by avneeshsingh** [comment]
the intention to have values on wiki is to allow a lighter weight process to update it. I understand the concern of having a strong requirement on the wiki page. 
One way can be to ask director about it. The other way can be that we clarify that the values are expected to be updated as per the needs of the community and we provide non-normitive link to the wiki page. @mattgarrish, what are your thoughts for providing clarification?

**Comment by mattgarrish** [comment]
I'd just note that schema.org also references the wiki for the expected values. That's because they don't want to own the value space, but would rather have the owners of the terms be responsible for them. That was determined to be the most appropriate place to document them when we developed the properties.

Why is it an issue, though? HTML references the microformats wiki for link relationships, for example.

**Comment by mattgarrish** [comment]
Closing this issue as the "expected values" links have been removed and replaced with a note at the end of the table n #449 that informatively references the wiki.
