### ISSUE TITLE
Change rel URLs to tokens

### ISSUE THREAD

**Issue by mattgarrish** [w3c/wpub#431]
As noted in the [tag feedback](https://github.com/w3ctag/design-reviews/issues/344#issuecomment-485034489), the use of URLs for relations is an uncommon choice. It also means that if we don't standardize these with IANA before publishing, existing content will either have to be changed or user agents will forever be stuck supporting the URLs.

In the interests of clarity, can we just change:

- https://www.w3.org/ns/wp#cover -> cover
- https://www.w3.org/ns/wp#accessibility-report -> accessibility-report
- https://www.w3.org/ns/wp#pagelist -> pagelist (or page-list)

and deal with IANA registration separately?

**Comment by iherman** [comment]
I do not have a problem with that; the arguments are compelling.

**Comment by HadrienGardeur** [comment]
> [...] the use of URLs for relations is an uncommon choice

Actually it isn't. URLs are usually recommended as an extensibility mechanism for rel values:

https://tools.ietf.org/html/rfc5988#section-4.2

>  Applications that don't wish to register a relation type can use an extension relation type, which is a URI [RFC3986] that uniquely identifies the relation type.

If the proposed tokens get registered at IANA, it's fine though because there's no reason to use an URL in this case.

**Comment by mattgarrish** [comment]
> If the proposed tokens get registered at IANA, it's fine though because there's no reason to use an URL in this case.

This is what makes them an odd choice. We're planning to register them, as we say in the notes for each, and URLs are only for relations you don't intend to register.

If for some reason they get rejected, then we should look at how else they might be expressed.
