### ISSUE TITLE
There are 2 lines of "datePublished" at "F. Properties Index"

### ISSUE THREAD

**Issue by toshiakikoike** [w3c/wpub#437]
https://w3c.github.io/wpub/#properties-index

There are 2 lines of "datePublished";
> datePublished | § 2.6.3.6 Publication Date |  
> datePublished | § 2.6.3.6 Publication Date |  

Is this a simple writing mistake?

**Comment by mattgarrish** [comment]
Yes, looks like a copy/paste error. I'll fix when I have a minute.
