### ISSUE TITLE
Default natural language

### ISSUE THREAD

**Issue by murata0204** [w3c/wpub#45]
At present, the default is English in [the WP draft](https://w3c.github.io/wpub/).  But it should be unknown, as in [HTML5](https://www.w3.org/TR/html5/dom.html#the-lang-and-xml:lang-attributes).

**Comment by mattgarrish** [comment]
Yes, see issue #42.

The pending PR fallback for this ends with "und", since language is required in the info set: https://github.com/w3c/publ-epub-revision/commit/ac5dd29fd91b8ffe071b160eb2165667d50647e8

**Comment by mattgarrish** [comment]
Sorry, preview link is: https://s3.amazonaws.com/pr-preview/mattgarrish/wpub/master.html#language

**Comment by mattgarrish** [comment]
Closing this issue as let's keep any further discussions in 42.
