### ISSUE TITLE
Remove accessibilityControl and accessibilityAPI

### ISSUE THREAD

**Issue by mattgarrish** [w3c/wpub#450]
We've discussed previously for EPUB how these two properties are not very applicable to authoring publications. They also don't make the threshold of being recommended in the EPUB accessibility specification.

Can we agree to remove them from the Web Publications specification, as not listing them doesn't mean they can't be used if someone does find a reason. Let's focus people on the more important ones.

/cc @avneeshsingh @GeorgeKerscher @clapierre

**Comment by avneeshsingh** [comment]
+1 to Remove accessibilityControl and accessibilityAPI. 


With regards
Avneesh
From: Matt Garrish 
Sent: Thursday, May 23, 2019 18:37
To: w3c/wpub 
Cc: Avneesh Singh ; Mention 
Subject: [w3c/wpub] Remove accessibilityControl and accessibilityAPI (#450)

We've discussed previously for EPUB how these two properties are not very applicable to authoring publications. They also don't make the threshold of being recommended in the EPUB accessibility specification.

Can we agree to remove them from the Web Publications specification, as not listing them doesn't mean they can't be used if someone does find a reason. Let's focus people on the more important ones.

/cc @avneeshsingh @GeorgeKerscher @clapierre
