### ISSUE TITLE
is a canonical identifier necessary

### ISSUE THREAD

**Issue by mattgarrish** [w3c/wpub#58]
This issue was raised in #56 by @rdeltour at https://github.com/w3c/wpub/issues/56#issuecomment-325776298. Splitting out here for future resolution.

> I'm still failing to see why we need a "canonical identifier" in the first place, even a loosely-defined one as proposed by @iherman and prosed by @mattgarrish.
> 
> It seems to me that at the minimum we will have:
> 
> - the publication’s URL (however that will be defined)
> - ways to express "identifier" properties (e.g. a dc:identifier property in metadata, wherever that will be allowed).
> - ways to declare links with specific semantics (link@rel), to express for instance a "canonical link" as defined in RFC6596.
> 
> That some systems use this or that as a "canonical" identifier, or require some uniqueness in some specific context, is totally up to implementers. In other words, I don't think the spec even needs to include the terms "canonical identifier". At all.

**Comment by iherman** [comment]
Worth carrying over some of the answers/thread

* https://github.com/w3c/wpub/issues/56#issuecomment-325802199
* https://github.com/w3c/wpub/issues/56#issuecomment-325920692
* https://github.com/w3c/wpub/issues/56#issuecomment-325974034
* https://github.com/w3c/wpub/issues/56#issuecomment-325998052

(Many other things were discussed in that issue, picking these may help to avoid repeating things.)

Also, this comment: https://github.com/w3c/wpub/issues/56#issuecomment-326160538 summarised the proposed changes in the Editor's draft, which is now in place.

**Comment by HadrienGardeur** [comment]
I agree with @rdeltour statement but we don't know yet if we'll have an identifier metadata or a generic link element at a manifest level (this is something that the Web App Manifest doesn't have, but both are available in the Readium Web Publication Manifest).

In general, I'd rather specify high level, flexible and powerful elements like links than create dedicated keys in our JSON syntax for a canonical identifier.

**Comment by westurner** [comment]
Web Annotations linked to a canonical identifier can persist across revisions.

What URI should Web Annotations be attached to?

https://www.w3.org/blog/news/archives/6156

https://www.w3.org/TR/2017/REC-annotation-model-20170223/#bodies-and-targets

https://www.w3.org/TR/annotation-model/#bodies-and-targets

**Comment by westurner** [comment]
https://www.w3.org/TR/2018/WD-wpub-ann-20180104/#selectors

https://www.w3.org/TR/wpub-ann/#selectors

> Selection of part of a Web Resource requires two distinct entities:
>
> - the URL of the overall resource; we will refer to this as the Source (see Locator).
> - the identification for the part of that resource; we will refer to this as the Segment (of Interest).
>
> A Selector specifies how to determine the Segment from within the Source resource. The nature of the Selector is dependent on the selection technique chosen (which determines the class of the Selector) and the media-type of the Source, as the methods to describe Segments from various media-types differ. The Source and the Selector(s) are encapsulated in a Locator.

**Comment by iherman** [comment]
Isn't this issue moot now that we have the manifest mapping to Schema which does have the notion of an address (`url`) and identifer (`id` and/or `identifier`)?

@mattgarrish @TzviyaSiegman
