### ISSUE TITLE
avoiding resource declaration duplication

### ISSUE THREAD

**Issue by mattgarrish** [w3c/wpub#59]
An unresolved issue from #55 that we'll need to return to in the future is resource declaration. We have a resource list and a default reading order, where the latter is a subset of the former.

Some choices include:

- having two separate lists with no duplication, as user agents will be aware those in the default reading order are necessary
- requiring the user agent add the default reading order resources to the infoset list of resources
- requiring the publisher duplicate the resources across lists in the manifest

**Comment by HadrienGardeur** [comment]
Microsoft and the Edge team recently provided feedback that's directly related to this issue through @BCWalters:

> 3.4.2  Resource list
>
>- If taking the web publication offline…Any resource in the default reading order must also be included in the resource list. User agents should ignore the resources not listed in the resource list.
>- Issue 59: Our preference is 3rd proposal from Matt: Requiring the publisher duplicate the resources across lists in the manifest. Again, keep the user-agents simple and consistent which means specifying independent lists if they serve different purposes.

On the Readium side, we decided against duplication with our own [Readium Web Publication Manifest](https://github.com/readium/webpub-manifest).
We consider that everything listed in the default reading order can be pre-loaded, pre-rendered or offlined, while we limit resources from the resource list to preloading and offline access.

I do think that these two lists serve different purposes, but duplication feels unnecessary.

**Comment by BCWalters** [comment]
User agents and production tools clearly consider the list of resources included in the web publication and the reading order as two mostly independent concepts. I say mostly, as user agents may require that items in the default reading order are contained in the resource list. Presumably production tools also consider them as separate concepts.

So, what's the advantage of building a resource set as a union of the two lists rather than requiring them to be specified independently? That strikes me as more error prone for tool chains and user agents to process correctly, and I don't see a strong benefit. I don't think the size of the data is worrisome, though I concede that there may be other benefits like ease of hand-creation of manifests for simple publications.

**Comment by HadrienGardeur** [comment]
> I don't think the size of the data is worrisome, though I concede that there may be other benefits like ease of hand-creation of manifests for simple publications.

This is mostly meant to help with authoring.

EPUB is often criticized for:

- the data duplication between `manifest`, `spine`, the navigation document and NCX
- its use of id/idref

We're somehow trying to solve both issues here.

**Comment by BCWalters** [comment]
I agree with the id/idref critique, but I think the URL to the resource itself can serve as an easy-to-understand and not error-prone common ID across multiple lists.

While duplicate data may be a common criticism historically, I don't agree it's problematic in practice. I think the bigger problem with EPUB is the differences in generating, parsing and correlating these various lists, mapping between EPUB2 and EPUB3, etc. If all of the user-agent readable entries were specified in the same manifest with the same "shape"--i.e., links to the URL, no ids and idrefs, no backwards compatibility concerns--I think the concerns about duplication would be naturally reduced.

**Comment by iherman** [comment]
The [resolution on the F2F](https://www.w3.org/publishing/groups/publ-wg/Meetings/Minutes/2018/2018-05-30-pwg.html#resolution1) says:

> There is an optional list of resources that may be provided to extend the bounds of the publication _beyond the default reading order_ and add section on Boundary determination to spec.

(Emphasis is mine.) This means that the resource list is definitely not duplicating the reading order.

As is resolved at the F2F, I propose to close this issue.
