### ISSUE TITLE
Should linking from manifests support URI templates?

### ISSUE THREAD

**Issue by iherman** [w3c/wpub#67]
URI templates [rfc650](https://tools.ietf.org/html/rfc6570) may be useful features to make external references easier to maintain.

**Comment by HadrienGardeur** [comment]
The current WebIDL allows URI templates, [there's even a member](https://w3c.github.io/wpub/#link-webidl) in our `PublicationLink` dictionary to flag it.

**Comment by iherman** [comment]
I am tempted, nevertheless, to postpone URI templates for a future version. I am not sure it is wise to include it right at the start; not necessarily part of a minimum viable product...

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/publishing/groups/publ-wg/Meetings/Minutes/2019/2019-03-18-pwg#section2-1).

- No actions or resolutions
<details><summary><i class="differentiate">View the transcript</i></summary>
2.1. Should linking from manifests support URI templates?<br/>
Wendy Reid: <a href="https://github.com/w3c/wpub/issues/67">https://github.com/w3c/wpub/issues/67</a><br/>
Wendy Reid: #67 not that important; can close?<br/>
Ivan Herman: +1<br/>
Wendy Reid: Silence == consent<br/>
</details>
