### ISSUE TITLE
Naming the media overlay work

### ISSUE THREAD

**Issue by iherman** [w3c/wpub#69]
The WG discussed, and plans to discuss further, work on media overlays. On the [WG call of 2017.09.18](https://www.w3.org/publishing/groups/publ-wg/Meetings/Minutes/2017/2017-09-18-minutes.html#section1) the term SMIL was used to denote the work. We may want to choose another term...

**Comment by iherman** [comment]
The term "SMIL" is loaded and bound to a specific and, on the Web, relatively unused technology. For strictly social reasons it may be better to use a different SMIL, to avoid misunderstandings.

I personally would use, for the time being at least, Media Overlay (MO) for now. For Web developers this may be a neutral terms, for seasoned EPUB users that refers to the technology that was based on SMIL...

**Comment by GarthConboy** [comment]
Not as fun as "grin"... but, yes, agree "MO" is good for now.

**Comment by iherman** [comment]
Propose closing: this is now in the realm of a separate CG, which also has its own repository: https://github.com/w3c/sync-media-pub.

**Comment by iherman** [comment]
Closing per https://www.w3.org/publishing/groups/publ-wg/Meetings/Minutes/2018/2018-03-12-minutes.html#resolution8
