### ISSUE TITLE
Relationship to the Web Animation work.

### ISSUE THREAD

**Issue by iherman** [w3c/wpub#70]
[Web Animation](https://w3c.github.io/web-animations/) is a fairly new but active work item right now, which could be used as a basis for Media Overlay work; it should be considered as the basis, possibly, for MO.

**Comment by iherman** [comment]
Some references:

* [Web Animation Spec](https://w3c.github.io/web-animations/)
* [Short tutorial on MDN](https://developer.mozilla.org/en-US/docs/Web/API/Web_Animations_API/Using_the_Web_Animations_API)

In short, it provides a general model for time and animation, together with an API. At present, the SVG specification plans to transition to the usage of that model and terminology, to remove links and references to SMIL and, I presume, CSS might also align with it. There are some implementations already available (see also the link to MDN). 

A quote from the intro is particularly important for our possible usage:

> Web Animations defines a model for supporting animation and synchronization on the Web platform. It is intended that other specifications will build on this model and expose its features through declarative means.

**Comment by danielweck** [comment]
WebAnimations is listed in the brainstorming wiki page for "synchronized multimedia" aka "Media Overlays" aka "SMIL lite":
https://github.com/w3c/publ-wg/wiki/Requirements-and-design-options-for-synchronized-multimedia#references

**Comment by iherman** [comment]
Propose closing: this is now in the realm of a separate CG, which also has its own repository: https://github.com/w3c/sync-media-pub.

**Comment by iherman** [comment]
Closing per https://www.w3.org/publishing/groups/publ-wg/Meetings/Minutes/2018/2018-03-12-minutes.html#resolution9
