### ISSUE TITLE
Allow links to multiple publications?

### ISSUE THREAD

**Issue by mattgarrish** [w3c/wpub#76]
When it comes to linking to a manifest and initiating the reading experience, the question is whether to allow resources to link to multiple manifests and solve the problems of selecting from among the available publications, or only use the first link found.

**Comment by mattgarrish** [comment]
To add context, it's simple enough to allow multiple links, but once a resource can include multiple links initiation of the reading experience is no longer a binary yes/no proposition:

- the user agent has to compile all the unique links
- it has to provide an interface that allows selecting from the available links
- it has to provide labels to differentiate the publications (which means either the author needs to provide title attributes/parameters or the manifests have to be parsed)

Assuming we allow HTTP links, there's also the problem of labels and links being mismatched and which gets precedence.

There are scenarios where multiple links might be useful (e.g., full journal v. individual article), but do we want to solve this now or keep things simple?

**Comment by dauwhe** [comment]
I think a first version should be as simple as possible, especially given that a single link will cover so many use cases.

**Comment by iherman** [comment]
Close issue 76, with the comment that a link to the WP(s) MAY be part of the resources, but WP does not require it.

See https://www.w3.org/2017/11/06-pwg-irc#T22-55-42

**Comment by iherman** [comment]
Additional comment from the discussion: the WP does _not_ define how a choice has to be done.
