### ISSUE TITLE
Audiobooks and WPUB

### ISSUE THREAD

**Issue by llemeurfr** [w3c/wpub#78]
It is important to integrate audiobooks (i.e audio only, no text) in the work of this WG, something that has been unsuccessfully tried with EPUB 3.

An audiobook, as currently produced, is made of a sequence of audio files (often mp3) with a specific naming convention. mp3 files can be enriched by some metadata (ID3 tags; https://en.wikipedia.org/wiki/ID3) and in proprietary cases (e.g. Apple M4B format) some metadata (a title, author and genre in the M4B case) can be added to the whole set. 

The Daisy Consortium has released guidelines on how to structure an EPUB 3 audiobook in http://www.daisy.org/ties/navigable-audio-only-epub3-guidelines, but it seems that only few a11y orgs are producing such publications, and this practice was not adopted by mainstream publishers. 

This issue can help finding which metadata would be useful for audiobooks available as Web Publications and EPUB 4 files.

**Comment by HadrienGardeur** [comment]
Aside purely from metadata, there are also a number of other questions that we need to raise:

- can we use audio files in our list of primary resources for a WP? This would be the most logical thing to do for an audiobook
- for audiobooks where a single audio track is used, can we rely on navigation (table of contents) to provide chapter level metadata?
- can we rely on media fragments for such navigation ?

For reference, here's how this could look like using a syntax inspired by the Readium effort:

*Multiple tracks*
```json
"primary": [
  {"href": "chapter1.mp3", "type": "audio/mpeg", "title": "Chapter 1 - The Beginning"},
  {"href": "chapter2.mp3", "type": "audio/mpeg", "title": "Chapter 2 - Continued"},
  {"href": "chapter3.mp3", "type": "audio/mpeg", "title": "Chapter 3 - The End"}
]
```

*Single track plus navigation*

```json
"primary": [
  {"href": "audiobook.mp3", "type": "audio/mpeg"}
],
"navigation": [
  {"href": "audiobook.mp3#t=0,587", "type": "audio/mpeg", "title": "Chapter 1 - The Beginning"},
  {"href": "audiobook.mp3#t=588,1274", "type": "audio/mpeg", "title": "Chapter 2 - Continued"},
  {"href": "audiobook.mp3#t=1275", "type": "audio/mpeg", "title": "Chapter 3 - The End"}
]
```

**Comment by llemeurfr** [comment]
+1 for the support of audio files as primary resources in a WP. 
The json snippet proposed by @HadrienGardeur is up to the point: easy to create, easy to process, with a structure that is compatible with text-first publications, and reuses W3C standards = [media fragments](https://www.w3.org/TR/media-frags/#valid-uri-temporal).

**Comment by danielweck** [comment]
The navigation requirements for DAISY talking books and EPUB3 Media Overlays (full-text full-audio and audio-only) are pretty much the same: coarse or fine, flat or hierarchical (depending on the authors needs) headings structure to match chaptering / sectioning in the main content. Special list of landmarks, for quick access to tables, figures, print page breaks, etc.
Advanced features include:
Escapability, to identify complex structures that readers / listeners can jump out of during the reading / playback experience. Skippability, to identify optional fragments of content that users can skip (e.g. footnotes, page breaks, etc.)

**Comment by danielweck** [comment]
Reminder (draft notes)
https://github.com/w3c/publ-wg/wiki/Requirements-and-design-options-for-synchronized-multimedia

**Comment by HadrienGardeur** [comment]
Any update post-TPAC on audiobooks? cc @iherman

**Comment by iherman** [comment]
Not specifically on audio books, but we had a [session on media overlays](https://www.w3.org/publishing/groups/publ-wg/Meetings/Minutes/2017/2017-11-07-minutes.html#section2) with further steps planned.

**Comment by HadrienGardeur** [comment]
We need to at least decide if pointing directly to audio files will be OK in the context of a WP.

**Comment by iherman** [comment]
In some sense, the whole discussion on the entry page came out of this issue (and the related issue raised by Samuel on mangas/BDs). I am not sure it was documented, so I give my own interpretation only: it should be possible to have a WP that includes audio or images files only for the 'content' (that is the authors' choice) but, mainly for "starting up" a WP it is important to have some entry point that today's browsers also understand.

**Comment by HadrienGardeur** [comment]
So, for audiobooks and comics, that "entry point" could serve some sort of viewer as well?

**Comment by iherman** [comment]
Could. Or could trigger an implementation that is the general viewer. The details are still fuzzy, of course.

**Comment by HadrienGardeur** [comment]
OK, but the door is open to the idea of having audio or images for the "content" as long as the entry point remains HTML, that's good to know.

**Comment by TzviyaSiegman** [comment]
assigned to Wendy Reid

**Comment by clapierre** [comment]
I am working with a group building EPUBs for countries with limited TTS support for their native language and the books they are creating are children's audio books with MediaOverlays but the images only have the ability for alt text which is textual only and therefor unable to be read to the child.  We need to also support media overlays for an alt/extended description of the images.

**Comment by TzviyaSiegman** [comment]
This issue is addressed by subsequent issues.
