### ISSUE TITLE
Minor editorial glitch

### ISSUE THREAD

**Issue by WSchindler** [w3c/wpub#82]
In the terminolgy section at **Web Publication Canonical Identifier** we should replace  "A c**o**nonical identifier that is an IRI, or a locator mapped from a canonical identifier, can be referred to as an Identifying IRI." by "A c**a**nonical identifier that is an IRI, or a locator mapped from a canonical identifier, can be referred to as an Identifying IRI. "

**Comment by iherman** [comment]
@WSchindler I do not see it... Are you sure you are looking at the right version of the document? Or should I change my glasses?

**Comment by WSchindler** [comment]
I was looking at [https://rawgit.com/w3c/wpub/8b3d570bb3c2106e2fc754119369bd4a434067f3/index.html](url) which has today's date but where a lot of stuff is missing *rather puzzled*

**Comment by mattgarrish** [comment]
The latest editor's draft is at: https://w3c.github.io/wpub/

The date in the raw files is meaningless, as it's always the current day -- it's inserted by script.

It looks like you have a link to a commit in an old pull request: https://github.com/w3c/wpub/pull/17/commits

How did you get to that page?

**Comment by mattgarrish** [comment]
Whatever the case, closing this as a non-issue to fix.
