### ISSUE TITLE
Privacy: Should WP restrict and/or gate access to some OWP features?

### ISSUE THREAD

**Issue by lrosenthol** [w3c/wpub#92]
Access to some OWP features should probably either be disallowed or require a user consent: 

- Geolocation
- camera
- microphone
- desktop-notifications
- push
- full-screen
- turning off mouse-cursor
- system exclusive midi
- clipboard-access

**Comment by lrosenthol** [comment]
Committee agreed (at TPAC) that there are no restrictions for WP, we may revisit for PWP.

However, there are other Privacy issues which will appear in separate issues

**Comment by caraya** [comment]
The following items in your list already require user permission/consent to use:

- Geolocation
- camera
- microphone
- desktop-notifications
- push

Other Feature/APIs require user action to activate and should not be automated:

full-screen
turning off mouse-cursor
system exclusive midi
clipboard-access
